/* Question Mark questions (question-mark/question-mark.html) — the game reads only this file.
   Adapted from the Jeopardy bank (shared/jeopardy-bank.js) but kept separate so the two games can diverge.
   Rules: every question stands on its own without the category label; 5–17 words; no brackets or blanks;
   the answer is not in the question; franchise questions name the franchise at varying positions.
   Item: {q, a, rank 1–15 (easiest first; Easy = 1–5), cefr, alt?}. Validate: node question-mark/validate.js */
(function (root) {
var questions = {
  "Animals": [
    {"q":"What is the largest land animal?","a":"elephant","rank":1,"cefr":"A1","alt":["African elephant"]},
    {"q":"What is the fastest land animal?","a":"cheetah","rank":2,"cefr":"A1"},
    {"q":"What do we call a baby dog?","a":"puppy","rank":3,"cefr":"A1"},
    {"q":"What is the largest animal that lives in the ocean?","a":"blue whale","rank":4,"cefr":"A2"},
    {"q":"What do we call a baby cat?","a":"kitten","rank":5,"cefr":"A2"},
    {"q":"Which bird cannot fly but runs very fast?","a":"ostrich","rank":6,"cefr":"A2"},
    {"q":"What is the tallest animal in the world?","a":"giraffe","rank":7,"cefr":"B1"},
    {"q":"Which animal is known for changing its skin color?","a":"chameleon","rank":8,"cefr":"B1"},
    {"q":"What do we call a group of lions?","a":"a pride","rank":9,"cefr":"B1"},
    {"q":"Which animal has the longest lifespan among land animals?","a":"tortoise","rank":10,"cefr":"B1","alt":["Galapagos tortoise","elephant"]},
    {"q":"Which mammal is the only one that can truly fly?","a":"bat","rank":11,"cefr":"B2"},
    {"q":"What is a group of crows called?","a":"a murder","rank":12,"cefr":"B2"},
    {"q":"Which animal sleeps the most hours per day?","a":"koala","rank":13,"cefr":"B2","alt":["sloth"]},
    {"q":"What is unique about a platypus, besides laying eggs?","a":"it is venomous","rank":14,"cefr":"B2","alt":["it produces venom","electroreception"]},
    {"q":"Which living animal has the strongest bite force ever measured?","a":"saltwater crocodile","rank":15,"cefr":"B2"}
  ],
  "Brazilian Capitals": [
    {"q":"Which Brazilian city was built in the 1950s to be the new capital?","a":"Brasília","rank":1,"cefr":"A1","alt":["Brasilia"]},
    {"q":"Which state capital is the biggest city in Brazil?","a":"São Paulo","rank":2,"cefr":"A1","alt":["Sao Paulo"]},
    {"q":"Which state capital has Sugarloaf Mountain and Copacabana beach?","a":"Rio de Janeiro","rank":3,"cefr":"A1"},
    {"q":"Which southern state capital is famous for its Botanical Garden and tube bus stops?","a":"Curitiba","rank":4,"cefr":"A2"},
    {"q":"Which Brazilian state capital do people often call 'BH' for short?","a":"Belo Horizonte","rank":5,"cefr":"A2"},
    {"q":"Which state capital was Brazil's first capital city?","a":"Salvador","rank":6,"cefr":"A2"},
    {"q":"What is the southernmost state capital in Brazil?","a":"Porto Alegre","rank":7,"cefr":"B1"},
    {"q":"Which state capital is called the 'Brazilian Venice' because of its bridges?","a":"Recife","rank":8,"cefr":"B1"},
    {"q":"Which state capital is mostly on an island and called 'Floripa'?","a":"Florianópolis","rank":9,"cefr":"B1","alt":["Florianopolis"]},
    {"q":"Which northeastern state capital's name means 'fortress' in English?","a":"Fortaleza","rank":10,"cefr":"B1","alt":["Ceara"]},
    {"q":"Which state capital sits in the middle of the Amazon rainforest?","a":"Manaus","rank":11,"cefr":"B2"},
    {"q":"Which state capital near the mouth of the Amazon hosted COP30 in 2025?","a":"Belém","rank":12,"cefr":"B2","alt":["Belem","Para"]},
    {"q":"Which state capital is famous as the home of sertanejo music?","a":"Goiânia","rank":13,"cefr":"B2","alt":["Goiania"]},
    {"q":"Which state capital's name means 'big field' in English?","a":"Campo Grande","rank":14,"cefr":"B2"},
    {"q":"Which state capital, founded in 1989, is the newest in Brazil?","a":"Palmas","rank":15,"cefr":"B2"}
  ],
  "Brazilian Cars": [
    {"q":"What color is commonly associated with taxis in Brazil?","a":"yellow","rank":1,"cefr":"A1"},
    {"q":"What American brand makes the popular Onix model sold in Brazil?","a":"Chevrolet","rank":2,"cefr":"A1"},
    {"q":"What is the Portuguese word for 'car'?","a":"carro","rank":3,"cefr":"A1"},
    {"q":"What Volkswagen model, iconic in Brazil, is nicknamed 'Fusca'?","a":"Beetle","rank":4,"cefr":"A2","alt":["VW Beetle","Fusca"]},
    {"q":"What Fiat model is one of the best-selling cars in Brazil?","a":"Fiat Mobi","rank":5,"cefr":"A2","alt":["Fiat Strada","Fiat Argo","Fiat Palio","Strada","Argo","Mobi"]},
    {"q":"What fuel type, made from sugarcane, is widely used in Brazilian cars?","a":"ethanol","rank":6,"cefr":"A2"},
    {"q":"What term describes a car that can run on both gasoline and ethanol?","a":"flex-fuel","rank":7,"cefr":"B1","alt":["flex"]},
    {"q":"What was the first car mass-produced in Brazil, built starting in 1956?","a":"Romi-Isetta","rank":8,"cefr":"B1"},
    {"q":"What popular pickup truck is made by Fiat in Brazil?","a":"Fiat Toro","rank":9,"cefr":"B1","alt":["Toro"]},
    {"q":"What Volkswagen car was Brazil's best-selling car for 27 years in a row?","a":"Gol","rank":10,"cefr":"B1","alt":["VW Gol","Volkswagen Gol"]},
    {"q":"In what year did Brazil stop making the Volkswagen Beetle, the Fusca?","a":"1996","rank":11,"cefr":"B2","alt":["1986"]},
    {"q":"Which area near São Paulo, named after three cities, is the center of Brazil's car industry?","a":"the ABC Paulista","rank":12,"cefr":"B2","alt":["ABC","ABC region"]},
    {"q":"What do Brazilians call a cheap car with a small 1.0 engine?","a":"carro popular","rank":13,"cefr":"B2","alt":["popular car"]},
    {"q":"What Chinese brand makes electric and hybrid cars at a factory in Bahia?","a":"BYD","rank":14,"cefr":"B2","alt":["1.0"]},
    {"q":"What independent Brazilian automaker was a pioneer of beach buggies before it closed in the 1990s?","a":"Gurgel","rank":15,"cefr":"B2"}
  ],
  "Famous Landmarks": [
    {"q":"In which country can you climb the Eiffel Tower?","a":"France","rank":1,"cefr":"A1"},
    {"q":"The Great Wall was built to protect which country?","a":"China","rank":2,"cefr":"A1"},
    {"q":"The Statue of Liberty was a gift from France to which country?","a":"USA","rank":3,"cefr":"A1","alt":["United States"]},
    {"q":"Gladiators once fought in the Colosseum in which country?","a":"Italy","rank":4,"cefr":"A2"},
    {"q":"Christ the Redeemer looks down over Rio in which country?","a":"Brazil","rank":5,"cefr":"A2"},
    {"q":"The Taj Mahal, a white marble building, is in which country?","a":"India","rank":6,"cefr":"A2"},
    {"q":"Which South American country is home to Machu Picchu?","a":"Peru","rank":7,"cefr":"B1"},
    {"q":"Big Ben is the famous clock tower of which country?","a":"England","rank":8,"cefr":"B1","alt":["UK","United Kingdom"]},
    {"q":"The pyramids of Giza stand near Cairo in which country?","a":"Egypt","rank":9,"cefr":"B1"},
    {"q":"Which country has the Sydney Opera House by its harbor?","a":"Australia","rank":10,"cefr":"B1"},
    {"q":"Petra, a city carved into pink rock, is in which country?","a":"Jordan","rank":11,"cefr":"B2"},
    {"q":"Chichén Itzá, an old Mayan pyramid, is in which country?","a":"Mexico","rank":12,"cefr":"B2"},
    {"q":"Gaudí's unfinished church, the Sagrada Família, is in which country?","a":"Spain","rank":13,"cefr":"B2"},
    {"q":"Angkor Wat, the largest temple complex in the world, is in which country?","a":"Cambodia","rank":14,"cefr":"B2"},
    {"q":"In which country does the Blue Mosque stand, in Istanbul?","a":"Turkey","rank":15,"cefr":"B2"}
  ],
  "Flags": [
    {"q":"What two colors are on the flag of Japan?","a":"white and red","rank":1,"cefr":"A1","alt":["red and white"]},
    {"q":"What color is the maple leaf on Canada's flag?","a":"red","rank":2,"cefr":"A1"},
    {"q":"What shape is on the flag of Brazil, besides the circle?","a":"a rhombus/diamond","rank":3,"cefr":"A1","alt":["diamond","rhombus"]},
    {"q":"How many stars are on the current flag of the USA?","a":"50","rank":4,"cefr":"A2"},
    {"q":"What color is the star on the flag of Turkey?","a":"white","rank":5,"cefr":"A2"},
    {"q":"Which country's flag is a simple red circle on a white background?","a":"Japan","rank":6,"cefr":"A2"},
    {"q":"What word is written on Brazil's flag?","a":"Ordem e Progresso","rank":7,"cefr":"B1"},
    {"q":"What animal appears on the flag of Mexico?","a":"an eagle","rank":8,"cefr":"B1","alt":["eagle"]},
    {"q":"What three colors make up the flag of Italy?","a":"green, white, and red","rank":9,"cefr":"B1"},
    {"q":"What animal is depicted on the flag of Sri Lanka?","a":"a lion","rank":10,"cefr":"B1","alt":["lion"]},
    {"q":"What is the only national flag that is not rectangular?","a":"Nepal","rank":11,"cefr":"B2"},
    {"q":"How many points does the star have on the flag of Chile?","a":"5","rank":12,"cefr":"B2"},
    {"q":"What shape is the white cross on the flag of Switzerland?","a":"a plus sign/equilateral cross","rank":13,"cefr":"B2","alt":["cross","plus sign"]},
    {"q":"Which country has a flag almost the same as Romania's flag?","a":"Chad","rank":14,"cefr":"B2","alt":["Moldova"]},
    {"q":"How many gold stars are in the circle on the European Union flag?","a":"12","rank":15,"cefr":"B2","alt":["twelve"]}
  ],
  "Food and Drink": [
    {"q":"What do you call the first meal of the day?","a":"breakfast","rank":1,"cefr":"A1"},
    {"q":"What white drink comes from cows?","a":"milk","rank":2,"cefr":"A1"},
    {"q":"What yellow spread, made from cream, do people put on bread?","a":"butter","rank":3,"cefr":"A1","alt":["cheese","jam"]},
    {"q":"What do you call a meal eaten in the middle of the day?","a":"lunch","rank":4,"cefr":"A2"},
    {"q":"What hot drink is made from roasted beans?","a":"coffee","rank":5,"cefr":"A2"},
    {"q":"What do you call food that is not cooked?","a":"raw","rank":6,"cefr":"A2"},
    {"q":"What word describes food with a lot of spice that burns your mouth?","a":"spicy","rank":7,"cefr":"B1"},
    {"q":"What do you call the list of dishes in a restaurant?","a":"menu","rank":8,"cefr":"B1"},
    {"q":"What word means 'without meat' in a diet?","a":"vegetarian","rank":9,"cefr":"B1"},
    {"q":"What do you call money left for a waiter after a meal?","a":"tip","rank":10,"cefr":"B1"},
    {"q":"What is the French term for a light snack served before a meal?","a":"hors d'oeuvre","rank":11,"cefr":"B2","alt":["appetizer"]},
    {"q":"What word describes meat cooked slowly in liquid?","a":"braised","rank":12,"cefr":"B2","alt":["stewed"]},
    {"q":"What do you call a chef's special selection of small dishes to taste?","a":"tasting menu","rank":13,"cefr":"B2","alt":["degustation"]},
    {"q":"What do you call a party where every guest brings a dish to share?","a":"potluck","rank":14,"cefr":"B2","alt":["potluck dinner"]},
    {"q":"What cooking method uses very high heat with little oil, tossing quickly?","a":"stir-frying","rank":15,"cefr":"B2"}
  ],
  "Fortnite": [
    {"q":"What is the name of the flying bus that drops Fortnite players onto the map?","a":"the Battle Bus","rank":1,"cefr":"A1","alt":["Battle Bus"]},
    {"q":"In Fortnite, what is the shrinking circle that forces players together?","a":"the storm","rank":2,"cefr":"A1","alt":["the storm circle"]},
    {"q":"What do Fortnite players collect to build walls, ramps and floors?","a":"materials","rank":3,"cefr":"A1","alt":["resources","wood/stone/metal"]},
    {"q":"What is the in-game currency used to buy skins in Fortnite?","a":"V-Bucks","rank":4,"cefr":"A2"},
    {"q":"What color shows that a Fortnite weapon is Legendary?","a":"orange","rank":5,"cefr":"A2","alt":["gold"]},
    {"q":"What do Fortnite players call a full outfit for their character?","a":"a skin","rank":6,"cefr":"A2","alt":["skin","outfit"]},
    {"q":"In a standard Fortnite match, how many players land on the island?","a":"100","rank":7,"cefr":"B1"},
    {"q":"What seasonal reward track do Fortnite players buy to unlock cosmetics?","a":"the Battle Pass","rank":8,"cefr":"B1","alt":["Battle Pass"]},
    {"q":"What do you win in Fortnite when you are the last player standing?","a":"Victory Royale","rank":9,"cefr":"B1"},
    {"q":"Which building material in Fortnite is the strongest but slowest to build?","a":"metal","rank":10,"cefr":"B1"},
    {"q":"What was the 2019 Fortnite event called when a black hole swallowed the map?","a":"The End","rank":11,"cefr":"B2","alt":["the black hole event","Chapter 1 finale"]},
    {"q":"In Fortnite, what do you do to help a knocked-down teammate get back up?","a":"revive them","rank":12,"cefr":"B2","alt":["revive","reviving"]},
    {"q":"What do Fortnite players call landing in a busy area at the start of a match?","a":"dropping hot","rank":13,"cefr":"B2","alt":["hot dropping"]},
    {"q":"What do Fortnite players call building walls all around themselves in a fight?","a":"turtling","rank":14,"cefr":"B2","alt":["building up"]},
    {"q":"What glowing boxes in Fortnite hold weapons and make a humming sound?","a":"chests","rank":15,"cefr":"B2","alt":["treasure chests"]}
  ],
  "Fruits": [
    {"q":"What yellow fruit do monkeys love to eat?","a":"banana","rank":1,"cefr":"A1"},
    {"q":"What red fruit is often used in a pie and keeps the doctor away?","a":"apple","rank":2,"cefr":"A1"},
    {"q":"What citrus fruit has the same name as its color?","a":"orange","rank":3,"cefr":"A1"},
    {"q":"What small red fruit is used to make jam and grows on bushes?","a":"strawberry","rank":4,"cefr":"A2"},
    {"q":"What small orange fruit, related to the peach, has fuzzy skin and a single pit?","a":"apricot","rank":5,"cefr":"A2"},
    {"q":"What green or purple small fruit grows in bunches and is used to make wine?","a":"grape","rank":6,"cefr":"A2"},
    {"q":"What tropical fruit is green outside, has a large pit, and is often used in guacamole?","a":"avocado","rank":7,"cefr":"B1"},
    {"q":"What yellow citrus fruit is very sour and used in lemonade?","a":"lemon","rank":8,"cefr":"B1"},
    {"q":"What small red or black fruit grows on thin canes and has a hollow center?","a":"raspberry","rank":9,"cefr":"B1","alt":["blackberry"]},
    {"q":"What tropical yellow fruit is spiky on the outside with sweet segments inside?","a":"pineapple","rank":10,"cefr":"B1"},
    {"q":"What fruit is a hybrid of a plum and an apricot?","a":"pluot","rank":11,"cefr":"B2","alt":["plumcot"]},
    {"q":"Which Brazilian fruit with a small black seed is used in energy drinks?","a":"guaraná","rank":12,"cefr":"B2","alt":["guarana"]},
    {"q":"What purple/black fruit, common in the Amazon, is used in bowls and smoothies?","a":"açaí","rank":13,"cefr":"B2","alt":["acai"]},
    {"q":"What tropical fruit is known as the 'king of fruits' in Southeast Asia for its strong smell?","a":"durian","rank":14,"cefr":"B2"},
    {"q":"What fruit has a hard shell, milky white flesh, and grows on palm trees?","a":"coconut","rank":15,"cefr":"B2"}
  ],
  "Geography": [
    {"q":"What is the largest continent?","a":"Asia","rank":1,"cefr":"A1"},
    {"q":"What is the largest ocean?","a":"Pacific Ocean","rank":2,"cefr":"A1","alt":["Pacific"]},
    {"q":"What is the smallest continent?","a":"Australia","rank":3,"cefr":"A1","alt":["Oceania"]},
    {"q":"What is the longest river in the world?","a":"Nile","rank":4,"cefr":"A2","alt":["Amazon"]},
    {"q":"What is the tallest mountain in the world?","a":"Mount Everest","rank":5,"cefr":"A2","alt":["Everest"]},
    {"q":"What is the largest country by area?","a":"Russia","rank":6,"cefr":"A2"},
    {"q":"Which cold desert is the largest desert in the world?","a":"Antarctic Desert","rank":7,"cefr":"B1","alt":["Antarctica"]},
    {"q":"What is the largest hot desert in the world?","a":"Sahara","rank":8,"cefr":"B1"},
    {"q":"Which country currently has the largest population in the world?","a":"India","rank":9,"cefr":"B1","alt":["China"]},
    {"q":"What is the driest place on Earth?","a":"Atacama Desert","rank":10,"cefr":"B1","alt":["Death Valley","McMurdo Dry Valleys"]},
    {"q":"What is the deepest point in the ocean?","a":"Mariana Trench","rank":11,"cefr":"B2","alt":["Challenger Deep"]},
    {"q":"What line of latitude divides the Earth into Northern and Southern hemispheres?","a":"the Equator","rank":12,"cefr":"B2","alt":["Equator"]},
    {"q":"Which strait separates Asia and North America?","a":"Bering Strait","rank":13,"cefr":"B2"},
    {"q":"What is the largest island in the world?","a":"Greenland","rank":14,"cefr":"B2"},
    {"q":"What is the saltiest large body of water, famous for floating in it?","a":"the Dead Sea","rank":15,"cefr":"B2","alt":["Dead Sea"]}
  ],
  "Harry Potter": [
    {"q":"What is the name of the school Harry Potter attends?","a":"Hogwarts","rank":1,"cefr":"A1"},
    {"q":"In the Harry Potter books, who is Harry's best friend with red hair?","a":"Ron Weasley","rank":2,"cefr":"A1","alt":["Ron"]},
    {"q":"What magical sport do Harry Potter and his friends play on broomsticks?","a":"Quidditch","rank":3,"cefr":"A1"},
    {"q":"What is the name of Harry Potter's white owl?","a":"Hedwig","rank":4,"cefr":"A2"},
    {"q":"Which Hogwarts house is Harry Potter sorted into?","a":"Gryffindor","rank":5,"cefr":"A2"},
    {"q":"Who is the dark wizard who tries to kill Harry Potter?","a":"Voldemort","rank":6,"cefr":"A2","alt":["Lord Voldemort"]},
    {"q":"Who is the headmaster of Hogwarts in the first Harry Potter books?","a":"Albus Dumbledore","rank":7,"cefr":"B1","alt":["Dumbledore"]},
    {"q":"Which clever girl is Harry's other best friend in Harry Potter?","a":"Hermione Granger","rank":8,"cefr":"B1","alt":["Hermione"]},
    {"q":"What creature guards Hogwarts and takes away people's happiness?","a":"Dementor","rank":9,"cefr":"B1"},
    {"q":"In Harry Potter, which house is known for cunning and ambition?","a":"Slytherin","rank":10,"cefr":"B1"},
    {"q":"What does Voldemort split his soul into in the Harry Potter series?","a":"Horcruxes","rank":11,"cefr":"B2"},
    {"q":"What platform at King's Cross station leads to the Hogwarts Express?","a":"Platform 9¾","rank":12,"cefr":"B2","alt":["Platform 9 3/4"]},
    {"q":"Who is Harry Potter's godfather?","a":"Sirius Black","rank":13,"cefr":"B2"},
    {"q":"In the wizarding world of Harry Potter, what potion lets you become someone else?","a":"Polyjuice Potion","rank":14,"cefr":"B2","alt":["Polyjuice"]},
    {"q":"What is the name of the wandmaker's shop in Diagon Alley?","a":"Ollivanders","rank":15,"cefr":"B2"}
  ],
  "How Many": [
    {"q":"How many months are in a year?","a":"12","rank":1,"cefr":"A1"},
    {"q":"How many legs does a spider have?","a":"8","rank":2,"cefr":"A1"},
    {"q":"How many players are on a basketball team on the court at once?","a":"5","rank":3,"cefr":"A1"},
    {"q":"How many players does a soccer team have on the field?","a":"11","rank":4,"cefr":"A2"},
    {"q":"How many continents are there?","a":"7","rank":5,"cefr":"A2"},
    {"q":"How many strings does a standard guitar have?","a":"6","rank":6,"cefr":"A2"},
    {"q":"How many bones are in the adult human body?","a":"206","rank":7,"cefr":"B1"},
    {"q":"How many time zones does Brazil have?","a":"4","rank":8,"cefr":"B1"},
    {"q":"How many countries border Brazil?","a":"10","rank":9,"cefr":"B1"},
    {"q":"How many days are in the month of February in a leap year?","a":"29","rank":10,"cefr":"B1"},
    {"q":"How many hearts does an octopus have?","a":"3","rank":11,"cefr":"B2"},
    {"q":"How many moons does Mars have?","a":"2","rank":12,"cefr":"B2"},
    {"q":"How many chromosomes does a human have?","a":"46","rank":13,"cefr":"B2"},
    {"q":"How many teeth does an adult human have?","a":"32","rank":14,"cefr":"B2"},
    {"q":"How many innings are in a standard baseball game?","a":"9","rank":15,"cefr":"B2"}
  ],
  "Marvel and DC": [
    {"q":"What is the name of the billionaire superhero also known as Iron Man?","a":"Tony Stark","rank":1,"cefr":"A1"},
    {"q":"What is Superman's home planet?","a":"Krypton","rank":2,"cefr":"A1"},
    {"q":"What is the name of Batman's home city?","a":"Gotham City","rank":3,"cefr":"A1","alt":["Gotham"]},
    {"q":"What is the name of Spider-Man's alter ego?","a":"Peter Parker","rank":4,"cefr":"A2"},
    {"q":"What color is the Hulk?","a":"green","rank":5,"cefr":"A2"},
    {"q":"What is Wonder Woman's home island called?","a":"Themyscira","rank":6,"cefr":"A2"},
    {"q":"What is the name of the team of superheroes led by Captain America and Iron Man?","a":"the Avengers","rank":7,"cefr":"B1","alt":["Avengers"]},
    {"q":"What metal makes up Captain America's shield?","a":"vibranium","rank":8,"cefr":"B1"},
    {"q":"What is the name of the DC team that includes Batman, Superman, and Wonder Woman?","a":"Justice League","rank":9,"cefr":"B1"},
    {"q":"What is Batman's butler and confidant called?","a":"Alfred","rank":10,"cefr":"B1","alt":["Alfred Pennyworth"]},
    {"q":"What nickname is Batman given for his detective skills?","a":"the World's Greatest Detective","rank":11,"cefr":"B2","alt":["World's Greatest Detective"]},
    {"q":"What is the name of the fictional African country Black Panther rules?","a":"Wakanda","rank":12,"cefr":"B2"},
    {"q":"Who is Loki's brother, the god of thunder with a hammer?","a":"Thor","rank":13,"cefr":"B2"},
    {"q":"What toxic element originally powered the arc reactor in Tony Stark's chest?","a":"palladium","rank":14,"cefr":"B2"},
    {"q":"What is the name of the giant purple villain who collects the Infinity Stones?","a":"Thanos","rank":15,"cefr":"B2","alt":["Multiverse Saga"]}
  ],
  "Math": [
    {"q":"What is 2 + 2?","a":"4","rank":1,"cefr":"A1"},
    {"q":"What is 10 - 4?","a":"6","rank":2,"cefr":"A1"},
    {"q":"What is 3 x 3?","a":"9","rank":3,"cefr":"A1"},
    {"q":"What is 12 divided by 4?","a":"3","rank":4,"cefr":"A2"},
    {"q":"How many sides does a pentagon have?","a":"5","rank":5,"cefr":"A2"},
    {"q":"What is 7 x 8?","a":"56","rank":6,"cefr":"A2"},
    {"q":"What is the value of pi, rounded to two decimals?","a":"3.14","rank":7,"cefr":"B1"},
    {"q":"How many degrees are in a right angle?","a":"90","rank":8,"cefr":"B1"},
    {"q":"What is the square root of 64?","a":"8","rank":9,"cefr":"B1"},
    {"q":"How many degrees are in a full circle?","a":"360","rank":10,"cefr":"B1"},
    {"q":"What is the formula for the area of a circle?","a":"πr²","rank":11,"cefr":"B2","alt":["pi times r squared"]},
    {"q":"What is the Pythagorean theorem's formula?","a":"a² + b² = c²","rank":12,"cefr":"B2","alt":["a squared plus b squared equals c squared"]},
    {"q":"What do you call a number that can only be divided evenly by 1 and itself?","a":"prime number","rank":13,"cefr":"B2"},
    {"q":"What is 15% of 200?","a":"30","rank":14,"cefr":"B2"},
    {"q":"What is the sum of the interior angles of a triangle?","a":"180°","rank":15,"cefr":"B2","alt":["180 degrees"]}
  ],
  "Minecraft": [
    {"q":"What block do you get when you punch a tree in Minecraft?","a":"wood","rank":1,"cefr":"A1","alt":["logs","a log"]},
    {"q":"In Minecraft, what green mob explodes when it gets close to you?","a":"Creeper","rank":2,"cefr":"A1"},
    {"q":"What tool do Minecraft players use to mine blocks?","a":"a pickaxe","rank":3,"cefr":"A1","alt":["pickaxe"]},
    {"q":"What metal makes the strongest Minecraft tools before diamond?","a":"iron","rank":4,"cefr":"A2"},
    {"q":"What dimension can you enter through an obsidian portal in Minecraft?","a":"the Nether","rank":5,"cefr":"A2","alt":["Nether"]},
    {"q":"What is the name of the flying boss in Minecraft's End dimension?","a":"Ender Dragon","rank":6,"cefr":"A2"},
    {"q":"Which tall Minecraft mob can teleport and steal blocks?","a":"Enderman","rank":7,"cefr":"B1"},
    {"q":"In Minecraft, what material do you need to build a Nether portal?","a":"obsidian","rank":8,"cefr":"B1"},
    {"q":"What tool do you need to safely mine obsidian in Minecraft?","a":"a diamond pickaxe","rank":9,"cefr":"B1","alt":["diamond pickaxe"]},
    {"q":"Which Minecraft mob attacks at night but burns in sunlight?","a":"Zombie","rank":10,"cefr":"B1","alt":["Skeleton"]},
    {"q":"What blue mineral do you need to enchant items in Minecraft?","a":"lapis lazuli","rank":11,"cefr":"B2","alt":["lapis"]},
    {"q":"What Minecraft block uses experience points to improve your gear?","a":"enchanting table","rank":12,"cefr":"B2","alt":["anvil"]},
    {"q":"What material from the Nether is even stronger than diamond in Minecraft?","a":"netherite","rank":13,"cefr":"B2"},
    {"q":"In Minecraft, what three-headed boss do you build from soul sand and skulls?","a":"the Wither","rank":14,"cefr":"B2","alt":["Wither"]},
    {"q":"What Minecraft item acts like a wire to carry a redstone signal?","a":"redstone dust","rank":15,"cefr":"B2","alt":["redstone wire"]}
  ],
  "Mobile Games": [
    {"q":"In which mobile game do you use a slingshot to hit green pigs?","a":"Angry Birds","rank":1,"cefr":"A1"},
    {"q":"In which mobile game do you swap sweets to make rows of three?","a":"Candy Crush","rank":2,"cefr":"A1","alt":["Candy Crush Saga"]},
    {"q":"What battle royale mobile game has a bus dropping players onto an island?","a":"Fortnite","rank":3,"cefr":"A1","alt":["PUBG Mobile"]},
    {"q":"What mobile game involves catching creatures by walking around real locations?","a":"Pokémon GO","rank":4,"cefr":"A2","alt":["Pokemon Go"]},
    {"q":"What runner mobile game has players dodging trains as a graffiti artist?","a":"Subway Surfers","rank":5,"cefr":"A2"},
    {"q":"In which mobile game do you run from monkeys after stealing a golden idol?","a":"Temple Run","rank":6,"cefr":"A2","alt":["Animal Crossing"]},
    {"q":"What mobile MOBA game features heroes like Layla and Miya?","a":"Mobile Legends: Bang Bang","rank":7,"cefr":"B1","alt":["Mobile Legends"]},
    {"q":"What mobile battle royale is known for its realistic graphics and squads of 4?","a":"PUBG Mobile","rank":8,"cefr":"B1"},
    {"q":"In which mobile game do you swipe to slice flying watermelons and bananas?","a":"Fruit Ninja","rank":9,"cefr":"B1"},
    {"q":"What card-battler mobile game by Supercell features princes and towers?","a":"Clash Royale","rank":10,"cefr":"B1"},
    {"q":"What mobile game by Supercell has players build a village and raid others?","a":"Clash of Clans","rank":11,"cefr":"B2"},
    {"q":"In which mobile game do you tap only the black squares to play a song?","a":"Piano Tiles","rank":12,"cefr":"B2","alt":["Piano Tiles"]},
    {"q":"What Supercell game has heroes called Brawlers, like Shelly and Colt?","a":"Brawl Stars","rank":13,"cefr":"B2","alt":["Last Day on Earth"]},
    {"q":"What mobile game publisher created both Clash of Clans and Clash Royale?","a":"Supercell","rank":14,"cefr":"B2"},
    {"q":"What Supercell farming game has players grow crops and sell them at a roadside shop?","a":"Hay Day","rank":15,"cefr":"B2","alt":["Cooking Fever"]}
  ],
  "Pop Culture": [
    {"q":"What streaming service is known for shows like Stranger Things?","a":"Netflix","rank":1,"cefr":"A1"},
    {"q":"What social media app is known for short dance and lip-sync videos?","a":"TikTok","rank":2,"cefr":"A1"},
    {"q":"What annual award show honors the best in film?","a":"the Oscars","rank":3,"cefr":"A1","alt":["Academy Awards"]},
    {"q":"What music streaming app uses a green logo?","a":"Spotify","rank":4,"cefr":"A2"},
    {"q":"What word describes a video or image that spreads very quickly online?","a":"viral","rank":5,"cefr":"A2"},
    {"q":"What are short vertical videos on Instagram called?","a":"Reels","rank":6,"cefr":"A2","alt":["Instagram Reels"]},
    {"q":"What term describes a celebrity's dedicated fanbase online?","a":"fandom","rank":7,"cefr":"B1","alt":["stan community"]},
    {"q":"What annual music award show is hosted by the Recording Academy?","a":"the Grammys","rank":8,"cefr":"B1","alt":["Grammy Awards"]},
    {"q":"What term describes posting content to intentionally provoke or annoy people online?","a":"trolling","rank":9,"cefr":"B1","alt":["trolling online"]},
    {"q":"What word describes a phrase or image that's copied and spread with variations online?","a":"meme","rank":10,"cefr":"B1"},
    {"q":"What do you call a video diary that a YouTuber makes about their daily life?","a":"a vlog","rank":11,"cefr":"B2","alt":["vlog","video blog"]},
    {"q":"What do you call a person who earns money by posting content on social media?","a":"an influencer","rank":12,"cefr":"B2","alt":["influencer","content creator"]},
    {"q":"What word describes editing photos to look unrealistically perfect?","a":"photoshopping","rank":13,"cefr":"B2","alt":["retouching"]},
    {"q":"Which French city holds a famous film festival every May?","a":"Cannes","rank":14,"cefr":"B2","alt":["Cannes"]},
    {"q":"What term describes content designed to grab attention with exaggerated claims?","a":"clickbait","rank":15,"cefr":"B2"}
  ],
  "Pop Music": [
    {"q":"What pop singer is known for the song 'Shake It Off'?","a":"Taylor Swift","rank":1,"cefr":"A1"},
    {"q":"What Brazilian singer had a global hit with the song 'Envolver'?","a":"Anitta","rank":2,"cefr":"A1"},
    {"q":"What pop star is known as 'Queen Bey'?","a":"Beyoncé","rank":3,"cefr":"A1","alt":["Beyonce"]},
    {"q":"What Canadian singer, who started by posting cover songs on YouTube, is known for the song 'Sorry'?","a":"Justin Bieber","rank":4,"cefr":"A2"},
    {"q":"What Barbadian singer is known for hits like 'Umbrella' and 'Diamonds'?","a":"Rihanna","rank":5,"cefr":"A2"},
    {"q":"What pop singer is known for the song 'Bad Guy'?","a":"Billie Eilish","rank":6,"cefr":"A2"},
    {"q":"What South Korean group, with members like Jisoo and Lisa, is known for global pop hits?","a":"Blackpink","rank":7,"cefr":"B1"},
    {"q":"What do Taylor Swift's fans call themselves?","a":"Swifties","rank":8,"cefr":"B1","alt":["stan community"]},
    {"q":"What Colombian singer is known worldwide for the song 'Hips Don't Lie'?","a":"Shakira","rank":9,"cefr":"B1"},
    {"q":"What music style from Rio's favelas did Anitta take around the world?","a":"funk","rank":10,"cefr":"B1","alt":["funk carioca","Brazilian funk","baile funk"]},
    {"q":"What British singer's album 'Divide' produced hits like 'Shape of You'?","a":"Ed Sheeran","rank":11,"cefr":"B2"},
    {"q":"Which K-pop boy band has seven members, including Jungkook and V?","a":"BTS","rank":12,"cefr":"B2","alt":["Spotify streams"]},
    {"q":"What pop singer collaborated with Anitta on international crossover hits?","a":"Cardi B","rank":13,"cefr":"B2","alt":["Maluma","J Balvin"]},
    {"q":"What term describes a song's official visual accompaniment released alongside it?","a":"music video","rank":14,"cefr":"B2"},
    {"q":"What weekly US chart lists the 100 most popular songs?","a":"Billboard Hot 100","rank":15,"cefr":"B2","alt":["Hot 100","Billboard"]}
  ],
  "Roblox": [
    {"q":"What is the in-game currency in Roblox called?","a":"Robux","rank":1,"cefr":"A1"},
    {"q":"In Roblox, what do players create to show how they look?","a":"an avatar","rank":2,"cefr":"A1","alt":["avatar"]},
    {"q":"What does Roblox call the games that its users make?","a":"experiences","rank":3,"cefr":"A1","alt":["games"]},
    {"q":"What popular Roblox game is about finding a killer in a group of players?","a":"Murder Mystery 2","rank":4,"cefr":"A2","alt":["MM2"]},
    {"q":"What do Roblox players call a game made of obstacle courses?","a":"Obby","rank":5,"cefr":"A2","alt":["obstacle course"]},
    {"q":"What free program do developers use to build Roblox games?","a":"Roblox Studio","rank":6,"cefr":"A2"},
    {"q":"In Roblox, what popular game is about adopting and raising pets?","a":"Adopt Me!","rank":7,"cefr":"B1","alt":["Adopt Me"]},
    {"q":"What programming language do Roblox Studio scripts use?","a":"Lua","rank":8,"cefr":"B1"},
    {"q":"What type of game has Roblox players defend a base from waves of monsters?","a":"tower defense","rank":9,"cefr":"B1","alt":["Tower Defense Simulator"]},
    {"q":"What do players call a Roblox game where you click again and again to grow stronger?","a":"a simulator","rank":10,"cefr":"B1","alt":["simulator","clicker"]},
    {"q":"What Roblox game lets players live a city life, own a house and drive cars?","a":"Brookhaven","rank":11,"cefr":"B2","alt":["Brookhaven RP"]},
    {"q":"In what year was Roblox first released?","a":"2006","rank":12,"cefr":"B2"},
    {"q":"What do you call buying cosmetic items in Roblox with real money?","a":"microtransactions","rank":13,"cefr":"B2","alt":["in-game purchases"]},
    {"q":"What horror game on Roblox has a pig-masked enemy chasing players?","a":"Piggy","rank":14,"cefr":"B2"},
    {"q":"What yearly event brings Roblox players and creators together?","a":"RDC","rank":15,"cefr":"B2","alt":["Roblox Developers Conference"]}
  ],
  "Science": [
    {"q":"What planet do we live on?","a":"Earth","rank":1,"cefr":"A1"},
    {"q":"What gas do humans breathe in to survive?","a":"oxygen","rank":2,"cefr":"A1"},
    {"q":"What force pulls objects toward the Earth?","a":"gravity","rank":3,"cefr":"A1"},
    {"q":"What is the powerhouse of the cell, that produces energy?","a":"mitochondria","rank":4,"cefr":"A2"},
    {"q":"What do plants need, besides water and sunlight, to grow?","a":"carbon dioxide","rank":5,"cefr":"A2","alt":["CO2","soil/nutrients"]},
    {"q":"What is the process by which plants make food from sunlight called?","a":"photosynthesis","rank":6,"cefr":"A2"},
    {"q":"What is the boiling point of water in Celsius?","a":"100°C","rank":7,"cefr":"B1","alt":["100"]},
    {"q":"What planet is known as the Red Planet?","a":"Mars","rank":8,"cefr":"B1"},
    {"q":"What is the largest organ in the human body?","a":"skin","rank":9,"cefr":"B1"},
    {"q":"What do we call the layer of gases surrounding the Earth?","a":"the atmosphere","rank":10,"cefr":"B1","alt":["atmosphere"]},
    {"q":"What is the chemical formula for table salt?","a":"NaCl","rank":11,"cefr":"B2"},
    {"q":"What is the speed of light, approximately?","a":"300,000 km/s","rank":12,"cefr":"B2","alt":["300000 km/s","186000 mi/s"]},
    {"q":"What is the name of the theory that explains how species change over time?","a":"evolution","rank":13,"cefr":"B2","alt":["theory of evolution"]},
    {"q":"What particle in an atom has a negative charge?","a":"electron","rank":14,"cefr":"B2"},
    {"q":"What is the study of the stars and universe called?","a":"astronomy","rank":15,"cefr":"B2"}
  ],
  "Stranger Things": [
    {"q":"In which town does Stranger Things take place?","a":"Hawkins","rank":1,"cefr":"A1"},
    {"q":"What is the name of the girl with psychic powers in Stranger Things?","a":"Eleven","rank":2,"cefr":"A1","alt":["El"]},
    {"q":"What dark alternate dimension do the kids in Stranger Things discover?","a":"the Upside Down","rank":3,"cefr":"A1","alt":["Upside Down"]},
    {"q":"In Stranger Things, which boy disappears in Season 1?","a":"Will Byers","rank":4,"cefr":"A2","alt":["Will"]},
    {"q":"What does Eleven from Stranger Things love to eat?","a":"Eggo waffles","rank":5,"cefr":"A2","alt":["Eggos","waffles"]},
    {"q":"What is the name of the first monster in Stranger Things?","a":"the Demogorgon","rank":6,"cefr":"A2","alt":["Demogorgon"]},
    {"q":"Who is the police chief of Hawkins in Stranger Things?","a":"Jim Hopper","rank":7,"cefr":"B1","alt":["Hopper"]},
    {"q":"What is the name of Will's older brother in Stranger Things?","a":"Jonathan Byers","rank":8,"cefr":"B1","alt":["Jonathan"]},
    {"q":"In Stranger Things, which government facility is connected to the Upside Down?","a":"Hawkins National Laboratory","rank":9,"cefr":"B1","alt":["Hawkins Lab"]},
    {"q":"Who is Mike's older sister on the show Stranger Things?","a":"Nancy Wheeler","rank":10,"cefr":"B1","alt":["Nancy"]},
    {"q":"What number is tattooed on Eleven's wrist in Stranger Things?","a":"011","rank":11,"cefr":"B2"},
    {"q":"What is the name of the shopping mall in Stranger Things Season 3?","a":"Starcourt Mall","rank":12,"cefr":"B2","alt":["Starcourt"]},
    {"q":"Which Stranger Things creature controls the Demogorgons and other monsters?","a":"the Mind Flayer","rank":13,"cefr":"B2","alt":["Mind Flayer"]},
    {"q":"What is the name of Joyce's kind boyfriend in Season 2 of Stranger Things?","a":"Bob Newby","rank":14,"cefr":"B2","alt":["Bob"]},
    {"q":"What Russian prison location matters in Season 4 of Stranger Things?","a":"Kamchatka","rank":15,"cefr":"B2","alt":["a Russian prison"]}
  ],
  "Vegetables": [
    {"q":"What orange vegetable is good for your eyes?","a":"carrot","rank":1,"cefr":"A1"},
    {"q":"What round red vegetable is used in salads and sauces?","a":"tomato","rank":2,"cefr":"A1"},
    {"q":"What green vegetable looks like a small tree?","a":"broccoli","rank":3,"cefr":"A1"},
    {"q":"What white vegetable makes people cry when you cut it?","a":"onion","rank":4,"cefr":"A2"},
    {"q":"What long green vegetable is mostly water and used in salads?","a":"cucumber","rank":5,"cefr":"A2"},
    {"q":"What vegetable is grown underground and is fried to make chips/fries?","a":"potato","rank":6,"cefr":"A2"},
    {"q":"What leafy green vegetable is used in Caesar salads?","a":"lettuce","rank":7,"cefr":"B1"},
    {"q":"What purple vegetable is used in Italian dishes like parmigiana?","a":"eggplant","rank":8,"cefr":"B1","alt":["aubergine"]},
    {"q":"What vegetable, related to cabbage, has small green florets similar to broccoli?","a":"Brussels sprout","rank":9,"cefr":"B1","alt":["Brussels sprouts"]},
    {"q":"What root vegetable is red or purple and used to make borscht soup?","a":"beet","rank":10,"cefr":"B1","alt":["beetroot"]},
    {"q":"What starchy root vegetable, called 'mandioca' in Brazil, is used to make farofa?","a":"cassava","rank":11,"cefr":"B2","alt":["manioc","yuca"]},
    {"q":"What vegetable is technically a fungus, not a plant?","a":"mushroom","rank":12,"cefr":"B2"},
    {"q":"What leafy vegetable is Popeye famous for eating for strength?","a":"spinach","rank":13,"cefr":"B2"},
    {"q":"What vegetable is the main ingredient in traditional Halloween carving?","a":"pumpkin","rank":14,"cefr":"B2"},
    {"q":"What vegetable family includes broccoli, cauliflower, and cabbage?","a":"brassica","rank":15,"cefr":"B2","alt":["cruciferous vegetables"]}
  ],
  "World Capitals": [
    {"q":"Which city on the River Seine is the capital of France?","a":"Paris","rank":1,"cefr":"A1"},
    {"q":"Which capital city of England has red double-decker buses?","a":"London","rank":2,"cefr":"A1"},
    {"q":"In which capital city does the US president live and work?","a":"Washington, D.C.","rank":3,"cefr":"A1","alt":["Washington DC","Washington"]},
    {"q":"Which capital city in Japan is famous for sushi and anime?","a":"Tokyo","rank":4,"cefr":"A2"},
    {"q":"Which Italian capital city surrounds Vatican City?","a":"Rome","rank":5,"cefr":"A2"},
    {"q":"Which capital city was divided by a wall until 1989?","a":"Berlin","rank":6,"cefr":"A2"},
    {"q":"Which Canadian city is the capital, not Toronto or Vancouver?","a":"Ottawa","rank":7,"cefr":"B1"},
    {"q":"Which capital city sits on the River Nile in Egypt?","a":"Cairo","rank":8,"cefr":"B1"},
    {"q":"Which capital city has the Kremlin and Red Square?","a":"Moscow","rank":9,"cefr":"B1"},
    {"q":"Which South American capital city is famous for tango?","a":"Buenos Aires","rank":10,"cefr":"B1"},
    {"q":"Which Asian capital city is the center of K-pop?","a":"Seoul","rank":11,"cefr":"B1"},
    {"q":"What is the capital of Turkey, which many people think is Istanbul?","a":"Ankara","rank":12,"cefr":"B2"},
    {"q":"What is one of the three capital cities of South Africa?","a":"Pretoria","rank":13,"cefr":"B2","alt":["Cape Town","Bloemfontein"]},
    {"q":"Which Swiss city is the capital, not Zurich or Geneva?","a":"Bern","rank":14,"cefr":"B2"},
    {"q":"Which Central Asian capital was renamed Nur-Sultan and later changed back?","a":"Astana","rank":15,"cefr":"B2"}
  ]
};
root.QM_QUESTIONS = questions;
if (typeof module !== "undefined" && module.exports) module.exports = questions;
})(typeof window !== "undefined" ? window : globalThis);
