/**
 * Facts Database — PAIRED
 *
 * Every entry is a TWIN PAIR: a true sentence and a false sentence written to
 * the same length, syntax and register, differing in one detail. The game serves
 * ONE half of a pair at random, so surface features (sentence length, numbers,
 * hedging, absolutes) carry no information about the answer. Only knowing the
 * fact helps.
 *
 * Fields: id, cefr (A2|B1|B2 — READING difficulty), category, t (true half),
 *         f (false half), note (the explanation shown on reveal, either way).
 *
 * 164 pairs = 328 sentences.
 *
 * WHEN ADDING PAIRS: keep the two halves within 3 words and 22 characters of
 * each other, and do not let absolutes or numbers cluster on one side. Run the
 * tell metrics before pushing — every naive rule must sit near 50%.
 */

const factsDatabase = {
  pairs: [

    // ── A2 ──
    { id: "AN-01", cefr: "A2", category: "animals",
      t: "An octopus has three hearts.",
      f: "An octopus has seven hearts.",
      note: "Three. Two pump blood to the gills and one to the rest of the body." },
    { id: "AN-02", cefr: "A2", category: "animals",
      t: "Polar bears have black skin under their white fur.",
      f: "Polar bears have pink skin under their white fur.",
      note: "Black skin, which helps them absorb heat from the sun." },
    { id: "AN-03", cefr: "A2", category: "animals",
      t: "Butterflies can taste with their feet.",
      f: "Butterflies can taste with their wings.",
      note: "With their feet. They stand on a leaf to find out if it is good food." },
    { id: "AN-04", cefr: "A2", category: "animals",
      t: "Koalas sleep for about twenty hours a day.",
      f: "Koalas sleep for about seven hours a day.",
      note: "Around twenty. Their diet of eucalyptus leaves gives them very little energy." },
    { id: "AN-05", cefr: "A2", category: "animals",
      t: "A dolphin is a mammal, not a fish.",
      f: "A dolphin is a fish, not a mammal.",
      note: "A mammal. Dolphins breathe air and feed their babies milk." },
    { id: "AN-06", cefr: "A2", category: "animals",
      t: "Sharks are older than trees.",
      f: "Trees are older than sharks.",
      note: "Sharks. They appeared roughly 100 million years before the first trees." },
    { id: "AN-07", cefr: "A2", category: "food",
      t: "A banana is a berry, but a strawberry is not.",
      f: "A strawberry is a berry, but a banana is not.",
      note: "The banana is. In botany a berry grows from one flower with one ovary." },
    { id: "AN-08", cefr: "A2", category: "animals",
      t: "An elephant cannot jump at all.",
      f: "An elephant can jump about half a metre.",
      note: "It cannot. Its legs and weight make jumping impossible." },
    { id: "AN-09", cefr: "A2", category: "animals",
      t: "A giraffe's neck has seven bones, the same number as yours.",
      f: "A giraffe's neck has seventy bones, ten times more than yours.",
      note: "Seven, like almost every mammal. The bones are just much longer." },
    { id: "AN-10", cefr: "A2", category: "animals",
      t: "A hummingbird can fly backwards.",
      f: "A hummingbird cannot fly backwards.",
      note: "It can. Its wings move in a figure eight, so it can go back or hover." },
    { id: "AN-11", cefr: "A2", category: "food",
      t: "Honey does not go bad, even after many years.",
      f: "Honey goes bad after about two years.",
      note: "It does not. Honey is too dry and too acidic for bacteria to grow in." },
    { id: "AN-12", cefr: "A2", category: "animals",
      t: "The ostrich lays the biggest egg of any bird alive today.",
      f: "The penguin lays the biggest egg of any bird alive today.",
      note: "The ostrich. One egg weighs about the same as two dozen chicken eggs." },
    { id: "AN-13", cefr: "A2", category: "animals",
      t: "The blue whale is the largest animal on Earth.",
      f: "The African elephant is the largest animal on Earth.",
      note: "The blue whale, at up to thirty metres long." },
    { id: "AN-14", cefr: "A2", category: "animals",
      t: "Bats are mammals, and they can fly.",
      f: "Bats are birds, and they can fly.",
      note: "Mammals. They have fur and feed their young with milk." },
    { id: "AN-15", cefr: "A2", category: "animals",
      t: "A frog can breathe through its skin.",
      f: "A frog can breathe through its eyes.",
      note: "Through its skin, which is why frogs must stay wet." },
    { id: "AN-16", cefr: "A2", category: "animals",
      t: "A starfish can grow a new arm if it loses one.",
      f: "A starfish will die if it loses one arm.",
      note: "It grows a new one, though this can take several months." },
    { id: "AN-17", cefr: "A2", category: "animals",
      t: "A camel's hump stores fat, not water.",
      f: "A camel's hump stores water, not fat.",
      note: "Fat. The camel uses it for energy when there is no food." },
    { id: "AN-18", cefr: "A2", category: "animals",
      t: "An owl can turn its head about 270 degrees.",
      f: "An owl can turn its head a full 360 degrees.",
      note: "About 270 degrees — three quarters of a circle, not a full one." },
    { id: "AN-19", cefr: "A2", category: "animals",
      t: "Flamingos get their pink colour from the food they eat.",
      f: "Flamingos are born pink and lose the colour as they grow.",
      note: "From their food. Baby flamingos are grey or white." },
    { id: "AN-20", cefr: "A2", category: "animals",
      t: "An ant can carry many times its own body weight.",
      f: "An ant struggles to carry even its own body weight.",
      note: "Many times — some ants carry fifty times their own weight." },
    { id: "AN-21", cefr: "A2", category: "animals",
      t: "A sloth can take a month to digest one meal.",
      f: "A sloth can digest one meal in about an hour.",
      note: "Weeks, sometimes a month. Its stomach works extremely slowly." },
    { id: "AN-22", cefr: "A2", category: "animals",
      t: "The whale shark is a shark, not a whale.",
      f: "The whale shark is a whale, not a shark.",
      note: "A shark — the biggest fish in the sea." },
    { id: "AN-23", cefr: "A2", category: "animals",
      t: "Cats have more than thirty muscles in each ear.",
      f: "Cats have fewer than five muscles in each ear.",
      note: "About thirty-two, so a cat can turn each ear on its own." },
    { id: "AN-24", cefr: "A2", category: "animals",
      t: "A snail will always sleep in short bursts rather than one long stretch.",
      f: "A snail sleeps in one long stretch of about three years.",
      note: "Snails do sleep, in short periods over about a day." },
    { id: "AN-25", cefr: "A2", category: "animals",
      t: "Penguins live in Antarctica but never in the Arctic.",
      f: "Penguins live in the Arctic but never in Antarctica.",
      note: "Wild penguins live only in the southern half of the world." },
    { id: "AN-26", cefr: "A2", category: "animals",
      t: "A crocodile cannot stick its tongue out of its mouth.",
      f: "A crocodile can stick its tongue out to catch insects.",
      note: "It cannot. The tongue is joined to the bottom of the mouth." },
    { id: "AN-27", cefr: "A2", category: "animals",
      t: "Cows have four parts in their stomach.",
      f: "Cows have four separate stomachs in their body.",
      note: "One stomach with four parts, not four stomachs." },
    { id: "AN-28", cefr: "A2", category: "animals",
      t: "Most spiders have eight eyes.",
      f: "Most spiders have two eyes.",
      note: "Eight is normal for most spiders, though a few kinds have fewer." },
    { id: "AN-29", cefr: "A2", category: "nature",
      t: "Bamboo is a kind of grass, not a tree.",
      f: "Bamboo is a kind of tree, not a grass.",
      note: "A grass — which is why it grows back so fast after cutting." },
    { id: "AN-30", cefr: "A2", category: "nature",
      t: "A tomato is a fruit, not a vegetable.",
      f: "A tomato is a vegetable, not a fruit.",
      note: "A fruit, because it grows from the flower and holds the seeds." },
    { id: "HB-01", cefr: "A2", category: "body",
      t: "An adult has fewer bones than a baby.",
      f: "An adult has more bones than a baby.",
      note: "Fewer. A baby has about 300 bones and some join together as it grows." },
    { id: "HB-02", cefr: "A2", category: "body",
      t: "Your left lung is smaller than your right lung.",
      f: "Your left lung is bigger than your right lung.",
      note: "Smaller, to leave space for the heart." },
    { id: "HB-03", cefr: "A2", category: "body",
      t: "The smallest bone in your body is in your ear.",
      f: "The smallest bone in your body is in your nose.",
      note: "In the ear. It is about three millimetres long." },
    { id: "HB-04", cefr: "A2", category: "body",
      t: "Your brain uses about a fifth of your body's energy.",
      f: "Your brain uses about a fiftieth of your body's energy.",
      note: "Around twenty per cent, even though it is only two per cent of your weight." },
    { id: "HB-05", cefr: "A2", category: "body",
      t: "You cannot easily lick your own elbow.",
      f: "You cannot easily close your eyes when you sneeze.",
      note: "The elbow one is true. Almost everyone closes their eyes when sneezing." },
    { id: "HB-06", cefr: "A2", category: "body",
      t: "Your fingernails grow faster than your toenails.",
      f: "Your toenails grow faster than your fingernails.",
      note: "Fingernails, about three times faster." },
    { id: "HB-07", cefr: "A2", category: "body",
      t: "Your body has more bacteria cells than human cells.",
      f: "Your body has more human cells than bacteria cells.",
      note: "Bacteria are slightly ahead, mostly living in your gut." },
    { id: "HB-08", cefr: "A2", category: "body",
      t: "Everyone has a different tongue print, as well as fingerprints.",
      f: "Everyone in a family shares a tongue print, unlike fingerprints.",
      note: "Tongue prints are different for everyone, like fingerprints." },
    { id: "HB-09", cefr: "A2", category: "body",
      t: "Your ears and nose keep growing all your life.",
      f: "Your ears and nose stop growing when you are ten.",
      note: "They keep changing, mostly because the soft tissue drops with age." },
    { id: "HB-10", cefr: "A2", category: "body",
      t: "Your heart beats about 100,000 times a day.",
      f: "Your heart beats about 10,000 times a day.",
      note: "Around 100,000 — roughly seventy times a minute." },
    { id: "SP-01", cefr: "A2", category: "space",
      t: "A day on Venus is longer than a year on Venus.",
      f: "A year on Venus is longer than a day on Venus.",
      note: "The day is longer. Venus turns very slowly on its axis." },
    { id: "SP-02", cefr: "A2", category: "space",
      t: "Venus is the hottest planet in the solar system.",
      f: "Mercury is the hottest planet in the solar system.",
      note: "Venus, because its thick clouds trap the heat." },
    { id: "SP-03", cefr: "A2", category: "space",
      t: "The Moon is slowly moving away from the Earth.",
      f: "The Moon is slowly moving closer to the Earth.",
      note: "Away, at about four centimetres a year." },
    { id: "SP-04", cefr: "A2", category: "space",
      t: "Mars has two moons.",
      f: "Mars has twelve moons.",
      note: "Two, called Phobos and Deimos." },
    { id: "SP-05", cefr: "A2", category: "space",
      t: "There is no wind on the Moon.",
      f: "There is light wind on the Moon at night.",
      note: "None, because the Moon has almost no atmosphere." },
    { id: "SP-06", cefr: "A2", category: "space",
      t: "Light from the Sun takes about eight minutes to reach us.",
      f: "Light from the Sun takes about eight seconds to reach us.",
      note: "About eight minutes and twenty seconds." },
    { id: "SP-07", cefr: "A2", category: "space",
      t: "Jupiter is the biggest planet in the solar system.",
      f: "Saturn is the biggest planet in the solar system.",
      note: "Jupiter. All the other planets would fit inside it." },
    { id: "SP-08", cefr: "A2", category: "space",
      t: "Astronauts get slightly taller in space.",
      f: "Astronauts get slightly shorter in space.",
      note: "Taller, by a few centimetres, because gravity stops pressing on the spine." },
    { id: "GE-01", cefr: "A2", category: "geography",
      t: "Russia is bigger than Pluto.",
      f: "Pluto is bigger than Russia.",
      note: "Russia has the larger surface area of the two." },
    { id: "GE-02", cefr: "A2", category: "geography",
      t: "Africa is bigger than South America.",
      f: "South America is bigger than Africa.",
      note: "Africa is roughly twice the size." },
    { id: "GE-03", cefr: "A2", category: "geography",
      t: "Antarctica is a desert.",
      f: "Antarctica is a rainforest under the ice.",
      note: "A desert. Very little rain or snow falls there each year." },
    { id: "GE-04", cefr: "A2", category: "geography",
      t: "Greenland is much smaller than Africa.",
      f: "Greenland is about the same size as Africa.",
      note: "Much smaller. Flat maps make Greenland look far bigger than it is." },
    { id: "GE-05", cefr: "A2", category: "geography",
      t: "The Pacific is the largest ocean in the world.",
      f: "The Atlantic is the largest ocean in the world.",
      note: "The Pacific, by a long way." },
    { id: "GE-06", cefr: "A2", category: "geography",
      t: "Australia is wider than the Moon.",
      f: "The Moon is wider than Australia.",
      note: "Australia is about 4,000 km wide; the Moon is about 3,500 km." },
    { id: "GE-07", cefr: "A2", category: "geography",
      t: "Canada has more lakes than the rest of the world together.",
      f: "Canada has fewer lakes than any other large country.",
      note: "Canada holds more lakes than all other countries combined." },
    { id: "GE-08", cefr: "A2", category: "geography",
      t: "Mount Everest is still getting taller every year.",
      f: "Mount Everest is getting shorter every year.",
      note: "Taller, by a few millimetres, as the plates below push up." },
    { id: "BR-01", cefr: "A2", category: "brazil",
      t: "Brazil is the largest country in South America.",
      f: "Argentina is the largest country in South America.",
      note: "Brazil, covering almost half the continent." },
    { id: "BR-02", cefr: "A2", category: "brazil",
      t: "Brasília became the capital of Brazil in 1960.",
      f: "Brasília became the capital of Brazil in 1900.",
      note: "1960. Rio de Janeiro was the capital before that." },
    { id: "BR-03", cefr: "A2", category: "brazil",
      t: "Portuguese is the official language of Brazil.",
      f: "Spanish is the official language of Brazil.",
      note: "Portuguese, the only country in South America where it is official." },
    { id: "BR-04", cefr: "A2", category: "brazil",
      t: "São Paulo has more people than Rio de Janeiro.",
      f: "Rio de Janeiro has more people than São Paulo.",
      note: "São Paulo is the largest city in the country." },
    { id: "BR-05", cefr: "A2", category: "brazil",
      t: "Brazil has won the men's football World Cup five times.",
      f: "Brazil has won the men's football World Cup nine times.",
      note: "Five, more than any other country." },
    { id: "BR-06", cefr: "A2", category: "brazil",
      t: "The Amazon River flows into the Atlantic Ocean.",
      f: "The Amazon River flows into the Pacific Ocean.",
      note: "The Atlantic, on the north-east coast of Brazil." },
    { id: "BR-07", cefr: "A2", category: "brazil",
      t: "Curitiba is the capital of the state of Paraná.",
      f: "Londrina is the capital of the state of Paraná.",
      note: "Curitiba, in the south of Brazil." },
    { id: "BR-08", cefr: "A2", category: "brazil",
      t: "Brazil shares a border with ten other countries.",
      f: "Brazil shares a border with three other countries.",
      note: "Ten, if you count French Guiana, which is part of France." },
    { id: "EV-01", cefr: "A2", category: "everyday",
      t: "Hot water can sometimes freeze faster than cold water.",
      f: "Hot water takes longer to freeze than cold water in every case.",
      note: "It sometimes can. Scientists still argue about exactly why." },
    { id: "EV-02", cefr: "A2", category: "everyday",
      t: "The colour orange was named after the fruit.",
      f: "The fruit orange was named after the colour.",
      note: "The fruit came first; English used other words for the colour before." },
    { id: "EV-03", cefr: "A2", category: "everyday",
      t: "A pencil can write in space.",
      f: "A pencil cannot write in space.",
      note: "Pencils work fine. It is normal pens that struggle without gravity." },
    { id: "EV-04", cefr: "A2", category: "everyday",
      t: "Glass is made mainly from sand.",
      f: "Glass is made mainly from salt.",
      note: "Sand, heated to a very high temperature." },
    { id: "EV-05", cefr: "A2", category: "everyday",
      t: "Chocolate is dangerous for dogs.",
      f: "Chocolate is dangerous for cows.",
      note: "For dogs. They cannot break down one of the chemicals in it." },
    { id: "EV-06", cefr: "A2", category: "everyday",
      t: "Carrots were once mostly purple, not orange.",
      f: "Carrots were once mostly blue, not orange.",
      note: "Purple and yellow carrots came first; orange ones are more recent." },
    { id: "EV-07", cefr: "A2", category: "everyday",
      t: "Peanuts do not grow on trees.",
      f: "Peanuts grow at the top of small trees.",
      note: "They grow underground. They are not really nuts at all." },
    { id: "EV-08", cefr: "A2", category: "everyday",
      t: "Water boils at a lower temperature high up a mountain.",
      f: "Water boils at a higher temperature high up a mountain.",
      note: "Lower, because the air pressure is weaker there." },

    // ── B1 ──
    { id: "HI-01", cefr: "B1", category: "history",
      t: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
      f: "Cleopatra lived closer in time to the building of the Great Pyramid than to the Moon landing.",
      note: "Closer to the Moon landing. The pyramid was already 2,500 years old in her lifetime." },
    { id: "HI-02", cefr: "B1", category: "history",
      t: "Oxford University is older than the Aztec Empire.",
      f: "The Aztec Empire is older than Oxford University.",
      note: "Oxford was teaching by 1096; the Aztec capital was founded in 1325." },
    { id: "HI-03", cefr: "B1", category: "history",
      t: "Vikings did not wear helmets with horns on them.",
      f: "Vikings wore helmets with horns on them in battle.",
      note: "No horned helmet has ever been found in a Viking grave." },
    { id: "HI-04", cefr: "B1", category: "history",
      t: "The Hundred Years' War lasted more than a hundred years.",
      f: "The Hundred Years' War lasted rather less than a hundred years.",
      note: "It ran from 1337 to 1453, so about 116 years." },
    { id: "HI-05", cefr: "B1", category: "history",
      t: "The Great Fire of London happened before the first English newspaper.",
      f: "The Great Fire of London happened after the first English newspaper.",
      note: "Printed news sheets appeared in England decades before the 1666 fire." },
    { id: "HI-06", cefr: "B1", category: "history",
      t: "The first modern Olympic Games were held in Athens in 1896.",
      f: "The first modern Olympic Games were held in Paris in 1896.",
      note: "Athens. Paris hosted the second games four years later." },
    { id: "HI-07", cefr: "B1", category: "history",
      t: "Ancient Roman concrete could set underwater.",
      f: "Ancient Roman concrete fell apart if it touched water.",
      note: "Volcanic ash in the mix let it harden in seawater, and it is still standing." },
    { id: "HI-08", cefr: "B1", category: "history",
      t: "The Eiffel Tower was built as a temporary structure.",
      f: "The Eiffel Tower was built as a permanent monument.",
      note: "It was meant to come down after twenty years, but proved useful as a radio mast." },
    { id: "HI-09", cefr: "B1", category: "history",
      t: "Napoleon was about average height for a Frenchman of his time.",
      f: "Napoleon was unusually short for a Frenchman of his time.",
      note: "He was around 1.68 m, which was normal then. The joke came from British cartoons." },
    { id: "HI-10", cefr: "B1", category: "history",
      t: "The Berlin Wall came down in 1989.",
      f: "The Berlin Wall came down in 1979.",
      note: "November 1989, after standing for twenty-eight years." },
    { id: "HI-11", cefr: "B1", category: "history",
      t: "Ancient Egyptians had no toothbrush but did clean their teeth with powder.",
      f: "Ancient Egyptians had no interest at all in cleaning their teeth.",
      note: "They mixed powders from salt, mint and other ingredients to clean their teeth." },
    { id: "HI-12", cefr: "B1", category: "history",
      t: "The printing press reached Europe after it was already used in Asia.",
      f: "The printing press reached Asia after it was already used in Europe.",
      note: "Printing with movable type began in China and Korea centuries earlier." },
    { id: "SC-01", cefr: "B1", category: "science",
      t: "Lightning can strike the same place many times.",
      f: "Lightning cannot strike the same place twice.",
      note: "Tall buildings are hit again and again. Some are struck dozens of times a year." },
    { id: "SC-02", cefr: "B1", category: "science",
      t: "Hot air rises because it is less dense than cold air.",
      f: "Hot air sinks because it is less dense than cold air.",
      note: "It rises. Less dense air floats upward through denser air around it." },
    { id: "SC-03", cefr: "B1", category: "science",
      t: "Sound travels faster through water than through air.",
      f: "Sound travels faster through air than through water.",
      note: "About four times faster in water, because the molecules are closer together." },
    { id: "SC-04", cefr: "B1", category: "science",
      t: "Glass is a solid, even though old window panes are often uneven.",
      f: "Glass is a liquid, which is why old window panes are often uneven.",
      note: "Glass is a solid. Old windows are uneven because of how they were made." },
    { id: "SC-05", cefr: "B1", category: "science",
      t: "Metal feels colder than wood because it moves heat away faster.",
      f: "Metal feels colder than wood because it is at a lower temperature.",
      note: "Both are the same temperature in the same room; metal just pulls heat from your hand." },
    { id: "SC-06", cefr: "B1", category: "science",
      t: "Pure water is a poor conductor of electricity.",
      f: "Pure water is an excellent conductor of electricity.",
      note: "It is the salts and minerals dissolved in ordinary water that carry the current." },
    { id: "SC-07", cefr: "B1", category: "science",
      t: "Diamond and pencil lead are both made of nothing but carbon.",
      f: "Diamond and pencil lead are made of two different elements.",
      note: "Both are pure carbon. Only the arrangement of the atoms is different." },
    { id: "SC-08", cefr: "B1", category: "science",
      t: "Ice floats because water expands when it freezes.",
      f: "Ice floats because water shrinks when it freezes.",
      note: "It expands by about nine per cent, which makes the ice less dense." },
    { id: "SC-09", cefr: "B1", category: "science",
      t: "A rainbow is really a full circle, but the ground hides part of it.",
      f: "A rainbow is really a half circle, and the ground hides nothing.",
      note: "From an aeroplane you can sometimes see the whole circle." },
    { id: "SC-10", cefr: "B1", category: "science",
      t: "Bees can see ultraviolet light that humans cannot see.",
      f: "Bees see fewer colours than humans and cannot see ultraviolet light.",
      note: "Many flowers have ultraviolet patterns that guide bees to the nectar." },
    { id: "SC-11", cefr: "B1", category: "science",
      t: "The Earth is slightly wider at the equator than from pole to pole.",
      f: "The Earth is slightly wider from pole to pole than at the equator.",
      note: "Spinning makes it bulge at the middle by about forty kilometres." },
    { id: "SC-12", cefr: "B1", category: "science",
      t: "Helium was discovered on the Sun before it was found on Earth.",
      f: "Helium was discovered on Earth before it was found on the Sun.",
      note: "It was spotted in sunlight in 1868, and named after the Greek word for sun." },
    { id: "TE-01", cefr: "B1", category: "technology",
      t: "Email was in use before the World Wide Web existed.",
      f: "The World Wide Web was in use before email existed.",
      note: "Email dates from the early 1970s; the Web came about twenty years later." },
    { id: "TE-02", cefr: "B1", category: "technology",
      t: "The first computer programmer is generally said to be a woman.",
      f: "The first computer programmer is generally said to be a man.",
      note: "Ada Lovelace wrote an algorithm for a machine in the 1840s." },
    { id: "TE-03", cefr: "B1", category: "technology",
      t: "Wi-Fi is a brand name that does not stand for anything.",
      f: "Wi-Fi is short for the technical term Wireless Fidelity.",
      note: "A marketing agency invented the name because it sounded good." },
    { id: "TE-04", cefr: "B1", category: "technology",
      t: "Nintendo was founded before the invention of the aeroplane.",
      f: "Nintendo was founded after the invention of the television.",
      note: "Nintendo started in 1889, making playing cards." },
    { id: "TE-05", cefr: "B1", category: "technology",
      t: "The first message sent on the internet crashed the system.",
      f: "The first message sent on the internet arrived without any problem.",
      note: "They tried to type LOGIN, and the system failed after the first two letters." },
    { id: "TE-06", cefr: "B1", category: "technology",
      t: "A modern smartphone is far more powerful than the Apollo computers.",
      f: "A modern smartphone is far less powerful than the Apollo computers.",
      note: "The gap is enormous — millions of times more memory and speed." },
    { id: "TE-07", cefr: "B1", category: "technology",
      t: "The at sign was used in business long before email.",
      f: "The at sign was invented specially for the first email system.",
      note: "Merchants used it for prices centuries before computers existed." },
    { id: "TE-08", cefr: "B1", category: "technology",
      t: "Bluetooth is named after a medieval Scandinavian king.",
      f: "Bluetooth is named after the colour of the first prototype device.",
      note: "After Harald Bluetooth, who united parts of Denmark and Norway." },
    { id: "LA-01", cefr: "B1", category: "language",
      t: "English has taken in thousands of words from French over the centuries.",
      f: "English has taken in barely a handful of words from French over the centuries.",
      note: "After 1066 French was the language of the English court for centuries." },
    { id: "LA-02", cefr: "B1", category: "language",
      t: "Mandarin Chinese has more native speakers than English.",
      f: "English has more native speakers than Mandarin Chinese.",
      note: "Mandarin leads on native speakers; English leads on total speakers." },
    { id: "LA-03", cefr: "B1", category: "language",
      t: "The word robot comes from a Czech play.",
      f: "The word robot comes from a Japanese novel.",
      note: "Karel Čapek used it in a 1920 play, from a Czech word for forced labour." },
    { id: "LA-04", cefr: "B1", category: "language",
      t: "Shakespeare gave English the first written record of hundreds of words.",
      f: "Shakespeare gave English the first written record of three or four words.",
      note: "His plays give the first known written use of a great many words." },
    { id: "LA-05", cefr: "B1", category: "language",
      t: "Portuguese and Spanish both developed from Latin.",
      f: "Portuguese developed from Spanish some centuries ago.",
      note: "They are sister languages, both descended from spoken Latin." },
    { id: "LA-06", cefr: "B1", category: "language",
      t: "The letter W was originally written as two letter Us.",
      f: "The letter W was originally written as two letter Vs.",
      note: "The name double-u survives from the original double U shape." },
    { id: "LA-07", cefr: "B1", category: "language",
      t: "Sign languages have their own grammar, different from spoken languages.",
      f: "Sign languages simply spell out the grammar of the spoken language.",
      note: "They are full languages with rules of their own." },
    { id: "LA-08", cefr: "B1", category: "language",
      t: "There is no single word for a person in Japanese that changes for gender.",
      f: "Every noun in Japanese changes its ending for gender, as in Portuguese.",
      note: "Japanese nouns do not carry grammatical gender at all." },
    { id: "SO-01", cefr: "B1", category: "sport",
      t: "A football match is ninety minutes plus added time.",
      f: "A football match is eighty minutes plus added time.",
      note: "Two halves of forty-five minutes, plus whatever the referee adds." },
    { id: "SO-02", cefr: "B1", category: "sport",
      t: "Basketball was invented using two peach baskets.",
      f: "Basketball was invented using two metal rings.",
      note: "James Naismith nailed peach baskets to a balcony in 1891." },
    { id: "SO-03", cefr: "B1", category: "sport",
      t: "Olympic gold medals are mostly made of silver.",
      f: "Olympic gold medals are mostly made of gold.",
      note: "They are silver with a thin gold coating." },
    { id: "SO-04", cefr: "B1", category: "sport",
      t: "The marathon distance was fixed in the twentieth century.",
      f: "The marathon distance was fixed in ancient Greece.",
      note: "The modern 42.195 km distance was settled at the 1908 London games." },
    { id: "SO-05", cefr: "B1", category: "sport",
      t: "A tennis ball must be yellow or white in professional matches.",
      f: "A tennis ball may be any colour in professional matches.",
      note: "The rules allow only those two colours." },
    { id: "SO-06", cefr: "B1", category: "sport",
      t: "Formula One cars can drive upside down at high speed, in theory.",
      f: "Formula One cars would fall immediately if driven upside down.",
      note: "At speed they generate more downforce than their own weight." },
    { id: "CU-01", cefr: "B1", category: "culture",
      t: "The Mona Lisa is smaller than most people expect.",
      f: "The Mona Lisa is larger than most people expect.",
      note: "It is about 77 by 53 centimetres — roughly the size of a poster." },
    { id: "CU-02", cefr: "B1", category: "culture",
      t: "Beethoven kept composing after he lost his hearing.",
      f: "Beethoven stopped composing as soon as he lost his hearing.",
      note: "Some of his best-known works came after he had gone deaf." },
    { id: "CU-03", cefr: "B1", category: "culture",
      t: "The Statue of Liberty was a gift from France to the United States.",
      f: "The Statue of Liberty was a gift from the United States to France.",
      note: "France gave it in 1886 to mark a century of American independence." },
    { id: "CU-04", cefr: "B1", category: "culture",
      t: "Van Gogh sold very few paintings during his lifetime.",
      f: "Van Gogh sold hundreds of paintings during his lifetime.",
      note: "He was almost unknown as an artist while he was alive." },
    { id: "CU-05", cefr: "B1", category: "culture",
      t: "Carnival in Brazil takes place before Lent.",
      f: "Carnival in Brazil takes place just after Lent.",
      note: "It is the celebration in the days leading up to Ash Wednesday." },
    { id: "CU-06", cefr: "B1", category: "culture",
      t: "The saxophone is named after the man who invented it.",
      f: "The saxophone is named after the city where it was invented.",
      note: "Adolphe Sax patented it in the 1840s." },

    // ── B2 ──
    { id: "XB-01", cefr: "B2", category: "science",
      t: "Ocean plankton generate roughly half of the oxygen in the atmosphere.",
      f: "Ocean plankton generate roughly five per cent of the oxygen in the atmosphere.",
      note: "Marine organisms produce about half of it, rivalling all land plants combined." },
    { id: "XB-02", cefr: "B2", category: "science",
      t: "A teaspoon of a neutron star would weigh billions of tonnes.",
      f: "A teaspoon of a neutron star would weigh only a few grams.",
      note: "Its matter is compressed until the atoms themselves collapse." },
    { id: "XB-03", cefr: "B2", category: "science",
      t: "Absolute zero is a temperature that cannot be reached in practice.",
      f: "Absolute zero is a temperature reached routinely in modern laboratories.",
      note: "Laboratories get extraordinarily close, but the last fraction is unreachable." },
    { id: "XB-04", cefr: "B2", category: "science",
      t: "Most of the mass of an atom sits in its nucleus.",
      f: "Most of the mass of an atom sits in its surrounding electrons.",
      note: "The nucleus holds almost all the mass in a tiny fraction of the volume." },
    { id: "XB-05", cefr: "B2", category: "science",
      t: "Antibiotics have no effect on viral infections such as the common cold.",
      f: "Antibiotics work equally well on viral infections such as the common cold.",
      note: "They target bacteria. Taking them for a virus only encourages resistance." },
    { id: "XB-06", cefr: "B2", category: "science",
      t: "Evolution acts on populations rather than on individual organisms.",
      f: "Evolution acts on individual organisms rather than on whole populations.",
      note: "An individual cannot evolve; the mix of traits in a population shifts over generations." },
    { id: "XB-07", cefr: "B2", category: "science",
      t: "The greenhouse effect is a natural process that life on Earth depends on.",
      f: "The greenhouse effect is a modern process that industry created from nothing.",
      note: "Without it the planet would be frozen. The concern is that it is intensifying." },
    { id: "XB-08", cefr: "B2", category: "science",
      t: "A nuclear power station cannot explode in the way a nuclear weapon does.",
      f: "A nuclear power station can explode in the way a nuclear weapon does.",
      note: "The fuel is nowhere near concentrated enough. Reactor accidents are chemical or steam explosions." },
    { id: "XB-09", cefr: "B2", category: "science",
      t: "Vaccines work by training the immune system to recognise a threat in advance.",
      f: "Vaccines work by killing an infection directly once it has taken hold.",
      note: "They present a harmless version of the threat so the body is ready." },
    { id: "XB-10", cefr: "B2", category: "science",
      t: "Most of the visible universe is moving away from us.",
      f: "Most of the visible universe is moving steadily towards us.",
      note: "Space itself is expanding, so distant galaxies recede in every direction." },
    { id: "XG-01", cefr: "B2", category: "geography",
      t: "The Dead Sea is not actually a sea but a landlocked lake.",
      f: "The Dead Sea is a narrow arm of the Mediterranean Sea.",
      note: "It has no outlet, which is why the salt concentrates." },
    { id: "XG-02", cefr: "B2", category: "geography",
      t: "The Sahara was covered in lakes and grassland within the last ten thousand years.",
      f: "The Sahara has been continuously dry for the last ten million years.",
      note: "Rock paintings there show people swimming and herding cattle." },
    { id: "XG-03", cefr: "B2", category: "geography",
      t: "Iceland is geologically younger than almost all of the surrounding seabed.",
      f: "Iceland is geologically older than almost all of the surrounding seabed.",
      note: "It sits on a mid-ocean ridge where new crust is constantly formed." },
    { id: "XG-04", cefr: "B2", category: "geography",
      t: "Rivers can flow northwards just as easily as in any other direction.",
      f: "Rivers must ultimately flow southwards because of the Earth's rotation.",
      note: "Water follows gravity downhill. The Nile is a famous northward example." },
    { id: "XG-05", cefr: "B2", category: "geography",
      t: "Time zones were introduced largely because of the railways.",
      f: "Time zones were introduced largely because of international shipping.",
      note: "Railway timetables became impossible when every town kept its own clock." },
    { id: "XH-01", cefr: "B2", category: "history",
      t: "The Rosetta Stone was decisive because it carried the same text in several scripts.",
      f: "The Rosetta Stone was decisive because it carried a dictionary of Egyptian words.",
      note: "The parallel Greek text allowed scholars to work out the hieroglyphs." },
    { id: "XH-02", cefr: "B2", category: "history",
      t: "The Black Death killed a substantial share of Europe's population.",
      f: "The Black Death killed a very small share of Europe's population.",
      note: "Estimates commonly run from a third to a half of the population." },
    { id: "XH-03", cefr: "B2", category: "history",
      t: "Brazil gained independence from Portugal without a large-scale war.",
      f: "Brazil gained independence from Portugal after a decade of full-scale war.",
      note: "There was scattered fighting, but nothing on the scale of Spanish America's wars." },
    { id: "XH-04", cefr: "B2", category: "history",
      t: "The Industrial Revolution began in Britain before spreading elsewhere.",
      f: "The Industrial Revolution began in Germany before spreading elsewhere.",
      note: "Britain led with textiles, coal and steam from the late eighteenth century." },
    { id: "XH-05", cefr: "B2", category: "history",
      t: "Written language appears to have developed independently in more than one region.",
      f: "Written language appears to have been invented once and copied everywhere else.",
      note: "Mesopotamia, China and Mesoamerica each seem to have developed writing separately." },
    { id: "XH-06", cefr: "B2", category: "history",
      t: "Medieval Europeans of the educated class knew the Earth was round.",
      f: "Medieval Europeans of the educated class believed the Earth was flat.",
      note: "The spherical Earth was standard knowledge from the ancient Greeks onwards." },
    { id: "XH-07", cefr: "B2", category: "history",
      t: "Portugal and Spain divided the unexplored world between them by treaty in 1494.",
      f: "Portugal and Spain divided the unexplored world between them by treaty in 1694.",
      note: "The Treaty of Tordesillas, which is why Brazil ended up Portuguese." },
    { id: "XE-01", cefr: "B2", category: "economics",
      t: "Inflation means money buys less than it did before.",
      f: "Inflation means money buys more than it did before.",
      note: "Prices rise, so the purchasing power of each unit of currency falls." },
    { id: "XE-02", cefr: "B2", category: "economics",
      t: "A country's population and its economic output are not the same measure.",
      f: "A country's population and its economic output are essentially the same measure.",
      note: "Small countries can produce far more than much larger ones." },
    { id: "XE-03", cefr: "B2", category: "economics",
      t: "Brazil is one of the world's largest exporters of agricultural products.",
      f: "Brazil is one of the world's largest importers of agricultural products.",
      note: "Soy, beef, coffee and sugar are major Brazilian exports." },
    { id: "XE-04", cefr: "B2", category: "economics",
      t: "Paper money began as a promise to pay rather than as something valuable itself.",
      f: "Paper money began as something valuable in itself rather than as a promise.",
      note: "Early notes were claims on deposited metal held by a bank or state." },
    { id: "XL-01", cefr: "B2", category: "language",
      t: "No language has been shown to be inherently more primitive than another.",
      f: "Linguists have shown that some languages are inherently more primitive than others.",
      note: "Every documented language handles the full range of what its speakers need to say." },
    { id: "XL-02", cefr: "B2", category: "language",
      t: "Dictionaries generally record how a language is used rather than dictating it.",
      f: "Dictionaries generally dictate how a language must be used rather than recording it.",
      note: "Modern lexicography is descriptive; new usages get added as they spread." },
    { id: "XL-03", cefr: "B2", category: "language",
      t: "Children acquire the grammar of their first language without formal instruction.",
      f: "Children require formal instruction to acquire the grammar of their first language.",
      note: "Grammar emerges from exposure long before any schooling begins." },
    { id: "XL-04", cefr: "B2", category: "language",
      t: "Speaking more than one language does not delay a child's language development.",
      f: "Speaking more than one language reliably delays a child's language development.",
      note: "Bilingual children reach the usual milestones within the normal range." },
    { id: "XP-01", cefr: "B2", category: "psychology",
      t: "Eyewitness memory is far less reliable than most people assume.",
      f: "Eyewitness memory is far more reliable than most people assume.",
      note: "Memory reconstructs rather than replays, and confidence is a poor guide to accuracy." },
    { id: "XP-02", cefr: "B2", category: "psychology",
      t: "Doing two demanding tasks at once usually makes both of them worse.",
      f: "Doing two demanding tasks at once usually makes both of them faster.",
      note: "Attention switches rather than divides, and each switch costs time." },
    { id: "XP-03", cefr: "B2", category: "psychology",
      t: "There is little evidence that people learn better in their preferred learning style.",
      f: "There is strong evidence that people learn better in their preferred learning style.",
      note: "Studies matching teaching to a stated style have not shown the expected benefit." },
    { id: "XP-04", cefr: "B2", category: "psychology",
      t: "Sleep plays an active role in fixing new memories in the brain.",
      f: "Sleep plays a passive role and never affects how memories are fixed.",
      note: "Consolidation happens during sleep, which is why studying all night backfires." },
    { id: "XA-01", cefr: "B2", category: "biology",
      t: "One species of jellyfish can always return to an earlier stage of its life.",
      f: "Every species of jellyfish ages in one direction and cannot go back.",
      note: "One small jellyfish can return to its polyp stage, effectively resetting." },
    { id: "XA-02", cefr: "B2", category: "biology",
      t: "Fungi are more closely related to animals than they are to plants.",
      f: "Fungi are more closely related to plants than they are to animals.",
      note: "They share a more recent common ancestor with animals." },
    { id: "XA-03", cefr: "B2", category: "biology",
      t: "Trees can exchange nutrients through fungal networks in the soil.",
      f: "Trees are sealed off from one another once their roots stop touching.",
      note: "Fungal threads connect root systems and move carbon and nutrients between trees." },
    { id: "XA-04", cefr: "B2", category: "biology",
      t: "Bacteria in your gut affect processes well beyond digestion.",
      f: "Bacteria in your gut affect nothing beyond digestion itself.",
      note: "Gut microbes are linked to immune function and even mood." },
    { id: "XA-05", cefr: "B2", category: "biology",
      t: "Identical twins do not have identical fingerprints.",
      f: "Identical twins have exactly identical fingerprints.",
      note: "Fingerprints form partly at random in the womb, so they differ." },
    { id: "XA-06", cefr: "B2", category: "biology",
      t: "Only a small share of human DNA codes directly for proteins.",
      f: "Nearly every part of human DNA codes directly for proteins.",
      note: "Protein-coding sequences make up only a small percentage of the genome." },
  ]
};

factsDatabase.CEFR_LEVELS = ['A2', 'B1', 'B2'];

// Serve one half of a pair as a playable item.
factsDatabase.buildItem = function (pair, isTrue) {
  return {
    id: pair.id,
    fact: isTrue ? pair.t : pair.f,
    isTrue: isTrue,
    note: pair.note,
    cefr: pair.cefr,
    category: pair.category
  };
};

// Pairs at or below a maximum reading level. Pass null for every level.
factsDatabase.getByLevel = function (maxLevel) {
  if (!maxLevel) return factsDatabase.pairs.slice();
  var order = factsDatabase.CEFR_LEVELS;
  var cap = order.indexOf(maxLevel);
  if (cap < 0) return factsDatabase.pairs.slice();
  return factsDatabase.pairs.filter(function (p) {
    return order.indexOf(p.cefr) <= cap;
  });
};

factsDatabase.countByLevel = function (maxLevel) {
  return factsDatabase.getByLevel(maxLevel).length;
};

// Back-compatible flat views (both halves of every pair).
factsDatabase.trueFacts = factsDatabase.pairs.map(function (p) {
  return { id: p.id, fact: p.t, category: p.category, cefr: p.cefr, note: p.note };
});
factsDatabase.falseFacts = factsDatabase.pairs.map(function (p) {
  return { id: p.id, fact: p.f, category: p.category, cefr: p.cefr, truth: p.note };
});
