/* Shared question bank: 36 categories x 15 questions, ranked 1-15 (easiest first) and CEFR-tagged.
   Used by Jeopardy (jeopardy/jeopardy.html). Question Mark keeps its own adapted copy in question-mark/questions.js.
   Item: {q, a, rank, cefr, alt?}. groups: library tab per category. Validate: node shared/validate-jeopardy-bank.js */
(function (root) {
var groups = {
  "Animals": "World",
  "Brazilian Capitals": "Brazil",
  "Brazilian Cars": "Brazil",
  "Comparatives and Superlatives": "Grammar",
  "Famous Landmarks": "World",
  "Flags": "World",
  "Food and Drink": "Vocabulary",
  "Fortnite": "Pop Culture",
  "Fruits": "Vocabulary",
  "Geography": "World",
  "Harry Potter": "Pop Culture",
  "How Many": "World",
  "Irregular Verbs": "Grammar",
  "Marvel and DC": "Pop Culture",
  "Math": "World",
  "Minecraft": "Pop Culture",
  "Mobile Games": "Pop Culture",
  "Opposites": "Grammar",
  "Past Continuous": "Grammar",
  "Past Perfect": "Grammar",
  "Periodic Table": "World",
  "Phrasal Verbs": "Grammar",
  "Pop Culture": "Pop Culture",
  "Pop Music": "Pop Culture",
  "Present Continuous": "Grammar",
  "Present Perfect": "Grammar",
  "Roblox": "Pop Culture",
  "Science": "World",
  "Simple Past": "Grammar",
  "Simple Present": "Grammar",
  "Spelling": "Grammar",
  "Stage Names": "Pop Culture",
  "Stranger Things": "Pop Culture",
  "The Letter A": "Vocabulary",
  "Vegetables": "Vocabulary",
  "World Capitals": "World"
};
var categories = {
  "Animals": [
    {"q":"What is the largest land animal?","a":"elephant","rank":1,"cefr":"A1","alt":["African elephant"]},
    {"q":"What is the fastest land animal?","a":"cheetah","rank":2,"cefr":"A1"},
    {"q":"What do we call a baby dog?","a":"puppy","rank":3,"cefr":"A1"},
    {"q":"What is the largest animal in the world (lives in the ocean)?","a":"blue whale","rank":4,"cefr":"A2"},
    {"q":"What do we call a baby cat?","a":"kitten","rank":5,"cefr":"A2"},
    {"q":"Which bird cannot fly but runs very fast?","a":"ostrich","rank":6,"cefr":"A2"},
    {"q":"What is the tallest animal in the world?","a":"giraffe","rank":7,"cefr":"B1"},
    {"q":"Which animal is known for changing its skin color?","a":"chameleon","rank":8,"cefr":"B1"},
    {"q":"What do we call a group of lions?","a":"a pride","rank":9,"cefr":"B1"},
    {"q":"Which animal has the longest lifespan among land animals?","a":"tortoise","rank":10,"cefr":"B1","alt":["Galapagos tortoise","elephant"]},
    {"q":"Which mammal is the only one that can truly fly?","a":"bat","rank":11,"cefr":"B2"},
    {"q":"What is a group of crows called?","a":"a murder","rank":12,"cefr":"B2"},
    {"q":"Which animal sleeps the most hours per day?","a":"koala","rank":13,"cefr":"B2","alt":["sloth"]},
    {"q":"What is unique about a platypus, besides laying eggs?","a":"it is venomous","rank":14,"cefr":"B2","alt":["it produces venom","electroreception"]},
    {"q":"Which living animal has the strongest bite force ever measured?","a":"saltwater crocodile","rank":15,"cefr":"B2"}
  ],
  "Brazilian Capitals": [
    {"q":"What is the capital of Brazil?","a":"Brasília","rank":1,"cefr":"A1","alt":["Brasilia"]},
    {"q":"What is the capital of São Paulo state?","a":"São Paulo","rank":2,"cefr":"A1","alt":["Sao Paulo"]},
    {"q":"What is the capital of Rio de Janeiro state?","a":"Rio de Janeiro","rank":3,"cefr":"A1"},
    {"q":"What is the capital of Paraná state?","a":"Curitiba","rank":4,"cefr":"A2"},
    {"q":"What is the capital of Minas Gerais?","a":"Belo Horizonte","rank":5,"cefr":"A2"},
    {"q":"What is the capital of Bahia?","a":"Salvador","rank":6,"cefr":"A2"},
    {"q":"What is the capital of Rio Grande do Sul?","a":"Porto Alegre","rank":7,"cefr":"B1"},
    {"q":"What is the capital of Pernambuco?","a":"Recife","rank":8,"cefr":"B1"},
    {"q":"What is the capital of Santa Catarina?","a":"Florianópolis","rank":9,"cefr":"B1","alt":["Florianopolis"]},
    {"q":"What is the capital of Ceará?","a":"Fortaleza","rank":10,"cefr":"B1","alt":["Ceara"]},
    {"q":"What is the capital of Amazonas?","a":"Manaus","rank":11,"cefr":"B2"},
    {"q":"What is the capital of Pará?","a":"Belém","rank":12,"cefr":"B2","alt":["Belem","Para"]},
    {"q":"What is the capital of Goiás?","a":"Goiânia","rank":13,"cefr":"B2","alt":["Goiania"]},
    {"q":"What is the capital of Mato Grosso do Sul?","a":"Campo Grande","rank":14,"cefr":"B2"},
    {"q":"What is the capital of Tocantins?","a":"Palmas","rank":15,"cefr":"B2"}
  ],
  "Brazilian Cars": [
    {"q":"What color is commonly associated with taxis in Brazil?","a":"yellow","rank":1,"cefr":"A1"},
    {"q":"What American brand makes the popular Onix model sold in Brazil?","a":"Chevrolet","rank":2,"cefr":"A1"},
    {"q":"What is the Portuguese word for 'car'?","a":"carro","rank":3,"cefr":"A1"},
    {"q":"What Volkswagen model, iconic in Brazil, is nicknamed 'Fusca'?","a":"Beetle","rank":4,"cefr":"A2","alt":["VW Beetle","Fusca"]},
    {"q":"What Fiat model is one of the best-selling cars in Brazil?","a":"Fiat Mobi","rank":5,"cefr":"A2","alt":["Fiat Strada","Fiat Argo","Fiat Palio","Strada","Argo","Mobi"]},
    {"q":"What fuel type, made from sugarcane, is widely used in Brazilian cars?","a":"ethanol","rank":6,"cefr":"A2"},
    {"q":"What term describes a car that can run on both gasoline and ethanol?","a":"flex-fuel","rank":7,"cefr":"B1","alt":["flex"]},
    {"q":"What was the first car mass-produced in Brazil, built starting in 1956?","a":"Romi-Isetta","rank":8,"cefr":"B1"},
    {"q":"What popular pickup truck is made by Fiat in Brazil?","a":"Fiat Toro","rank":9,"cefr":"B1","alt":["Toro"]},
    {"q":"What Volkswagen car was Brazil's best-selling car for 27 years in a row?","a":"Gol","rank":10,"cefr":"B1","alt":["VW Gol","Volkswagen Gol"]},
    {"q":"In what year did the Volkswagen Beetle ('Fusca') finally stop being produced in Brazil?","a":"1996","rank":11,"cefr":"B2","alt":["1986"]},
    {"q":"Which area near São Paulo, named after three cities, is the center of Brazil's car industry?","a":"the ABC Paulista","rank":12,"cefr":"B2","alt":["ABC","ABC region"]},
    {"q":"What do Brazilians call a cheap car with a small 1.0 engine?","a":"carro popular","rank":13,"cefr":"B2","alt":["popular car"]},
    {"q":"What Chinese brand makes electric and hybrid cars at a factory in Bahia?","a":"BYD","rank":14,"cefr":"B2","alt":["1.0"]},
    {"q":"What independent Brazilian automaker was a pioneer of beach buggies before it closed in the 1990s?","a":"Gurgel","rank":15,"cefr":"B2"}
  ],
  "Comparatives and Superlatives": [
    {"q":"What is the comparative form of 'big'?","a":"bigger","rank":1,"cefr":"A1"},
    {"q":"What is the superlative form of 'tall'?","a":"tallest","rank":2,"cefr":"A1"},
    {"q":"What is the comparative form of 'good'?","a":"better","rank":3,"cefr":"A1"},
    {"q":"What is the superlative form of 'good'?","a":"best","rank":4,"cefr":"A2"},
    {"q":"What is the comparative form of 'happy'?","a":"happier","rank":5,"cefr":"A2"},
    {"q":"What is the comparative form of 'bad'?","a":"worse","rank":6,"cefr":"A2"},
    {"q":"What word do we add before long adjectives to make a comparative, like 'beautiful'?","a":"more","rank":7,"cefr":"B1"},
    {"q":"What is the superlative form of 'far'?","a":"farthest","rank":8,"cefr":"B1","alt":["furthest"]},
    {"q":"Fill in: This book is ___ interesting than that one. (more/most)","a":"more interesting","rank":9,"cefr":"B1"},
    {"q":"What is the comparative form of 'little' (amount)?","a":"less","rank":10,"cefr":"B1"},
    {"q":"Correct the error: 'This is the most best film.'","a":"This is the best film.","rank":11,"cefr":"B2"},
    {"q":"Fill in: The Nile is ___ longer than the Thames. (much/very)","a":"much","rank":12,"cefr":"B2"},
    {"q":"What structure means two things increase together, e.g. 'the more you practice, ___ '?","a":"the better you get","rank":13,"cefr":"B2"},
    {"q":"Fill in: She is as tall ___ her brother.","a":"as","rank":14,"cefr":"B2"},
    {"q":"What is the superlative form of 'little' (amount)?","a":"least","rank":15,"cefr":"B2"}
  ],
  "Famous Landmarks": [
    {"q":"In which country is the Eiffel Tower?","a":"France","rank":1,"cefr":"A1"},
    {"q":"In which country is the Great Wall?","a":"China","rank":2,"cefr":"A1"},
    {"q":"In which country is the Statue of Liberty?","a":"USA","rank":3,"cefr":"A1","alt":["United States"]},
    {"q":"In which country is the Colosseum?","a":"Italy","rank":4,"cefr":"A2"},
    {"q":"In which country is Christ the Redeemer?","a":"Brazil","rank":5,"cefr":"A2"},
    {"q":"In which country is the Taj Mahal?","a":"India","rank":6,"cefr":"A2"},
    {"q":"In which country is Machu Picchu?","a":"Peru","rank":7,"cefr":"B1"},
    {"q":"In which country is Big Ben (Elizabeth Tower)?","a":"England","rank":8,"cefr":"B1","alt":["UK","United Kingdom"]},
    {"q":"In which country are the pyramids of Giza?","a":"Egypt","rank":9,"cefr":"B1"},
    {"q":"In which country is the Sydney Opera House?","a":"Australia","rank":10,"cefr":"B1"},
    {"q":"In which country is Petra?","a":"Jordan","rank":11,"cefr":"B2"},
    {"q":"In which country is Chichén Itzá, the famous Mayan pyramid?","a":"Mexico","rank":12,"cefr":"B2"},
    {"q":"In which country is the Sagrada Família?","a":"Spain","rank":13,"cefr":"B2"},
    {"q":"In which country is Angkor Wat?","a":"Cambodia","rank":14,"cefr":"B2"},
    {"q":"In which country is the Blue Mosque?","a":"Turkey","rank":15,"cefr":"B2"}
  ],
  "Flags": [
    {"q":"What two colors are on the flag of Japan?","a":"white and red","rank":1,"cefr":"A1","alt":["red and white"]},
    {"q":"What color is the maple leaf on Canada's flag?","a":"red","rank":2,"cefr":"A1"},
    {"q":"What shape is on the flag of Brazil, besides the circle?","a":"a rhombus/diamond","rank":3,"cefr":"A1","alt":["diamond","rhombus"]},
    {"q":"How many stars are on the current flag of the USA?","a":"50","rank":4,"cefr":"A2"},
    {"q":"What color is the star on the flag of Turkey?","a":"white","rank":5,"cefr":"A2"},
    {"q":"Which country's flag is a simple red circle on a white background?","a":"Japan","rank":6,"cefr":"A2"},
    {"q":"What word is written on Brazil's flag?","a":"Ordem e Progresso","rank":7,"cefr":"B1"},
    {"q":"What animal appears on the flag of Mexico?","a":"an eagle","rank":8,"cefr":"B1","alt":["eagle"]},
    {"q":"What three colors make up the flag of Italy?","a":"green, white, and red","rank":9,"cefr":"B1"},
    {"q":"What animal is depicted on the flag of Sri Lanka?","a":"a lion","rank":10,"cefr":"B1","alt":["lion"]},
    {"q":"What is the only national flag that is not rectangular?","a":"Nepal","rank":11,"cefr":"B2"},
    {"q":"How many points does the star have on the flag of Chile?","a":"5","rank":12,"cefr":"B2"},
    {"q":"What shape is the white cross on the flag of Switzerland?","a":"a plus sign/equilateral cross","rank":13,"cefr":"B2","alt":["cross","plus sign"]},
    {"q":"Which two countries have nearly identical flags (differing mainly in shade), Romania and...?","a":"Chad","rank":14,"cefr":"B2","alt":["Moldova"]},
    {"q":"How many gold stars are in the circle on the European Union flag?","a":"12","rank":15,"cefr":"B2","alt":["twelve"]}
  ],
  "Food and Drink": [
    {"q":"What do you call the first meal of the day?","a":"breakfast","rank":1,"cefr":"A1"},
    {"q":"What white drink comes from cows?","a":"milk","rank":2,"cefr":"A1"},
    {"q":"What yellow spread, made from cream, do people put on bread?","a":"butter","rank":3,"cefr":"A1","alt":["cheese","jam"]},
    {"q":"What do you call a meal eaten in the middle of the day?","a":"lunch","rank":4,"cefr":"A2"},
    {"q":"What hot drink is made from roasted beans?","a":"coffee","rank":5,"cefr":"A2"},
    {"q":"What do you call food that is not cooked?","a":"raw","rank":6,"cefr":"A2"},
    {"q":"What word describes food with a lot of spice that burns your mouth?","a":"spicy","rank":7,"cefr":"B1"},
    {"q":"What do you call the list of dishes in a restaurant?","a":"menu","rank":8,"cefr":"B1"},
    {"q":"What word means 'without meat' in a diet?","a":"vegetarian","rank":9,"cefr":"B1"},
    {"q":"What do you call money left for a waiter after a meal?","a":"tip","rank":10,"cefr":"B1"},
    {"q":"What is the French term for a light snack served before a meal?","a":"hors d'oeuvre","rank":11,"cefr":"B2","alt":["appetizer"]},
    {"q":"What word describes meat cooked slowly in liquid?","a":"braised","rank":12,"cefr":"B2","alt":["stewed"]},
    {"q":"What do you call a chef's special selection of small dishes to taste?","a":"tasting menu","rank":13,"cefr":"B2","alt":["degustation"]},
    {"q":"What do you call a party where every guest brings a dish to share?","a":"potluck","rank":14,"cefr":"B2","alt":["potluck dinner"]},
    {"q":"What cooking method uses very high heat with little oil, tossing quickly?","a":"stir-frying","rank":15,"cefr":"B2"}
  ],
  "Fortnite": [
    {"q":"What is the name of the flying bus that drops players onto the map?","a":"the Battle Bus","rank":1,"cefr":"A1","alt":["Battle Bus"]},
    {"q":"What do you call the shrinking barrier that forces players together?","a":"the storm","rank":2,"cefr":"A1","alt":["the storm circle"]},
    {"q":"What must players collect to build walls, ramps, and floors?","a":"materials","rank":3,"cefr":"A1","alt":["resources","wood/stone/metal"]},
    {"q":"What is the in-game currency used to buy skins and cosmetics?","a":"V-Bucks","rank":4,"cefr":"A2"},
    {"q":"What color shows that a Fortnite weapon is Legendary?","a":"orange","rank":5,"cefr":"A2","alt":["gold"]},
    {"q":"What do you call a full outfit change for your character, bought or unlocked?","a":"a skin","rank":6,"cefr":"A2","alt":["skin","outfit"]},
    {"q":"What is the maximum number of players who can land on the island in a standard match?","a":"100","rank":7,"cefr":"B1"},
    {"q":"What is the seasonal item catalog called that offers cosmetic rewards for playing?","a":"the Battle Pass","rank":8,"cefr":"B1","alt":["Battle Pass"]},
    {"q":"What is the term for eliminating every other player and winning the match?","a":"Victory Royale","rank":9,"cefr":"B1"},
    {"q":"What building material is the strongest but slowest to place?","a":"metal","rank":10,"cefr":"B1"},
    {"q":"What was the 2019 event called when a black hole swallowed the whole map?","a":"The End","rank":11,"cefr":"B2","alt":["the black hole event","Chapter 1 finale"]},
    {"q":"What do you do to help a knocked-down teammate get back up?","a":"revive them","rank":12,"cefr":"B2","alt":["revive","reviving"]},
    {"q":"What is the name for landing quickly and aggressively at the very start of a match to fight early?","a":"dropping hot","rank":13,"cefr":"B2","alt":["hot dropping"]},
    {"q":"What is the term for the practice of quickly building structures for defense in a fight?","a":"turtling","rank":14,"cefr":"B2","alt":["building up"]},
    {"q":"What glowing boxes, found around the map, hold weapons and make a humming sound?","a":"chests","rank":15,"cefr":"B2","alt":["treasure chests"]}
  ],
  "Fruits": [
    {"q":"What yellow fruit do monkeys love to eat?","a":"banana","rank":1,"cefr":"A1"},
    {"q":"What red fruit is often used in a pie and keeps the doctor away?","a":"apple","rank":2,"cefr":"A1"},
    {"q":"What citrus fruit has the same name as its color?","a":"orange","rank":3,"cefr":"A1"},
    {"q":"What small red fruit is used to make jam and grows on bushes?","a":"strawberry","rank":4,"cefr":"A2"},
    {"q":"What small orange fruit, related to the peach, has fuzzy skin and a single pit?","a":"apricot","rank":5,"cefr":"A2"},
    {"q":"What green or purple small fruit grows in bunches and is used to make wine?","a":"grape","rank":6,"cefr":"A2"},
    {"q":"What tropical fruit is green outside, has a large pit, and is often used in guacamole?","a":"avocado","rank":7,"cefr":"B1"},
    {"q":"What yellow citrus fruit is very sour and used in lemonade?","a":"lemon","rank":8,"cefr":"B1"},
    {"q":"What small red or black fruit grows on thin canes and has a hollow center?","a":"raspberry","rank":9,"cefr":"B1","alt":["blackberry"]},
    {"q":"What tropical yellow fruit is spiky on the outside with sweet segments inside?","a":"pineapple","rank":10,"cefr":"B1"},
    {"q":"What fruit is a hybrid of a plum and an apricot?","a":"pluot","rank":11,"cefr":"B2","alt":["plumcot"]},
    {"q":"What fruit, grown widely in Brazil, is often used to make an energy drink and has a small black seed inside?","a":"guaraná","rank":12,"cefr":"B2","alt":["guarana"]},
    {"q":"What purple/black fruit, common in the Amazon, is used in bowls and smoothies?","a":"açaí","rank":13,"cefr":"B2","alt":["acai"]},
    {"q":"What tropical fruit is known as the 'king of fruits' in Southeast Asia for its strong smell?","a":"durian","rank":14,"cefr":"B2"},
    {"q":"What fruit has a hard shell, milky white flesh, and grows on palm trees?","a":"coconut","rank":15,"cefr":"B2"}
  ],
  "Geography": [
    {"q":"What is the largest continent?","a":"Asia","rank":1,"cefr":"A1"},
    {"q":"What is the largest ocean?","a":"Pacific Ocean","rank":2,"cefr":"A1","alt":["Pacific"]},
    {"q":"What is the smallest continent?","a":"Australia","rank":3,"cefr":"A1","alt":["Oceania"]},
    {"q":"What is the longest river in the world? (either accepted answer counts)","a":"Nile","rank":4,"cefr":"A2","alt":["Amazon"]},
    {"q":"What is the tallest mountain in the world?","a":"Mount Everest","rank":5,"cefr":"A2","alt":["Everest"]},
    {"q":"What is the largest country by area?","a":"Russia","rank":6,"cefr":"A2"},
    {"q":"What is the largest desert by area in the world overall (it's a cold one)?","a":"Antarctic Desert","rank":7,"cefr":"B1","alt":["Antarctica"]},
    {"q":"What is the largest hot desert in the world?","a":"Sahara","rank":8,"cefr":"B1"},
    {"q":"Which country currently has the largest population in the world?","a":"India","rank":9,"cefr":"B1","alt":["China"]},
    {"q":"What is the driest place on Earth?","a":"Atacama Desert","rank":10,"cefr":"B1","alt":["Death Valley","McMurdo Dry Valleys"]},
    {"q":"What is the deepest point in the ocean?","a":"Mariana Trench","rank":11,"cefr":"B2","alt":["Challenger Deep"]},
    {"q":"What line of latitude divides the Earth into Northern and Southern hemispheres?","a":"the Equator","rank":12,"cefr":"B2","alt":["Equator"]},
    {"q":"Which strait separates Asia and North America?","a":"Bering Strait","rank":13,"cefr":"B2"},
    {"q":"What is the largest island in the world?","a":"Greenland","rank":14,"cefr":"B2"},
    {"q":"What is the saltiest large body of water, famous for floating in it?","a":"the Dead Sea","rank":15,"cefr":"B2","alt":["Dead Sea"]}
  ],
  "Harry Potter": [
    {"q":"What is the name of the school Harry Potter attends?","a":"Hogwarts","rank":1,"cefr":"A1"},
    {"q":"What is the name of Harry Potter's best friend with red hair?","a":"Ron Weasley","rank":2,"cefr":"A1","alt":["Ron"]},
    {"q":"What magical sport is played on flying broomsticks?","a":"Quidditch","rank":3,"cefr":"A1"},
    {"q":"What is the name of Harry's owl?","a":"Hedwig","rank":4,"cefr":"A2"},
    {"q":"What house is Harry Potter sorted into?","a":"Gryffindor","rank":5,"cefr":"A2"},
    {"q":"What is the name of the villain who tries to kill Harry?","a":"Voldemort","rank":6,"cefr":"A2","alt":["Lord Voldemort"]},
    {"q":"What is the name of the school's headmaster in the first books?","a":"Albus Dumbledore","rank":7,"cefr":"B1","alt":["Dumbledore"]},
    {"q":"What is the name of Harry's other best friend, a clever girl?","a":"Hermione Granger","rank":8,"cefr":"B1","alt":["Hermione"]},
    {"q":"What creature guards Hogwarts and drains happiness (feeds on fear)?","a":"Dementor","rank":9,"cefr":"B1"},
    {"q":"What house is known for cunning and ambition?","a":"Slytherin","rank":10,"cefr":"B1"},
    {"q":"What is the name of the magical objects Voldemort split his soul into?","a":"Horcruxes","rank":11,"cefr":"B2"},
    {"q":"What platform at King's Cross station leads to the Hogwarts Express?","a":"Platform 9¾","rank":12,"cefr":"B2","alt":["Platform 9 3/4"]},
    {"q":"What is the name of Harry's godfather?","a":"Sirius Black","rank":13,"cefr":"B2"},
    {"q":"What potion allows the drinker to transform into someone else?","a":"Polyjuice Potion","rank":14,"cefr":"B2","alt":["Polyjuice"]},
    {"q":"What is the name of the wandmaker's shop in Diagon Alley?","a":"Ollivanders","rank":15,"cefr":"B2"}
  ],
  "How Many": [
    {"q":"How many months are in a year?","a":"12","rank":1,"cefr":"A1"},
    {"q":"How many legs does a spider have?","a":"8","rank":2,"cefr":"A1"},
    {"q":"How many players are on a basketball team on the court at once?","a":"5","rank":3,"cefr":"A1"},
    {"q":"How many players are on a football (soccer) team on the field?","a":"11","rank":4,"cefr":"A2"},
    {"q":"How many continents are there?","a":"7","rank":5,"cefr":"A2"},
    {"q":"How many strings does a standard guitar have?","a":"6","rank":6,"cefr":"A2"},
    {"q":"How many bones are in the adult human body?","a":"206","rank":7,"cefr":"B1"},
    {"q":"How many time zones does Brazil have?","a":"4","rank":8,"cefr":"B1"},
    {"q":"How many countries border Brazil?","a":"10","rank":9,"cefr":"B1"},
    {"q":"How many days are in the month of February in a leap year?","a":"29","rank":10,"cefr":"B1"},
    {"q":"How many hearts does an octopus have?","a":"3","rank":11,"cefr":"B2"},
    {"q":"How many moons does Mars have?","a":"2","rank":12,"cefr":"B2"},
    {"q":"How many chromosomes does a human have?","a":"46","rank":13,"cefr":"B2"},
    {"q":"How many teeth does an adult human have?","a":"32","rank":14,"cefr":"B2"},
    {"q":"How many innings are in a standard baseball game?","a":"9","rank":15,"cefr":"B2"}
  ],
  "Irregular Verbs": [
    {"q":"What is the past tense of 'be'?","a":"was / were","rank":1,"cefr":"A1"},
    {"q":"What is the past tense of 'have'?","a":"had","rank":2,"cefr":"A1"},
    {"q":"What is the past tense of 'do'?","a":"did","rank":3,"cefr":"A1"},
    {"q":"What is the past tense of 'see'?","a":"saw","rank":4,"cefr":"A1"},
    {"q":"What is the past tense of 'make'?","a":"made","rank":5,"cefr":"A2"},
    {"q":"What is the past tense of 'take'?","a":"took","rank":6,"cefr":"A2"},
    {"q":"What is the past participle of 'give'?","a":"given","rank":7,"cefr":"A2"},
    {"q":"What is the past participle of 'write'?","a":"written","rank":8,"cefr":"B1"},
    {"q":"What is the past tense of 'catch'?","a":"caught","rank":9,"cefr":"B1"},
    {"q":"What is the past participle of 'begin'?","a":"begun","rank":10,"cefr":"B1"},
    {"q":"What is the past tense of 'swim'?","a":"swam","rank":11,"cefr":"B1"},
    {"q":"What is the past participle of 'fly'?","a":"flown","rank":12,"cefr":"B2"},
    {"q":"What is the past tense of 'lay' (to put something down)?","a":"laid","rank":13,"cefr":"B2"},
    {"q":"What is the past participle of 'lie' (to recline)?","a":"lain","rank":14,"cefr":"B2"},
    {"q":"What is the past tense of 'forsake'?","a":"forsook","rank":15,"cefr":"B2"}
  ],
  "Marvel and DC": [
    {"q":"What is the name of the billionaire superhero also known as Iron Man?","a":"Tony Stark","rank":1,"cefr":"A1"},
    {"q":"What is Superman's home planet?","a":"Krypton","rank":2,"cefr":"A1"},
    {"q":"What is the name of Batman's home city?","a":"Gotham City","rank":3,"cefr":"A1","alt":["Gotham"]},
    {"q":"What is the name of Spider-Man's alter ego?","a":"Peter Parker","rank":4,"cefr":"A2"},
    {"q":"What color is the Hulk?","a":"green","rank":5,"cefr":"A2"},
    {"q":"What is Wonder Woman's home island called?","a":"Themyscira","rank":6,"cefr":"A2"},
    {"q":"What is the name of the team of superheroes led by Captain America and Iron Man?","a":"the Avengers","rank":7,"cefr":"B1","alt":["Avengers"]},
    {"q":"What metal makes up Captain America's shield?","a":"vibranium","rank":8,"cefr":"B1"},
    {"q":"What is the name of the DC team that includes Batman, Superman, and Wonder Woman?","a":"Justice League","rank":9,"cefr":"B1"},
    {"q":"What is Batman's butler and confidant called?","a":"Alfred","rank":10,"cefr":"B1","alt":["Alfred Pennyworth"]},
    {"q":"What nickname is Batman given for his detective skills?","a":"the World's Greatest Detective","rank":11,"cefr":"B2","alt":["World's Greatest Detective"]},
    {"q":"What is the name of the fictional African country Black Panther rules?","a":"Wakanda","rank":12,"cefr":"B2"},
    {"q":"Who is Loki's brother, the god of thunder with a hammer?","a":"Thor","rank":13,"cefr":"B2"},
    {"q":"What toxic element originally powered the arc reactor in Tony Stark's chest?","a":"palladium","rank":14,"cefr":"B2"},
    {"q":"What is the name of the giant purple villain who collects the Infinity Stones?","a":"Thanos","rank":15,"cefr":"B2","alt":["Multiverse Saga"]}
  ],
  "Math": [
    {"q":"What is 2 + 2?","a":"4","rank":1,"cefr":"A1"},
    {"q":"What is 10 - 4?","a":"6","rank":2,"cefr":"A1"},
    {"q":"What is 3 x 3?","a":"9","rank":3,"cefr":"A1"},
    {"q":"What is 12 divided by 4?","a":"3","rank":4,"cefr":"A2"},
    {"q":"How many sides does a pentagon have?","a":"5","rank":5,"cefr":"A2"},
    {"q":"What is 7 x 8?","a":"56","rank":6,"cefr":"A2"},
    {"q":"What is the value of pi, rounded to two decimals?","a":"3.14","rank":7,"cefr":"B1"},
    {"q":"How many degrees are in a right angle?","a":"90","rank":8,"cefr":"B1"},
    {"q":"What is the square root of 64?","a":"8","rank":9,"cefr":"B1"},
    {"q":"How many degrees are in a full circle?","a":"360","rank":10,"cefr":"B1"},
    {"q":"What is the formula for the area of a circle?","a":"πr²","rank":11,"cefr":"B2","alt":["pi times r squared"]},
    {"q":"What is the Pythagorean theorem's formula?","a":"a² + b² = c²","rank":12,"cefr":"B2","alt":["a squared plus b squared equals c squared"]},
    {"q":"What do you call a number that can only be divided evenly by 1 and itself?","a":"prime number","rank":13,"cefr":"B2"},
    {"q":"What is 15% of 200?","a":"30","rank":14,"cefr":"B2"},
    {"q":"What is the sum of the interior angles of a triangle?","a":"180°","rank":15,"cefr":"B2","alt":["180 degrees"]}
  ],
  "Minecraft": [
    {"q":"What block do you get when you punch a tree in Minecraft?","a":"wood","rank":1,"cefr":"A1","alt":["logs","a log"]},
    {"q":"What green, hostile mob explodes when it gets close to you?","a":"Creeper","rank":2,"cefr":"A1"},
    {"q":"What do you use to mine blocks?","a":"a pickaxe","rank":3,"cefr":"A1","alt":["pickaxe"]},
    {"q":"What mineral is used to make the strongest tools before diamond?","a":"iron","rank":4,"cefr":"A2"},
    {"q":"What dimension can you enter using a portal made of obsidian?","a":"the Nether","rank":5,"cefr":"A2","alt":["Nether"]},
    {"q":"What is the name of the flying dragon boss in the End dimension?","a":"Ender Dragon","rank":6,"cefr":"A2"},
    {"q":"What mob can teleport and steals blocks?","a":"Enderman","rank":7,"cefr":"B1"},
    {"q":"What material is needed to make a Nether portal?","a":"obsidian","rank":8,"cefr":"B1"},
    {"q":"What tool do you need to safely mine obsidian?","a":"a diamond pickaxe","rank":9,"cefr":"B1","alt":["diamond pickaxe"]},
    {"q":"What mob attacks at night but burns in sunlight?","a":"Zombie","rank":10,"cefr":"B1","alt":["Skeleton"]},
    {"q":"What blue mineral do you need to enchant items?","a":"lapis lazuli","rank":11,"cefr":"B2","alt":["lapis"]},
    {"q":"What item lets you store and use experience points to improve gear?","a":"enchanting table","rank":12,"cefr":"B2","alt":["anvil"]},
    {"q":"What material, found in the Nether, is stronger than diamond?","a":"netherite","rank":13,"cefr":"B2"},
    {"q":"What three-headed boss do players build from soul sand and skulls?","a":"the Wither","rank":14,"cefr":"B2","alt":["Wither"]},
    {"q":"What redstone component acts like a wire to carry a signal?","a":"redstone dust","rank":15,"cefr":"B2","alt":["redstone wire"]}
  ],
  "Mobile Games": [
    {"q":"In which mobile game do you use a slingshot to hit green pigs?","a":"Angry Birds","rank":1,"cefr":"A1"},
    {"q":"In which mobile game do you swap sweets to make rows of three?","a":"Candy Crush","rank":2,"cefr":"A1","alt":["Candy Crush Saga"]},
    {"q":"What battle royale mobile game has a bus dropping players onto an island?","a":"Fortnite","rank":3,"cefr":"A1","alt":["PUBG Mobile"]},
    {"q":"What mobile game involves catching creatures by walking around real locations?","a":"Pokémon GO","rank":4,"cefr":"A2","alt":["Pokemon Go"]},
    {"q":"What runner mobile game has players dodging trains as a graffiti artist?","a":"Subway Surfers","rank":5,"cefr":"A2"},
    {"q":"In which mobile game do you run from monkeys after stealing a golden idol?","a":"Temple Run","rank":6,"cefr":"A2","alt":["Animal Crossing"]},
    {"q":"What mobile MOBA game features heroes like Layla and Miya?","a":"Mobile Legends: Bang Bang","rank":7,"cefr":"B1","alt":["Mobile Legends"]},
    {"q":"What mobile battle royale is known for its realistic graphics and squads of 4?","a":"PUBG Mobile","rank":8,"cefr":"B1"},
    {"q":"In which mobile game do you swipe to slice flying watermelons and bananas?","a":"Fruit Ninja","rank":9,"cefr":"B1"},
    {"q":"What card-battler mobile game by Supercell features princes and towers?","a":"Clash Royale","rank":10,"cefr":"B1"},
    {"q":"What mobile game by Supercell has players build a village and raid others?","a":"Clash of Clans","rank":11,"cefr":"B2"},
    {"q":"In which mobile game do you tap only the black squares to play a song?","a":"Piano Tiles","rank":12,"cefr":"B2","alt":["Piano Tiles"]},
    {"q":"What Supercell game has heroes called Brawlers, like Shelly and Colt?","a":"Brawl Stars","rank":13,"cefr":"B2","alt":["Last Day on Earth"]},
    {"q":"What mobile game publisher created both Clash of Clans and Clash Royale?","a":"Supercell","rank":14,"cefr":"B2"},
    {"q":"What Supercell farming game has players grow crops and sell them at a roadside shop?","a":"Hay Day","rank":15,"cefr":"B2","alt":["Cooking Fever"]}
  ],
  "Opposites": [
    {"q":"What is the opposite of 'big'?","a":"small","rank":1,"cefr":"A1"},
    {"q":"What is the opposite of 'hot'?","a":"cold","rank":2,"cefr":"A1"},
    {"q":"What is the opposite of 'happy'?","a":"sad","rank":3,"cefr":"A1"},
    {"q":"What is the opposite of 'fast'?","a":"slow","rank":4,"cefr":"A1"},
    {"q":"What is the opposite of 'expensive'?","a":"cheap","rank":5,"cefr":"A2"},
    {"q":"What is the opposite of 'difficult'?","a":"easy","rank":6,"cefr":"A2"},
    {"q":"What is the opposite of 'early'?","a":"late","rank":7,"cefr":"A2"},
    {"q":"What is the opposite of 'generous'?","a":"stingy","rank":8,"cefr":"B1","alt":["mean","selfish"]},
    {"q":"What is the opposite of 'ancient'?","a":"modern","rank":9,"cefr":"B1"},
    {"q":"What is the opposite of 'borrow'?","a":"lend","rank":10,"cefr":"B1"},
    {"q":"What is the opposite of 'accept'?","a":"reject","rank":11,"cefr":"B1"},
    {"q":"What is the opposite of 'reveal'?","a":"conceal","rank":12,"cefr":"B2","alt":["hide"]},
    {"q":"What is the opposite of 'temporary'?","a":"permanent","rank":13,"cefr":"B2"},
    {"q":"What is the opposite of 'humble'?","a":"arrogant","rank":14,"cefr":"B2","alt":["proud"]},
    {"q":"What is the opposite of 'scarce'?","a":"abundant","rank":15,"cefr":"B2","alt":["plentiful"]}
  ],
  "Past Continuous": [
    {"q":"What is the formula for past continuous?","a":"was/were + verb-ing","rank":1,"cefr":"A1"},
    {"q":"Fill in: I ___ TV when she called. (watch)","a":"was watching","rank":2,"cefr":"A1"},
    {"q":"Correct the error: 'She was sleep.'","a":"She was sleeping.","rank":3,"cefr":"A1"},
    {"q":"Fill in: They ___ football at 3pm. (play)","a":"were playing","rank":4,"cefr":"A2"},
    {"q":"Fill in: He ___ dinner when I arrived. (cook)","a":"was cooking","rank":5,"cefr":"A2"},
    {"q":"Make a negative: 'They were having a meeting.'","a":"They were not having a meeting.","rank":6,"cefr":"A2"},
    {"q":"Fill in: While I ___, my phone rang. (study)","a":"was studying","rank":7,"cefr":"B1"},
    {"q":"Which connector is typical for past continuous + simple past: 'when' or 'since'?","a":"when","rank":8,"cefr":"B1"},
    {"q":"Fill in: The children ___ in the garden at noon. (run)","a":"were running","rank":9,"cefr":"B1"},
    {"q":"Make a question: 'She was crying.'","a":"Was she crying?","rank":10,"cefr":"B1"},
    {"q":"Fill in: What ___ you ___ at midnight? (do)","a":"were you doing","rank":11,"cefr":"B2"},
    {"q":"Correct the error: 'Were she sleeping when it happened?'","a":"Was she sleeping when it happened?","rank":12,"cefr":"B2"},
    {"q":"Fill in: The fire ___ for hours before the rain stopped it. (burn)","a":"had been burning","rank":13,"cefr":"B2"},
    {"q":"Explain the difference: 'I was reading when she called' vs 'I read when she called.'","a":"continuous = interrupted action; past = a completed one","rank":14,"cefr":"B2"},
    {"q":"Can past continuous express future-in-the-past? Give an example.","a":"Yes: 'She was leaving the next day.'","rank":15,"cefr":"B2"}
  ],
  "Past Perfect": [
    {"q":"What is the formula for past perfect?","a":"had + past participle","rank":1,"cefr":"A1"},
    {"q":"Fill in: I ___ never ___ sushi before. (eat)","a":"had never eaten","rank":2,"cefr":"A1"},
    {"q":"Correct the error: 'They had went.'","a":"They had gone.","rank":3,"cefr":"A1"},
    {"q":"Fill in: She ___ already ___ when we arrived. (leave)","a":"had already left","rank":4,"cefr":"A2"},
    {"q":"Fill in: He ___ just ___ his homework before dinner. (finish)","a":"had just finished","rank":5,"cefr":"A2"},
    {"q":"Why do we use past perfect? Give a short explanation.","a":"To show one past action happened before another past action.","rank":6,"cefr":"A2"},
    {"q":"Fill in: When I got to the cinema, the film ___ already ___. (start)","a":"had already started","rank":7,"cefr":"B1"},
    {"q":"Make a question: 'She had studied English before.'","a":"Had she studied English before?","rank":8,"cefr":"B1"},
    {"q":"Fill in: They realized they ___ made a mistake. (make)","a":"had made","rank":9,"cefr":"B1"},
    {"q":"What is the past participle of 'choose'?","a":"chosen","rank":10,"cefr":"B1"},
    {"q":"Explain: 'By the time the police arrived, the thief had escaped.' Which action happened first?","a":"The escaping — past perfect marks the earlier action.","rank":11,"cefr":"B2"},
    {"q":"Correct the error: 'He had went to bed before I called.'","a":"He had gone to bed before I called.","rank":12,"cefr":"B2"},
    {"q":"Fill in: I could see that she ___ ___ crying. (have / be)","a":"had been","rank":13,"cefr":"B2"},
    {"q":"What is the difference between 'had seen' and 'had been seeing'?","a":"'had seen' = done; 'had been seeing' = ongoing before that","rank":14,"cefr":"B2"},
    {"q":"Fill in: They ___ never ___ such a big storm before. (experience)","a":"had never experienced","rank":15,"cefr":"B2"}
  ],
  "Periodic Table": [
    {"q":"What is the chemical symbol for hydrogen?","a":"H","rank":1,"cefr":"A1"},
    {"q":"What is the chemical symbol for gold?","a":"Au","rank":2,"cefr":"A1"},
    {"q":"What is the chemical symbol for oxygen?","a":"O","rank":3,"cefr":"A1"},
    {"q":"What is the chemical symbol for iron?","a":"Fe","rank":4,"cefr":"A2"},
    {"q":"What is the chemical symbol for carbon?","a":"C","rank":5,"cefr":"A2"},
    {"q":"What is the chemical symbol for silver?","a":"Ag","rank":6,"cefr":"A2"},
    {"q":"What is the chemical symbol for sodium?","a":"Na","rank":7,"cefr":"B1"},
    {"q":"What is the chemical symbol for helium?","a":"He","rank":8,"cefr":"B1"},
    {"q":"What is the lightest element on the periodic table?","a":"Hydrogen","rank":9,"cefr":"B1"},
    {"q":"What is the chemical symbol for potassium?","a":"K","rank":10,"cefr":"B1"},
    {"q":"What is the chemical symbol for lead?","a":"Pb","rank":11,"cefr":"B2"},
    {"q":"What noble gas is used to fill party balloons because it's lighter than air?","a":"Helium","rank":12,"cefr":"B2"},
    {"q":"What is the chemical symbol for tin?","a":"Sn","rank":13,"cefr":"B2"},
    {"q":"What metal is liquid at room temperature?","a":"Mercury","rank":14,"cefr":"B2"},
    {"q":"What is the chemical symbol for mercury?","a":"Hg","rank":15,"cefr":"B2"}
  ],
  "Phrasal Verbs": [
    {"q":"Which phrasal verb means 'to stop sleeping'?","a":"wake up","rank":1,"cefr":"A1"},
    {"q":"Which phrasal verb means 'to take a seat'?","a":"sit down","rank":2,"cefr":"A1"},
    {"q":"Which phrasal verb means 'to make a device work' (like a light)?","a":"turn on","rank":3,"cefr":"A1"},
    {"q":"Which phrasal verb means 'to search for a word in a dictionary'?","a":"look up","rank":4,"cefr":"A2"},
    {"q":"Which phrasal verb means 'to stop trying'?","a":"give up","rank":5,"cefr":"A2"},
    {"q":"Which phrasal verb means 'to enter a bus or train'?","a":"get on","rank":6,"cefr":"A2"},
    {"q":"Which phrasal verb means 'to postpone'?","a":"put off","rank":7,"cefr":"B1"},
    {"q":"Which phrasal verb means 'to have none left' of something?","a":"run out of","rank":8,"cefr":"B1"},
    {"q":"Which phrasal verb means 'a plane leaves the ground'?","a":"take off","rank":9,"cefr":"B1"},
    {"q":"Which phrasal verb can mean 'a device stops working'?","a":"break down","rank":10,"cefr":"B1"},
    {"q":"Which phrasal verb means 'to find something by chance'?","a":"come across","rank":11,"cefr":"B2"},
    {"q":"Which phrasal verb means 'to escape punishment for something'?","a":"get away with","rank":12,"cefr":"B2"},
    {"q":"Which phrasal verb means 'to introduce a topic in conversation'?","a":"bring up","rank":13,"cefr":"B2"},
    {"q":"Which phrasal verb means 'to cancel an event'?","a":"call off","rank":14,"cefr":"B2"},
    {"q":"Which phrasal verb means 'to admire and respect someone'?","a":"look up to","rank":15,"cefr":"B2"}
  ],
  "Pop Culture": [
    {"q":"What streaming service is known for shows like Stranger Things?","a":"Netflix","rank":1,"cefr":"A1"},
    {"q":"What social media app is known for short dance and lip-sync videos?","a":"TikTok","rank":2,"cefr":"A1"},
    {"q":"What annual award show honors the best in film?","a":"the Oscars","rank":3,"cefr":"A1","alt":["Academy Awards"]},
    {"q":"What music streaming app uses a green logo?","a":"Spotify","rank":4,"cefr":"A2"},
    {"q":"What word describes a video or image that spreads very quickly online?","a":"viral","rank":5,"cefr":"A2"},
    {"q":"What are short vertical videos on Instagram called?","a":"Reels","rank":6,"cefr":"A2","alt":["Instagram Reels"]},
    {"q":"What term describes a celebrity's dedicated fanbase online?","a":"fandom","rank":7,"cefr":"B1","alt":["stan community"]},
    {"q":"What annual music award show is hosted by the Recording Academy?","a":"the Grammys","rank":8,"cefr":"B1","alt":["Grammy Awards"]},
    {"q":"What term describes posting content to intentionally provoke or annoy people online?","a":"trolling","rank":9,"cefr":"B1","alt":["trolling online"]},
    {"q":"What word describes a phrase or image that's copied and spread with variations online?","a":"meme","rank":10,"cefr":"B1"},
    {"q":"What do you call a video diary that a YouTuber makes about their daily life?","a":"a vlog","rank":11,"cefr":"B2","alt":["vlog","video blog"]},
    {"q":"What do you call a person who earns money by posting content on social media?","a":"an influencer","rank":12,"cefr":"B2","alt":["influencer","content creator"]},
    {"q":"What word describes editing photos to look unrealistically perfect?","a":"photoshopping","rank":13,"cefr":"B2","alt":["retouching"]},
    {"q":"Which French city holds a famous film festival every May?","a":"Cannes","rank":14,"cefr":"B2","alt":["Cannes"]},
    {"q":"What term describes content designed to grab attention with exaggerated claims?","a":"clickbait","rank":15,"cefr":"B2"}
  ],
  "Pop Music": [
    {"q":"What pop singer is known for the song 'Shake It Off'?","a":"Taylor Swift","rank":1,"cefr":"A1"},
    {"q":"What Brazilian singer had a global hit with the song 'Envolver'?","a":"Anitta","rank":2,"cefr":"A1"},
    {"q":"What pop star is known as 'Queen Bey'?","a":"Beyoncé","rank":3,"cefr":"A1","alt":["Beyonce"]},
    {"q":"What Canadian singer, who started by posting cover songs on YouTube, is known for the song 'Sorry'?","a":"Justin Bieber","rank":4,"cefr":"A2"},
    {"q":"What Barbadian singer is known for hits like 'Umbrella' and 'Diamonds'?","a":"Rihanna","rank":5,"cefr":"A2"},
    {"q":"What pop singer is known for the song 'Bad Guy'?","a":"Billie Eilish","rank":6,"cefr":"A2"},
    {"q":"What South Korean group, with members like Jisoo and Lisa, is known for global pop hits?","a":"Blackpink","rank":7,"cefr":"B1"},
    {"q":"What do Taylor Swift's fans call themselves?","a":"Swifties","rank":8,"cefr":"B1","alt":["stan community"]},
    {"q":"What Colombian singer is known worldwide for the song 'Hips Don't Lie'?","a":"Shakira","rank":9,"cefr":"B1"},
    {"q":"What music style from Rio's favelas did Anitta take around the world?","a":"funk","rank":10,"cefr":"B1","alt":["funk carioca","Brazilian funk","baile funk"]},
    {"q":"What British singer's album 'Divide' produced hits like 'Shape of You'?","a":"Ed Sheeran","rank":11,"cefr":"B2"},
    {"q":"Which K-pop boy band has seven members, including Jungkook and V?","a":"BTS","rank":12,"cefr":"B2","alt":["Spotify streams"]},
    {"q":"What pop singer collaborated with Anitta on international crossover hits?","a":"Cardi B","rank":13,"cefr":"B2","alt":["Maluma","J Balvin"]},
    {"q":"What term describes a song's official visual accompaniment released alongside it?","a":"music video","rank":14,"cefr":"B2"},
    {"q":"What weekly US chart lists the 100 most popular songs?","a":"Billboard Hot 100","rank":15,"cefr":"B2","alt":["Hot 100","Billboard"]}
  ],
  "Present Continuous": [
    {"q":"Fill in both blanks: She ___ ___ a book right now. (be / read)","a":"is reading","rank":1,"cefr":"A1"},
    {"q":"Fill in both blanks: I ___ ___ to music right now. (be / listen)","a":"am listening","rank":2,"cefr":"A1"},
    {"q":"Fill in both blanks: They ___ ___ football outside. (be / play)","a":"are playing","rank":3,"cefr":"A1"},
    {"q":"Fill in both blanks: Look! It ___ ___! (be / rain)","a":"is raining","rank":4,"cefr":"A2"},
    {"q":"Fill in both blanks: We ___ ___ dinner at the moment. (be / have)","a":"are having","rank":5,"cefr":"A2"},
    {"q":"What is the -ing form of 'sit'?","a":"sitting","rank":6,"cefr":"A2"},
    {"q":"Make a negative: 'He is sleeping.'","a":"He is not sleeping.","rank":7,"cefr":"B1"},
    {"q":"What is the -ing form of 'run'?","a":"running","rank":8,"cefr":"B1"},
    {"q":"Fill in: Why ___ you ___? (shout)","a":"are you shouting","rank":9,"cefr":"B1"},
    {"q":"Present continuous can refer to future arrangements. Give an example.","a":"'I am meeting her tomorrow.'","rank":10,"cefr":"B1"},
    {"q":"Name a stative verb (a verb describing a state, not normally used in continuous tenses).","a":"know","rank":11,"cefr":"B2","alt":["believe","love","hate","want","need","own","understand","seem","belong","prefer","hope","remember"]},
    {"q":"Correct the error: 'She is knowing the answer.'","a":"She knows the answer.","rank":12,"cefr":"B2"},
    {"q":"Fill in: The company ___ its prices this year. (increase)","a":"is increasing","rank":13,"cefr":"B2"},
    {"q":"Explain: 'He is always losing his keys.' What does 'always' add here?","a":"It expresses annoyance at a repeated habit.","rank":14,"cefr":"B2"},
    {"q":"Fill in: Don't disturb her — she ___ ___ a presentation for tomorrow. (be / prepare)","a":"is preparing","rank":15,"cefr":"B2"}
  ],
  "Present Perfect": [
    {"q":"What two words form the present perfect auxiliary?","a":"have / has","rank":1,"cefr":"A1"},
    {"q":"Fill in: I ___ that movie before. (see)","a":"have seen","rank":2,"cefr":"A1"},
    {"q":"Correct the error: 'I have went to Paris.'","a":"I have gone to Paris.","rank":3,"cefr":"A1"},
    {"q":"Fill in: She ___ already ___. (eat)","a":"has already eaten","rank":4,"cefr":"A2"},
    {"q":"Fill in: They ___ to Paris. (never / be)","a":"have never been","rank":5,"cefr":"A2"},
    {"q":"Which signal word goes with present perfect: 'yesterday' or 'already'?","a":"already","rank":6,"cefr":"A2"},
    {"q":"Fill in: We ___ just ___ dinner. (finish)","a":"have just finished","rank":7,"cefr":"B1"},
    {"q":"What is the past participle of 'break'?","a":"broken","rank":8,"cefr":"B1"},
    {"q":"Make a question: 'She has met the president.'","a":"Has she met the president?","rank":9,"cefr":"B1"},
    {"q":"Fill in: How long ___ you ___ English? (study)","a":"have you studied","rank":10,"cefr":"B1","alt":["have you been studying"]},
    {"q":"Fill in: This is the best film I ___ ever ___. (see)","a":"have ever seen","rank":11,"cefr":"B2"},
    {"q":"Correct the error: 'Have you ever went abroad?'","a":"Have you ever gone abroad?","rank":12,"cefr":"B2"},
    {"q":"What is the past participle of 'arise'?","a":"arisen","rank":13,"cefr":"B2"},
    {"q":"Fill in: It ___ not ___ since Monday. (rain)","a":"has not rained","rank":14,"cefr":"B2"},
    {"q":"Explain the difference between 'I have lived here for 5 years' and 'I lived here for 5 years'.","a":"present perfect = still living there; past = not anymore","rank":15,"cefr":"B2"}
  ],
  "Roblox": [
    {"q":"What is the in-game currency in Roblox called?","a":"Robux","rank":1,"cefr":"A1"},
    {"q":"What do players create their character's look with in Roblox?","a":"an avatar","rank":2,"cefr":"A1","alt":["avatar"]},
    {"q":"What do you call individual games made by users on Roblox?","a":"experiences","rank":3,"cefr":"A1","alt":["games"]},
    {"q":"What popular Roblox game involves surviving a killer among a group of players?","a":"Murder Mystery 2","rank":4,"cefr":"A2","alt":["MM2"]},
    {"q":"What Roblox game has players race through obstacle courses?","a":"Obby","rank":5,"cefr":"A2","alt":["obstacle course"]},
    {"q":"What is the tool used by developers to build Roblox games called?","a":"Roblox Studio","rank":6,"cefr":"A2"},
    {"q":"What popular Roblox game is themed around adopting and raising virtual pets?","a":"Adopt Me!","rank":7,"cefr":"B1","alt":["Adopt Me"]},
    {"q":"What language is used to code scripts in Roblox Studio?","a":"Lua","rank":8,"cefr":"B1"},
    {"q":"What Roblox game type has players build and defend a base from monster waves?","a":"tower defense","rank":9,"cefr":"B1","alt":["Tower Defense Simulator"]},
    {"q":"What do players call a Roblox game where you click again and again to grow stronger?","a":"a simulator","rank":10,"cefr":"B1","alt":["simulator","clicker"]},
    {"q":"What Roblox game lets players live a city life, own a house and drive cars?","a":"Brookhaven","rank":11,"cefr":"B2","alt":["Brookhaven RP"]},
    {"q":"What year was Roblox originally released?","a":"2006","rank":12,"cefr":"B2"},
    {"q":"What is the term for buying special cosmetic items in Roblox with real money?","a":"microtransactions","rank":13,"cefr":"B2","alt":["in-game purchases"]},
    {"q":"What popular Roblox horror game involves piggy-masked enemies chasing players?","a":"Piggy","rank":14,"cefr":"B2"},
    {"q":"What annual live event does Roblox hold that brings players and creators together?","a":"RDC","rank":15,"cefr":"B2","alt":["Roblox Developers Conference"]}
  ],
  "Science": [
    {"q":"What planet do we live on?","a":"Earth","rank":1,"cefr":"A1"},
    {"q":"What gas do humans breathe in to survive?","a":"oxygen","rank":2,"cefr":"A1"},
    {"q":"What force pulls objects toward the Earth?","a":"gravity","rank":3,"cefr":"A1"},
    {"q":"What is the powerhouse of the cell, that produces energy?","a":"mitochondria","rank":4,"cefr":"A2"},
    {"q":"What do plants need, besides water and sunlight, to grow?","a":"carbon dioxide","rank":5,"cefr":"A2","alt":["CO2","soil/nutrients"]},
    {"q":"What is the process by which plants make food from sunlight called?","a":"photosynthesis","rank":6,"cefr":"A2"},
    {"q":"What is the boiling point of water in Celsius?","a":"100°C","rank":7,"cefr":"B1","alt":["100"]},
    {"q":"What planet is known as the Red Planet?","a":"Mars","rank":8,"cefr":"B1"},
    {"q":"What is the largest organ in the human body?","a":"skin","rank":9,"cefr":"B1"},
    {"q":"What do we call the layer of gases surrounding the Earth?","a":"the atmosphere","rank":10,"cefr":"B1","alt":["atmosphere"]},
    {"q":"What is the chemical formula for table salt?","a":"NaCl","rank":11,"cefr":"B2"},
    {"q":"What is the speed of light in a vacuum (approx.)?","a":"300,000 km/s","rank":12,"cefr":"B2","alt":["300000 km/s","186000 mi/s"]},
    {"q":"What is the name of the theory that explains how species change over time?","a":"evolution","rank":13,"cefr":"B2","alt":["theory of evolution"]},
    {"q":"What particle in an atom has a negative charge?","a":"electron","rank":14,"cefr":"B2"},
    {"q":"What is the study of the stars and universe called?","a":"astronomy","rank":15,"cefr":"B2"}
  ],
  "Simple Past": [
    {"q":"Fill in: I ___ TV last night. (watch)","a":"watched","rank":1,"cefr":"A1"},
    {"q":"What is the past tense of 'go'?","a":"went","rank":2,"cefr":"A1"},
    {"q":"What is the past tense of 'eat'?","a":"ate","rank":3,"cefr":"A1"},
    {"q":"Fill in: They ___ football yesterday. (play)","a":"played","rank":4,"cefr":"A1"},
    {"q":"Fill in: She ___ a cake for the party. (bake)","a":"baked","rank":5,"cefr":"A2"},
    {"q":"What is the past tense of 'buy'?","a":"bought","rank":6,"cefr":"A2"},
    {"q":"What is the past tense of 'speak'?","a":"spoke","rank":7,"cefr":"A2"},
    {"q":"Fill in: We ___ a great time at the beach. (have)","a":"had","rank":8,"cefr":"A2"},
    {"q":"Which is correct: 'Did she went?' or 'Did she go?'","a":"Did she go?","rank":9,"cefr":"B1"},
    {"q":"Make a negative in simple past: 'He went to the party.'","a":"He didn't go to the party.","rank":10,"cefr":"B1"},
    {"q":"Correct the sentence: 'I didn't saw that movie.'","a":"I didn't see that movie.","rank":11,"cefr":"B1"},
    {"q":"Transform to a simple past question: 'They finished the project.'","a":"Did they finish the project?","rank":12,"cefr":"B1"},
    {"q":"Fill in: The earthquake ___ at 3am. (occur)","a":"occurred","rank":13,"cefr":"B2"},
    {"q":"What is the past tense of 'lie' (to recline)?","a":"lay","rank":14,"cefr":"B2"},
    {"q":"Explain the difference between 'I ate' and 'I have eaten'.","a":"'ate' = specific past time; 'have eaten' connects to now","rank":15,"cefr":"B2"}
  ],
  "Simple Present": [
    {"q":"Fill in: She ___ to school every day. (go)","a":"goes","rank":1,"cefr":"A1"},
    {"q":"Fill in: They ___ football on Saturdays. (play)","a":"play","rank":2,"cefr":"A1"},
    {"q":"Fill in: He ___ coffee in the morning. (drink)","a":"drinks","rank":3,"cefr":"A1"},
    {"q":"Fill in: The cat ___ on the mat. (sit)","a":"sits","rank":4,"cefr":"A1"},
    {"q":"Fill in: The sun ___ in the east. (rise)","a":"rises","rank":5,"cefr":"A2"},
    {"q":"What auxiliary verb do we use to make a question with he/she/it?","a":"Does","rank":6,"cefr":"A2"},
    {"q":"Fill in: Water ___ at 100°C. (boil)","a":"boils","rank":7,"cefr":"A2"},
    {"q":"Correct the error: 'I goes to the store.'","a":"I go to the store.","rank":8,"cefr":"A2"},
    {"q":"Which is correct: 'Do they speaks English?' or 'Do they speak English?'","a":"Do they speak English?","rank":9,"cefr":"B1"},
    {"q":"Make a negative: 'She likes cats.'","a":"She doesn't like cats.","rank":10,"cefr":"B1"},
    {"q":"Identify the error: 'He don't understand the question.'","a":"'don't' should be 'doesn't'","rank":11,"cefr":"B1"},
    {"q":"Transform into a question: 'They work on Sundays.'","a":"Do they work on Sundays?","rank":12,"cefr":"B1"},
    {"q":"Fill in: The news ___ at 6pm every day. (start)","a":"starts","rank":13,"cefr":"B2"},
    {"q":"Give an example of simple present used for a scheduled future event.","a":"The train leaves at 8 tomorrow.","rank":14,"cefr":"B2","alt":["The bus arrives at noon tomorrow.","The movie starts at 7 tonight."]},
    {"q":"Why do we add -s or -es to the verb with he/she/it in simple present?","a":"the third-person singular rule","rank":15,"cefr":"B2"}
  ],
  "Spelling": [
    {"q":"Spell the plural of 'box'.","a":"boxes","rank":1,"cefr":"A1"},
    {"q":"Spell the -ing form of 'run'.","a":"running","rank":2,"cefr":"A1"},
    {"q":"Spell the past tense of 'stop'.","a":"stopped","rank":3,"cefr":"A1"},
    {"q":"Which is correct: 'recieve' or 'receive'?","a":"receive","rank":4,"cefr":"A2"},
    {"q":"Spell the plural of 'child'.","a":"children","rank":5,"cefr":"A2"},
    {"q":"Which is correct: 'occured' or 'occurred'?","a":"occurred","rank":6,"cefr":"A2"},
    {"q":"Which is correct: 'seperate' or 'separate'?","a":"separate","rank":7,"cefr":"B1"},
    {"q":"Spell the adverb form of 'true'.","a":"truly","rank":8,"cefr":"B1"},
    {"q":"Which is correct: 'definately' or 'definitely'?","a":"definitely","rank":9,"cefr":"B1"},
    {"q":"Spell the plural of 'shelf'.","a":"shelves","rank":10,"cefr":"B1"},
    {"q":"Which is correct: 'accomodate' or 'accommodate'?","a":"accommodate","rank":11,"cefr":"B2"},
    {"q":"Which is correct: 'embarass' or 'embarrass'?","a":"embarrass","rank":12,"cefr":"B2"},
    {"q":"Which is correct: 'neccessary' or 'necessary'?","a":"necessary","rank":13,"cefr":"B2"},
    {"q":"Which is correct: 'existance' or 'existence'?","a":"existence","rank":14,"cefr":"B2"},
    {"q":"Which is correct: 'concious' or 'conscious'?","a":"conscious","rank":15,"cefr":"B2"}
  ],
  "Stage Names": [
    {"q":"What is the stage name of the singer born Stefani Germanotta?","a":"Lady Gaga","rank":1,"cefr":"A1"},
    {"q":"What is the stage name of the singer born Robyn Fenty?","a":"Rihanna","rank":2,"cefr":"A1"},
    {"q":"What is the stage name of the rapper born Marshall Mathers?","a":"Eminem","rank":3,"cefr":"A1"},
    {"q":"What is the stage name of the singer born Katheryn Hudson?","a":"Katy Perry","rank":4,"cefr":"A2"},
    {"q":"What is the stage name of the rapper born Aubrey Graham?","a":"Drake","rank":5,"cefr":"A2"},
    {"q":"What is the stage name of the singer born Larissa de Macedo Machado?","a":"Anitta","rank":6,"cefr":"A2"},
    {"q":"What is the stage name of the singer born Onika Maraj?","a":"Nicki Minaj","rank":7,"cefr":"B1"},
    {"q":"What is the stage name of the rapper born Shawn Carter?","a":"Jay-Z","rank":8,"cefr":"B1"},
    {"q":"What is the stage name of the singer born Alecia Moore?","a":"Pink","rank":9,"cefr":"B1","alt":["P!nk"]},
    {"q":"What is the stage name of the musician born Stevland Judkins?","a":"Stevie Wonder","rank":10,"cefr":"B1"},
    {"q":"What is the stage name of the singer born Georgios Kyriacos Panayiotou?","a":"George Michael","rank":11,"cefr":"B2"},
    {"q":"What is the stage name of the rapper born Calvin Broadus?","a":"Snoop Dogg","rank":12,"cefr":"B2"},
    {"q":"What is the stage name of the singer born Robert Zimmerman?","a":"Bob Dylan","rank":13,"cefr":"B2"},
    {"q":"What is the stage name of the musician born Farrokh Bulsara?","a":"Freddie Mercury","rank":14,"cefr":"B2"},
    {"q":"What is the stage name of the rapper born O'Shea Jackson?","a":"Ice Cube","rank":15,"cefr":"B2"}
  ],
  "Stranger Things": [
    {"q":"What is the name of the town where Stranger Things takes place?","a":"Hawkins","rank":1,"cefr":"A1"},
    {"q":"What is the name of the girl with psychic powers?","a":"Eleven","rank":2,"cefr":"A1","alt":["El"]},
    {"q":"What alternate dimension is central to the show?","a":"the Upside Down","rank":3,"cefr":"A1","alt":["Upside Down"]},
    {"q":"What is the name of the boy who disappears in Season 1?","a":"Will Byers","rank":4,"cefr":"A2","alt":["Will"]},
    {"q":"What does Eleven love to eat, seen throughout the show?","a":"Eggo waffles","rank":5,"cefr":"A2","alt":["Eggos","waffles"]},
    {"q":"What is the name of the monster that first appears in Season 1?","a":"the Demogorgon","rank":6,"cefr":"A2","alt":["Demogorgon"]},
    {"q":"What is the name of the police chief in Hawkins?","a":"Jim Hopper","rank":7,"cefr":"B1","alt":["Hopper"]},
    {"q":"What is the name of Will's older brother?","a":"Jonathan Byers","rank":8,"cefr":"B1","alt":["Jonathan"]},
    {"q":"What government facility is connected to the Upside Down?","a":"Hawkins National Laboratory","rank":9,"cefr":"B1","alt":["Hawkins Lab"]},
    {"q":"What is the name of Mike's older sister?","a":"Nancy Wheeler","rank":10,"cefr":"B1","alt":["Nancy"]},
    {"q":"What number is tattooed on Eleven's wrist?","a":"011","rank":11,"cefr":"B2"},
    {"q":"What is the name of the shopping mall featured in Season 3?","a":"Starcourt Mall","rank":12,"cefr":"B2","alt":["Starcourt"]},
    {"q":"What creature controls the Demogorgons and other monsters in later seasons?","a":"the Mind Flayer","rank":13,"cefr":"B2","alt":["Mind Flayer"]},
    {"q":"What is the name of Joyce's kind boyfriend who works at RadioShack in Season 2?","a":"Bob Newby","rank":14,"cefr":"B2","alt":["Bob"]},
    {"q":"What Russian location becomes important in Season 4?","a":"Kamchatka","rank":15,"cefr":"B2","alt":["a Russian prison"]}
  ],
  "The Letter A": [
    {"q":"What do you call a red or green fruit that keeps the doctor away? (starts with A)","a":"apple","rank":1,"cefr":"A1"},
    {"q":"What flies in the sky and carries passengers? (starts with A)","a":"airplane","rank":2,"cefr":"A1","alt":["aeroplane"]},
    {"q":"What reptile has a long snout and lives in rivers and swamps? (starts with A)","a":"alligator","rank":3,"cefr":"A1"},
    {"q":"What do you call a large stadium where you watch sports or concerts? (starts with A)","a":"arena","rank":4,"cefr":"A2"},
    {"q":"What is the word for a person who designs buildings? (starts with A)","a":"architect","rank":5,"cefr":"A2"},
    {"q":"What word describes a feeling of worry or nervousness? (starts with A)","a":"anxiety","rank":6,"cefr":"A2"},
    {"q":"What is the word for a big group of ants living together, or a monkey with no tail? (starts with A)","a":"ape","rank":7,"cefr":"B1","alt":["colony"]},
    {"q":"What is the word for a formal agreement or partnership between countries? (starts with A)","a":"alliance","rank":8,"cefr":"B1"},
    {"q":"What do you call a scientist who studies ancient human history through digging up artifacts? (starts with A)","a":"archaeologist","rank":9,"cefr":"B1"},
    {"q":"What is a word meaning 'to change or adjust to new conditions'? (starts with A)","a":"adapt","rank":10,"cefr":"B1"},
    {"q":"What word means 'to succeed in doing something you were trying to do'? (starts with A)","a":"achieve","rank":11,"cefr":"B2","alt":["accomplish"]},
    {"q":"What is the word for a formal, official announcement? (starts with A)","a":"announcement","rank":12,"cefr":"B2","alt":["proclamation"]},
    {"q":"What word describes something that can be heard? (starts with A)","a":"audible","rank":13,"cefr":"B2"},
    {"q":"What is a formal word meaning 'to give official permission for something'? (starts with A)","a":"authorize","rank":14,"cefr":"B2"},
    {"q":"What word means 'existing since a very early time'? (starts with A)","a":"ancient","rank":15,"cefr":"B2"}
  ],
  "Vegetables": [
    {"q":"What orange vegetable is good for your eyes?","a":"carrot","rank":1,"cefr":"A1"},
    {"q":"What round red vegetable is used in salads and sauces (technically a fruit)?","a":"tomato","rank":2,"cefr":"A1"},
    {"q":"What green vegetable looks like a small tree?","a":"broccoli","rank":3,"cefr":"A1"},
    {"q":"What white vegetable makes people cry when you cut it?","a":"onion","rank":4,"cefr":"A2"},
    {"q":"What long green vegetable is mostly water and used in salads?","a":"cucumber","rank":5,"cefr":"A2"},
    {"q":"What vegetable is grown underground and is fried to make chips/fries?","a":"potato","rank":6,"cefr":"A2"},
    {"q":"What leafy green vegetable is used in Caesar salads?","a":"lettuce","rank":7,"cefr":"B1"},
    {"q":"What purple vegetable is used in Italian dishes like parmigiana?","a":"eggplant","rank":8,"cefr":"B1","alt":["aubergine"]},
    {"q":"What vegetable, related to cabbage, has small green florets similar to broccoli?","a":"Brussels sprout","rank":9,"cefr":"B1","alt":["Brussels sprouts"]},
    {"q":"What root vegetable is red or purple and used to make borscht soup?","a":"beet","rank":10,"cefr":"B1","alt":["beetroot"]},
    {"q":"What starchy root vegetable, called 'mandioca' in Brazil, is used to make farofa?","a":"cassava","rank":11,"cefr":"B2","alt":["manioc","yuca"]},
    {"q":"What vegetable is technically a fungus, not a plant?","a":"mushroom","rank":12,"cefr":"B2"},
    {"q":"What leafy vegetable is Popeye famous for eating for strength?","a":"spinach","rank":13,"cefr":"B2"},
    {"q":"What vegetable is the main ingredient in traditional Halloween carving?","a":"pumpkin","rank":14,"cefr":"B2"},
    {"q":"What vegetable family includes broccoli, cauliflower, and cabbage?","a":"brassica","rank":15,"cefr":"B2","alt":["cruciferous vegetables"]}
  ],
  "World Capitals": [
    {"q":"What is the capital of France?","a":"Paris","rank":1,"cefr":"A1"},
    {"q":"What is the capital of the United Kingdom?","a":"London","rank":2,"cefr":"A1"},
    {"q":"What is the capital of the USA?","a":"Washington, D.C.","rank":3,"cefr":"A1","alt":["Washington DC","Washington"]},
    {"q":"What is the capital of Japan?","a":"Tokyo","rank":4,"cefr":"A2"},
    {"q":"What is the capital of Italy?","a":"Rome","rank":5,"cefr":"A2"},
    {"q":"What is the capital of Germany?","a":"Berlin","rank":6,"cefr":"A2"},
    {"q":"What is the capital of Canada?","a":"Ottawa","rank":7,"cefr":"B1"},
    {"q":"What is the capital of Egypt?","a":"Cairo","rank":8,"cefr":"B1"},
    {"q":"What is the capital of Russia?","a":"Moscow","rank":9,"cefr":"B1"},
    {"q":"What is the capital of Argentina?","a":"Buenos Aires","rank":10,"cefr":"B1"},
    {"q":"What is the capital of South Korea?","a":"Seoul","rank":11,"cefr":"B1"},
    {"q":"What is the capital of Turkey?","a":"Ankara","rank":12,"cefr":"B2"},
    {"q":"What is the capital of South Africa? (one accepted answer is enough)","a":"Pretoria","rank":13,"cefr":"B2","alt":["Cape Town","Bloemfontein"]},
    {"q":"What is the capital of Switzerland?","a":"Bern","rank":14,"cefr":"B2"},
    {"q":"What is the capital of Kazakhstan?","a":"Astana","rank":15,"cefr":"B2"}
  ]
};
var bank = { categories: categories, groups: groups };
root.JEOPARDY_BANK = bank;
if (typeof module !== 'undefined' && module.exports) module.exports = bank;
})(typeof window !== 'undefined' ? window : globalThis);
