// triviaData.js
// Each category: { label, aliases, items }
// aliases: normalized answer name → accepted alternates (exact match only)
// Add new categories freely — the game loads all keys automatically.

const triviaData = {

  largestCountries: {
    label: "Largest Countries by Area",
    aliases: {
      "united states":          ["us", "usa", "united states of america", "america"],
      "democratic republic of congo": ["drc", "congo", "dr congo", "droc"],
      "saudi arabia":           ["saudi"],
    },
    items: [
      { rank: 1,  name: "Russia",                detail: "17,098,242 km²" },
      { rank: 2,  name: "Canada",                detail: "9,984,670 km²" },
      { rank: 3,  name: "United States",         detail: "9,833,517 km²" },
      { rank: 4,  name: "China",                 detail: "9,596,960 km²" },
      { rank: 5,  name: "Brazil",                detail: "8,515,767 km²" },
      { rank: 6,  name: "Australia",             detail: "7,692,024 km²" },
      { rank: 7,  name: "India",                 detail: "3,287,263 km²" },
      { rank: 8,  name: "Argentina",             detail: "2,780,400 km²" },
      { rank: 9,  name: "Kazakhstan",            detail: "2,724,900 km²" },
      { rank: 10, name: "Algeria",               detail: "2,381,741 km²" },
      { rank: 11, name: "Democratic Republic of Congo", detail: "2,344,858 km²" },
      { rank: 12, name: "Greenland",             detail: "2,166,086 km²" },
      { rank: 13, name: "Saudi Arabia",          detail: "2,149,690 km²" },
      { rank: 14, name: "Mexico",                detail: "1,964,375 km²" },
      { rank: 15, name: "Indonesia",             detail: "1,904,569 km²" },
      { rank: 16, name: "Sudan",                 detail: "1,861,484 km²" },
      { rank: 17, name: "Libya",                 detail: "1,759,540 km²" },
      { rank: 18, name: "Iran",                  detail: "1,648,195 km²" },
      { rank: 19, name: "Mongolia",              detail: "1,564,116 km²" },
      { rank: 20, name: "Peru",                  detail: "1,285,216 km²" },
    ],
  },

  highestGrossingMovies: {
    label: "Highest-Grossing Movies of All Time",
    aliases: {
      "avengers endgame":       ["endgame", "avengers end game"],
      "spider-man no way home": ["no way home", "spiderman no way home"],
      "super mario bros movie": ["mario movie", "mario bros movie", "super mario movie"],
      "deadpool and wolverine": ["deadpool wolverine", "deadpool 3"],
      "harry potter deathly hallows": ["deathly hallows", "harry potter"],
      "star wars the force awakens": ["force awakens", "star wars 7", "star wars vii"],
      "top gun maverick":       ["maverick", "top gun 2"],
      "the lion king":          ["lion king"],
      "inside out 2":           ["inside out"],
      "jurassic world":         ["jurassic park"],
      "black panther":          ["wakanda"],
      "the dark knight rises":  ["dark knight", "batman dark knight"],
      "minions":                ["despicable me", "minion"],
      "transformers age of extinction": ["transformers", "age of extinction"],
      "furious 7":              ["fast and furious", "fast furious", "fast 7"],
      "frozen ii":              ["frozen 2", "frozen"],
    },
    items: [
      { rank: 1,  name: "Avatar",                        detail: "$2.923B (2009)" },
      { rank: 2,  name: "Avengers Endgame",              detail: "$2.799B (2019)" },
      { rank: 3,  name: "Titanic",                       detail: "$2.264B (1997)" },
      { rank: 4,  name: "Star Wars The Force Awakens",   detail: "$2.069B (2015)" },
      { rank: 5,  name: "Spider-Man No Way Home",        detail: "$1.921B (2021)" },
      { rank: 6,  name: "Inside Out 2",                  detail: "$1.698B (2024)" },
      { rank: 7,  name: "Jurassic World",                detail: "$1.672B (2015)" },
      { rank: 8,  name: "The Lion King",                 detail: "$1.663B (2019)" },
      { rank: 9,  name: "Furious 7",                     detail: "$1.516B (2015)" },
      { rank: 10, name: "Top Gun Maverick",              detail: "$1.494B (2022)" },
      { rank: 11, name: "Frozen II",                     detail: "$1.453B (2019)" },
      { rank: 12, name: "Barbie",                        detail: "$1.446B (2023)" },
      { rank: 13, name: "Super Mario Bros Movie",        detail: "$1.362B (2023)" },
      { rank: 14, name: "Black Panther",                 detail: "$1.349B (2018)" },
      { rank: 15, name: "Harry Potter Deathly Hallows",  detail: "$1.342B (2011)" },
      { rank: 16, name: "Deadpool and Wolverine",        detail: "$1.338B (2024)" },
      { rank: 17, name: "The Dark Knight Rises",         detail: "$1.085B (2012)" },
      { rank: 18, name: "Joker",                         detail: "$1.079B (2019)" },
      { rank: 19, name: "Minions",                       detail: "$1.159B (2015)" },
      { rank: 20, name: "Transformers Age of Extinction", detail: "$1.104B (2014)" },
    ],
  },

  mostSpokenLanguages: {
    label: "Most Spoken Languages",
    aliases: {
      "mandarin":               ["mandarin chinese", "chinese"],
      "cantonese":              ["yue chinese", "yue"],
      "nigerian pidgin":        ["pidgin"],
    },
    items: [
      { rank: 1,  name: "English",     detail: "~1.5B speakers" },
      { rank: 2,  name: "Mandarin",    detail: "~1.1B speakers" },
      { rank: 3,  name: "Hindi",       detail: "~609M speakers" },
      { rank: 4,  name: "Spanish",     detail: "~560M speakers" },
      { rank: 5,  name: "French",      detail: "~310M speakers" },
      { rank: 6,  name: "Arabic",      detail: "~274M speakers" },
      { rank: 7,  name: "Bengali",     detail: "~272M speakers" },
      { rank: 8,  name: "Portuguese",  detail: "~264M speakers" },
      { rank: 9,  name: "Russian",     detail: "~258M speakers" },
      { rank: 10, name: "Urdu",        detail: "~232M speakers" },
      { rank: 11, name: "Indonesian",  detail: "~199M speakers" },
      { rank: 12, name: "German",      detail: "~135M speakers" },
      { rank: 13, name: "Japanese",    detail: "~126M speakers" },
      { rank: 14, name: "Nigerian Pidgin", detail: "~121M speakers" },
      { rank: 15, name: "Marathi",     detail: "~99M speakers" },
      { rank: 16, name: "Telugu",      detail: "~96M speakers" },
      { rank: 17, name: "Turkish",     detail: "~88M speakers" },
      { rank: 18, name: "Tamil",       detail: "~87M speakers" },
      { rank: 19, name: "Cantonese",   detail: "~86M speakers" },
      { rank: 20, name: "Vietnamese",  detail: "~85M speakers" },
    ],
  },

  famousInventors: {
    label: "Famous Inventors",
    aliases: {
      "wright brothers":        ["wright", "orville wright", "wilbur wright"],
      "johannes gutenberg":     ["gutenberg"],
      "alexander graham bell":  ["graham bell", "bell"],
      "tim berners-lee":        ["berners lee", "berners-lee"],
      "guglielmo marconi":      ["marconi"],
      "alexander fleming":      ["fleming"],
      "charles babbage":        ["babbage"],
      "thomas edison":          ["edison"],
      "nikola tesla":           ["tesla"],
      "leonardo da vinci":      ["da vinci", "davinci", "vinci"],
      "marie curie":            ["curie"],
      "galileo galilei":        ["galileo"],
      "isaac newton":           ["newton"],
      "louis pasteur":          ["pasteur"],
      "benjamin franklin":      ["franklin"],
      "ada lovelace":           ["lovelace"],
      "james watt":             ["watt"],
      "karl benz":              ["benz"],
      "steve jobs":             ["jobs"],
    },
    items: [
      { rank: 1,  name: "Thomas Edison",       detail: "Light bulb, phonograph" },
      { rank: 2,  name: "Nikola Tesla",        detail: "AC electrical system, radio" },
      { rank: 3,  name: "Leonardo da Vinci",   detail: "Aerial screw, armored vehicle" },
      { rank: 4,  name: "Alexander Graham Bell", detail: "Telephone (1876)" },
      { rank: 5,  name: "Wright Brothers",     detail: "Powered airplane (1903)" },
      { rank: 6,  name: "Johannes Gutenberg",  detail: "Printing press (~1440)" },
      { rank: 7,  name: "James Watt",          detail: "Steam engine (1769)" },
      { rank: 8,  name: "Marie Curie",         detail: "Radioactive element isolation" },
      { rank: 9,  name: "Tim Berners-Lee",     detail: "World Wide Web (1989)" },
      { rank: 10, name: "Galileo Galilei",     detail: "Improved telescope" },
      { rank: 11, name: "Isaac Newton",        detail: "Reflecting telescope, calculus" },
      { rank: 12, name: "Louis Pasteur",       detail: "Pasteurization, vaccines" },
      { rank: 13, name: "Benjamin Franklin",   detail: "Lightning rod, bifocals" },
      { rank: 14, name: "Karl Benz",           detail: "First automobile (1885)" },
      { rank: 15, name: "Guglielmo Marconi",   detail: "Radio communication (1895)" },
      { rank: 16, name: "Charles Babbage",     detail: "First mechanical computer" },
      { rank: 17, name: "Archimedes",          detail: "Screw pump, compound pulley" },
      { rank: 18, name: "Alexander Fleming",   detail: "Penicillin (1928)" },
      { rank: 19, name: "Ada Lovelace",        detail: "First algorithm (1843)" },
      { rank: 20, name: "Steve Jobs",          detail: "Personal computer, iPhone" },
    ],
  },

  olympicMedalsByCountry: {
    label: "Countries with Most Olympic Medals",
    aliases: {
      "united states":  ["us", "usa", "america"],
      "soviet union":   ["ussr"],
      "great britain":  ["uk", "united kingdom", "britain", "england"],
      "east germany":   ["ddr"],
    },
    items: [
      { rank: 1,  name: "United States",  detail: "2,638 total medals" },
      { rank: 2,  name: "Soviet Union",   detail: "1,122 total medals" },
      { rank: 3,  name: "Great Britain",  detail: "948 total medals" },
      { rank: 4,  name: "Germany",        detail: "937 total medals" },
      { rank: 5,  name: "France",         detail: "843 total medals" },
      { rank: 6,  name: "China",          detail: "696 total medals" },
      { rank: 7,  name: "Italy",          detail: "686 total medals" },
      { rank: 8,  name: "Australia",      detail: "668 total medals" },
      { rank: 9,  name: "Hungary",        detail: "528 total medals" },
      { rank: 10, name: "Japan",          detail: "521 total medals" },
      { rank: 11, name: "East Germany",   detail: "519 total medals" },
      { rank: 12, name: "Russia",         detail: "518 total medals" },
      { rank: 13, name: "Sweden",         detail: "493 total medals" },
      { rank: 14, name: "Netherlands",    detail: "441 total medals" },
      { rank: 15, name: "Norway",         detail: "405 total medals" },
      { rank: 16, name: "Romania",        detail: "307 total medals" },
      { rank: 17, name: "Canada",         detail: "299 total medals" },
      { rank: 18, name: "South Korea",    detail: "266 total medals" },
      { rank: 19, name: "Cuba",           detail: "226 total medals" },
      { rank: 20, name: "Finland",        detail: "306 total medals" },
    ],
  },

  mostDownloadedApps: {
    label: "Most Downloaded Apps",
    aliases: {
      "twitter":        ["x", "twitter x"],
      "candy crush":    ["candy crush saga"],
    },
    items: [
      { rank: 1,  name: "TikTok",        detail: "~4.7B downloads" },
      { rank: 2,  name: "Instagram",     detail: "~3.8B downloads" },
      { rank: 3,  name: "Facebook",      detail: "~3.7B downloads" },
      { rank: 4,  name: "WhatsApp",      detail: "~3.4B downloads" },
      { rank: 5,  name: "Messenger",     detail: "~3.1B downloads" },
      { rank: 6,  name: "Telegram",      detail: "~2.3B downloads" },
      { rank: 7,  name: "Snapchat",      detail: "~2.2B downloads" },
      { rank: 8,  name: "YouTube",       detail: "~2.0B downloads" },
      { rank: 9,  name: "Twitter",       detail: "~1.5B downloads" },
      { rank: 10, name: "Spotify",       detail: "~1.4B downloads" },
      { rank: 11, name: "Zoom",          detail: "~1.3B downloads" },
      { rank: 12, name: "Netflix",       detail: "~1.2B downloads" },
      { rank: 13, name: "Amazon",        detail: "~1.1B downloads" },
      { rank: 14, name: "Uber",          detail: "~950M downloads" },
      { rank: 15, name: "Google Maps",   detail: "~900M downloads" },
      { rank: 16, name: "Gmail",         detail: "~850M downloads" },
      { rank: 17, name: "LinkedIn",      detail: "~800M downloads" },
      { rank: 18, name: "Pinterest",     detail: "~750M downloads" },
      { rank: 19, name: "Candy Crush",   detail: "~700M downloads" },
      { rank: 20, name: "Shein",         detail: "~650M downloads" },
    ],
  },

  mostVisitedWebsites: {
    label: "Most Visited Websites",
    aliases: {
      "google":         ["google.com"],
      "youtube":        ["youtube.com"],
      "facebook":       ["facebook.com"],
      "twitter":        ["x", "twitter x"],
      "wikipedia":      ["wiki"],
      "duckduckgo":     ["ddg"],
      "new york times": ["nyt", "ny times"],
      "outlook":        ["live.com", "hotmail"],
    },
    items: [
      { rank: 1,  name: "Google",        detail: "~85B monthly visits" },
      { rank: 2,  name: "YouTube",       detail: "~33B monthly visits" },
      { rank: 3,  name: "Facebook",      detail: "~18B monthly visits" },
      { rank: 4,  name: "Instagram",     detail: "~7.5B monthly visits" },
      { rank: 5,  name: "Wikipedia",     detail: "~5.5B monthly visits" },
      { rank: 6,  name: "Twitter",       detail: "~5.3B monthly visits" },
      { rank: 7,  name: "Reddit",        detail: "~4.8B monthly visits" },
      { rank: 8,  name: "Yahoo",         detail: "~4.2B monthly visits" },
      { rank: 9,  name: "WhatsApp",      detail: "~4.0B monthly visits" },
      { rank: 10, name: "Amazon",        detail: "~3.7B monthly visits" },
      { rank: 11, name: "TikTok",        detail: "~3.5B monthly visits" },
      { rank: 12, name: "Bing",          detail: "~3.3B monthly visits" },
      { rank: 13, name: "Netflix",       detail: "~2.1B monthly visits" },
      { rank: 14, name: "Outlook",       detail: "~2.0B monthly visits" },
      { rank: 15, name: "LinkedIn",      detail: "~1.9B monthly visits" },
      { rank: 16, name: "ESPN",           detail: "~1.8B monthly visits" },
      { rank: 17, name: "DuckDuckGo",    detail: "~1.7B monthly visits" },
      { rank: 18, name: "New York Times", detail: "~1.3B monthly visits" },
      { rank: 19, name: "CNN",           detail: "~1.2B monthly visits" },
      { rank: 20, name: "eBay",          detail: "~1.1B monthly visits" },
    ],
  },

  mostPopularFastFoodChains: {
    label: "Most Popular Fast Food Chains",
    aliases: {
      "mcdonald's":     ["mcdonalds", "mcd", "mickey ds", "mickey d"],
      "dunkin":         ["dunkin donuts", "dunkin'"],
      "hardee's":       ["hardees", "carls jr", "carl's jr"],
      "five guys":      ["five guys burgers"],
      "taco bell":      ["taco"],
      "baskin-robbins": ["baskin robbins"],
      "papa john's":    ["papa johns"],
      "little caesars": ["little caesar"],
      "dairy queen":    ["dq"],
      "burger king":    ["bk"],
      "pizza hut":      ["pizza"],
      "wendy's":        ["wendys"],
      "tim hortons":    ["tim horton", "timmies"],
    },
    items: [
      { rank: 1,  name: "McDonald's",           detail: "~40,000 locations" },
      { rank: 2,  name: "Subway",               detail: "~37,000 locations" },
      { rank: 3,  name: "Starbucks",            detail: "~35,000 locations" },
      { rank: 4,  name: "KFC",                  detail: "~27,000 locations" },
      { rank: 5,  name: "Domino's",             detail: "~19,000 locations" },
      { rank: 6,  name: "Burger King",          detail: "~18,000 locations" },
      { rank: 7,  name: "Pizza Hut",            detail: "~18,000 locations" },
      { rank: 8,  name: "Dunkin",               detail: "~13,000 locations" },
      { rank: 9,  name: "Baskin-Robbins",       detail: "~8,000 locations" },
      { rank: 10, name: "Taco Bell",            detail: "~8,000 locations" },
      { rank: 11, name: "Dairy Queen",          detail: "~7,000 locations" },
      { rank: 12, name: "Wendy's",              detail: "~6,700 locations" },
      { rank: 13, name: "Papa John's",          detail: "~5,900 locations" },
      { rank: 14, name: "Tim Hortons",          detail: "~5,700 locations" },
      { rank: 15, name: "Little Caesars",       detail: "~4,400 locations" },
      { rank: 16, name: "Hardee's",             detail: "~3,800 locations" },
      { rank: 17, name: "Popeyes",              detail: "~3,700 locations" },
      { rank: 18, name: "Chick-fil-A",          detail: "~3,000 locations" },
      { rank: 19, name: "Panda Express",        detail: "~2,400 locations" },
      { rank: 20, name: "Five Guys",            detail: "~1,700 locations" },
    ],
  },

  countriesMostCoffee: {
    label: "Countries That Consume the Most Coffee",
    aliases: {
      "united states": ["us", "usa", "america"],
      "bosnia":        ["bosnia and herzegovina", "bosnia herzegovina"],
    },
    items: [
      { rank: 1,  name: "Finland",       detail: "12 kg/capita/year" },
      { rank: 2,  name: "Norway",        detail: "9.9 kg/capita/year" },
      { rank: 3,  name: "Iceland",       detail: "9.0 kg/capita/year" },
      { rank: 4,  name: "Denmark",       detail: "8.7 kg/capita/year" },
      { rank: 5,  name: "Netherlands",   detail: "8.4 kg/capita/year" },
      { rank: 6,  name: "Sweden",        detail: "8.2 kg/capita/year" },
      { rank: 7,  name: "Switzerland",   detail: "7.9 kg/capita/year" },
      { rank: 8,  name: "Belgium",       detail: "6.8 kg/capita/year" },
      { rank: 9,  name: "Luxembourg",    detail: "6.5 kg/capita/year" },
      { rank: 10, name: "Canada",        detail: "6.2 kg/capita/year" },
      { rank: 11, name: "Bosnia",        detail: "6.1 kg/capita/year" },
      { rank: 12, name: "Austria",       detail: "5.7 kg/capita/year" },
      { rank: 13, name: "Italy",         detail: "5.6 kg/capita/year" },
      { rank: 14, name: "Brazil",        detail: "5.5 kg/capita/year" },
      { rank: 15, name: "Germany",       detail: "5.4 kg/capita/year" },
      { rank: 16, name: "Greece",        detail: "5.2 kg/capita/year" },
      { rank: 17, name: "France",        detail: "5.0 kg/capita/year" },
      { rank: 18, name: "United States", detail: "4.5 kg/capita/year" },
      { rank: 19, name: "Spain",         detail: "4.3 kg/capita/year" },
      { rank: 20, name: "Portugal",      detail: "4.1 kg/capita/year" },
    ],
  },

  topTouristDestinations: {
    label: "Top Tourist Destinations",
    aliases: {
      "united states":  ["us", "usa", "america"],
      "united kingdom": ["uk", "britain", "england"],
      "uae":            ["united arab emirates", "emirates", "dubai"],
      "saudi arabia":   ["saudi"],
    },
    items: [
      { rank: 1,  name: "France",         detail: "~100M arrivals/year" },
      { rank: 2,  name: "Spain",          detail: "~85M arrivals/year" },
      { rank: 3,  name: "United States",  detail: "~79M arrivals/year" },
      { rank: 4,  name: "Turkey",         detail: "~56M arrivals/year" },
      { rank: 5,  name: "Italy",          detail: "~57M arrivals/year" },
      { rank: 6,  name: "Mexico",         detail: "~45M arrivals/year" },
      { rank: 7,  name: "Germany",        detail: "~40M arrivals/year" },
      { rank: 8,  name: "United Kingdom", detail: "~39M arrivals/year" },
      { rank: 9,  name: "Greece",         detail: "~33M arrivals/year" },
      { rank: 10, name: "Austria",        detail: "~31M arrivals/year" },
      { rank: 11, name: "Thailand",       detail: "~30M arrivals/year" },
      { rank: 12, name: "China",          detail: "~28M arrivals/year" },
      { rank: 13, name: "Japan",          detail: "~25M arrivals/year" },
      { rank: 14, name: "Canada",         detail: "~22M arrivals/year" },
      { rank: 15, name: "Poland",         detail: "~19M arrivals/year" },
      { rank: 16, name: "Netherlands",    detail: "~18M arrivals/year" },
      { rank: 17, name: "Saudi Arabia",   detail: "~17M arrivals/year" },
      { rank: 18, name: "Portugal",       detail: "~16M arrivals/year" },
      { rank: 19, name: "UAE",            detail: "~14.4M arrivals/year" },
      { rank: 20, name: "India",          detail: "~14M arrivals/year" },
    ],
  },

  mostStreamedArtistsSpotify: {
    label: "Most Streamed Artists on Spotify",
    aliases: {
      "the weeknd":     ["weeknd"],
      "ed sheeran":     ["sheeran"],
      "bad bunny":      ["bad bunny"],
      "taylor swift":   ["swift", "tay tay"],
      "ariana grande":  ["ariana", "ari"],
      "justin bieber":  ["bieber"],
      "post malone":    ["posty"],
      "billie eilish":  ["billie"],
      "bruno mars":         ["mars"],
    },
    items: [
      { rank: 1,  name: "The Weeknd",      detail: "~120B+ streams" },
      { rank: 2,  name: "Ed Sheeran",      detail: "~110B+ streams" },
      { rank: 3,  name: "Bad Bunny",       detail: "~100B+ streams" },
      { rank: 4,  name: "Taylor Swift",    detail: "~95B+ streams" },
      { rank: 5,  name: "Drake",           detail: "~90B+ streams" },
      { rank: 6,  name: "Ariana Grande",   detail: "~85B+ streams" },
      { rank: 7,  name: "Eminem",          detail: "~80B+ streams" },
      { rank: 8,  name: "Justin Bieber",   detail: "~75B+ streams" },
      { rank: 9,  name: "Post Malone",     detail: "~70B+ streams" },
      { rank: 10, name: "Rihanna",         detail: "~68B+ streams" },
      { rank: 11, name: "BTS",             detail: "~65B+ streams" },
      { rank: 12, name: "Billie Eilish",   detail: "~62B+ streams" },
      { rank: 13, name: "Dua Lipa",        detail: "~60B+ streams" },
      { rank: 14, name: "Coldplay",        detail: "~58B+ streams" },
      { rank: 15, name: "Harry Styles",    detail: "~55B+ streams" },
      { rank: 16, name: "The Chainsmokers", detail: "~53B+ streams" },
      { rank: 17, name: "Bruno Mars",       detail: "~50B+ streams" },
      { rank: 18, name: "Olivia Rodrigo",  detail: "~48B+ streams" },
      { rank: 19, name: "Karol G",         detail: "~45B+ streams" },
      { rank: 20, name: "Peso Pluma",      detail: "~42B+ streams" },
    ],
  },

  countriesLargestArmies: {
    label: "Countries with the Largest Armies",
    aliases: {
      "united states":  ["us", "usa", "america"],
      "north korea":    ["dprk"],
      "south korea":    ["korea"],
      "saudi arabia":   ["saudi"],
    },
    items: [
      { rank: 1,  name: "China",           detail: "2,000,000 active" },
      { rank: 2,  name: "India",           detail: "1,455,550 active" },
      { rank: 3,  name: "United States",   detail: "1,395,350 active" },
      { rank: 4,  name: "North Korea",     detail: "1,280,000 active" },
      { rank: 5,  name: "Russia",          detail: "900,000 active" },
      { rank: 6,  name: "Pakistan",        detail: "654,000 active" },
      { rank: 7,  name: "Iran",            detail: "610,000 active" },
      { rank: 8,  name: "South Korea",     detail: "555,000 active" },
      { rank: 9,  name: "Vietnam",         detail: "482,000 active" },
      { rank: 10, name: "Egypt",           detail: "438,500 active" },
      { rank: 11, name: "Myanmar",         detail: "406,000 active" },
      { rank: 12, name: "Indonesia",       detail: "395,000 active" },
      { rank: 13, name: "Brazil",          detail: "366,500 active" },
      { rank: 14, name: "Thailand",        detail: "361,000 active" },
      { rank: 15, name: "Turkey",          detail: "355,200 active" },
      { rank: 16, name: "Mexico",          detail: "277,150 active" },
      { rank: 17, name: "Saudi Arabia",    detail: "257,000 active" },
      { rank: 18, name: "Japan",           detail: "247,150 active" },
      { rank: 19, name: "Ukraine",         detail: "~200,000+ active" },
      { rank: 20, name: "Ethiopia",        detail: "138,000 active" },
    ],
  },

  mostCommonDogBreeds: {
    label: "Most Common Dog Breeds",
    aliases: {
      "french bulldog":         ["frenchie", "french bull"],
      "labrador retriever":     ["labrador", "lab"],
      "golden retriever":       ["golden", "goldie"],
      "german shepherd":        ["gsd", "alsatian"],
      "corgi":                  ["welsh corgi", "pembroke corgi"],
      "australian shepherd":    ["aussie"],
      "yorkshire terrier":      ["yorkie"],
      "cavalier king charles spaniel": ["cavalier", "king charles"],
      "miniature schnauzer":    ["schnauzer"],
      "siberian husky":         ["husky"],
      "doberman":               ["dobermann"],
      "border collie":          ["border"],
      "german shorthaired pointer": ["gsp"],
    },
    items: [
      { rank: 1,  name: "French Bulldog",       detail: "Most popular in US, UK, AU" },
      { rank: 2,  name: "Labrador Retriever",   detail: "Top breed for 31 years in US" },
      { rank: 3,  name: "Golden Retriever",     detail: "Consistently top 5 worldwide" },
      { rank: 4,  name: "German Shepherd",      detail: "Most popular working dog" },
      { rank: 5,  name: "Poodle",               detail: "Top 5 in Western countries" },
      { rank: 6,  name: "Bulldog",              detail: "Top 10 in US and UK" },
      { rank: 7,  name: "Rottweiler",           detail: "Top 10 globally" },
      { rank: 8,  name: "Beagle",               detail: "Top 10 globally" },
      { rank: 9,  name: "Dachshund",            detail: "Popular in Germany and US" },
      { rank: 10, name: "German Shorthaired Pointer", detail: "Growing popularity in US" },
      { rank: 11, name: "Corgi",                detail: "Top 15 in UK and US" },
      { rank: 12, name: "Australian Shepherd",  detail: "Popular in US and Australia" },
      { rank: 13, name: "Yorkshire Terrier",    detail: "Popular worldwide" },
      { rank: 14, name: "Boxer",                detail: "Top 15 in multiple countries" },
      { rank: 15, name: "Cavalier King Charles Spaniel", detail: "Top 20 in UK and US" },
      { rank: 16, name: "Great Dane",           detail: "Growing in North America" },
      { rank: 17, name: "Miniature Schnauzer",  detail: "Popular in Germany and US" },
      { rank: 18, name: "Siberian Husky",       detail: "Popular globally" },
      { rank: 19, name: "Doberman",             detail: "Popular in US and Europe" },
      { rank: 20, name: "Border Collie",        detail: "Most popular herding breed" },
    ],
  },

  mostPlayedOnlineGames: {
    label: "Most Played Online Games (Peak Concurrent Players)",
    aliases: {
      "counter-strike":     ["cs", "csgo", "cs2", "counter strike"],
      "league of legends":  ["lol", "league"],
      "genshin impact":     ["genshin"],
      "pubg":               ["playerunknowns battlegrounds", "battlegrounds"],
      "among us":           ["among"],
      "dota 2":             ["dota"],
      "gta online":         ["gta", "grand theft auto"],
      "apex legends":       ["apex"],
      "black myth wukong":  ["black myth", "wukong"],
      "palworld":           ["pal world"],
      "lost ark":           ["lostark"],
      "new world":          ["amazon new world"],
      "path of exile 2":    ["poe2", "poe 2", "path of exile"],
      "cyberpunk 2077":     ["cyberpunk"],
      "elden ring":         ["eldenring"],
      "hogwarts legacy":    ["hogwarts"],
    },
    items: [
      { rank: 1,  name: "Fortnite",            detail: "14.3M peak concurrent (Nov 2024)" },
      { rank: 2,  name: "Roblox",              detail: "~4.5M peak concurrent (2025)" },
      { rank: 3,  name: "PUBG",               detail: "3.24M peak concurrent (Jan 2018, Steam)" },
      { rank: 4,  name: "Black Myth Wukong",   detail: "2.4M peak concurrent (Aug 2024, Steam)" },
      { rank: 5,  name: "Palworld",            detail: "2.1M peak concurrent (Jan 2024, Steam)" },
      { rank: 6,  name: "Counter-Strike",      detail: "1.86M peak concurrent (Apr 2025, Steam)" },
      { rank: 7,  name: "Lost Ark",            detail: "1.32M peak concurrent (Feb 2022, Steam)" },
      { rank: 8,  name: "Minecraft",           detail: "~1.3M concurrent (est. 2025)" },
      { rank: 9,  name: "Dota 2",             detail: "1.29M peak concurrent (Mar 2016, Steam)" },
      { rank: 10, name: "League of Legends",   detail: "~1M peak concurrent (est. 2019)" },
      { rank: 11, name: "Cyberpunk 2077",      detail: "1.05M peak concurrent (Dec 2020, Steam)" },
      { rank: 12, name: "Elden Ring",          detail: "953K peak concurrent (Feb 2022, Steam)" },
      { rank: 13, name: "New World",           detail: "913K peak concurrent (Sep 2021, Steam)" },
      { rank: 14, name: "Hogwarts Legacy",     detail: "879K peak concurrent (Feb 2023, Steam)" },
      { rank: 15, name: "Among Us",            detail: "~600K peak concurrent (Sep 2020)" },
      { rank: 16, name: "Path of Exile 2",     detail: "577K peak concurrent (Dec 2024, Steam)" },
      { rank: 17, name: "Valheim",             detail: "502K peak concurrent (Feb 2021, Steam)" },
      { rank: 18, name: "GTA Online",          detail: "~364K peak concurrent (Steam)" },
      { rank: 19, name: "Apex Legends",        detail: "~300K peak concurrent (Steam est.)" },
      { rank: 20, name: "Genshin Impact",      detail: "~300K peak concurrent (PC est.)" },
    ],
  },

  mostCommonVerbsEnglish: {
    label: "Most Common Verbs in English",
    aliases: {},
    items: [
      { rank: 1,  name: "be",     detail: "Most frequent verb in English" },
      { rank: 2,  name: "have",   detail: "Possession and auxiliary" },
      { rank: 3,  name: "do",     detail: "Action and auxiliary" },
      { rank: 4,  name: "say",    detail: "Speech and reporting" },
      { rank: 5,  name: "get",    detail: "Receive, become, arrive" },
      { rank: 6,  name: "make",   detail: "Create or cause" },
      { rank: 7,  name: "go",     detail: "Movement and change" },
      { rank: 8,  name: "know",   detail: "Knowledge and familiarity" },
      { rank: 9,  name: "take",   detail: "Carry, accept, require" },
      { rank: 10, name: "think",  detail: "Cognitive process, opinion" },
      { rank: 11, name: "see",    detail: "Visual perception" },
      { rank: 12, name: "come",   detail: "Movement toward speaker" },
      { rank: 13, name: "want",   detail: "Desire and wish" },
      { rank: 14, name: "look",   detail: "Direct gaze or appear" },
      { rank: 15, name: "use",    detail: "Employ or utilize" },
      { rank: 16, name: "find",   detail: "Discover or locate" },
      { rank: 17, name: "give",   detail: "Transfer or provide" },
      { rank: 18, name: "tell",   detail: "Inform or instruct" },
      { rank: 19, name: "work",   detail: "Labor or function" },
      { rank: 20, name: "call",   detail: "Name, summon, or phone" },
    ],
  },

  mostWatchedAnime: {
    label: "Most Watched Anime Series",
    aliases: {
      "dragon ball z":          ["dbz", "dragon ball"],
      "fullmetal alchemist":    ["fma", "fullmetal", "full metal alchemist"],
      "attack on titan":        ["aot", "shingeki no kyojin", "shingeki"],
      "demon slayer":           ["kimetsu no yaiba", "kimetsu"],
      "sword art online":       ["sao"],
      "my hero academia":       ["mha", "boku no hero", "bnha"],
      "jujutsu kaisen":         ["jjk"],
      "hunter x hunter":        ["hxh", "hunter hunter"],
      "neon genesis evangelion":["nge", "evangelion", "eva", "neon genesis"],
      "cowboy bebop":           ["bebop"],
      "one punch man":          ["opm"],
      "sailor moon":            ["bishoujo senshi sailor moon"],
      "naruto":                 ["naruto shippuden", "shippuden"],
      "spy x family":           ["spy family"],
      "death note":             ["deathnote"],
      "fairy tail":             ["fairytail"],
      "one piece":              ["onepiece"],
      "pokemon":                ["pokémon"],
      "tokyo ghoul":            ["tg"],
      "bleach":                 ["bleach tybw"],
    },
    items: [
      { rank: 1,  name: "Dragon Ball Z",              detail: "250M+ viewers globally" },
      { rank: 2,  name: "Naruto",                     detail: "220M+ viewers" },
      { rank: 3,  name: "One Piece",                  detail: "200M+ fans" },
      { rank: 4,  name: "Pokemon",                    detail: "Aired in 180+ countries" },
      { rank: 5,  name: "Attack on Titan",            detail: "Most-watched 2021–2023" },
      { rank: 6,  name: "Demon Slayer",               detail: "Highest-grossing anime film" },
      { rank: 7,  name: "Death Note",                 detail: "#1 or #2 on MyAnimeList" },
      { rank: 8,  name: "Fullmetal Alchemist",        detail: "Rated #1 on MAL for a decade" },
      { rank: 9,  name: "Sword Art Online",           detail: "Top isekai globally" },
      { rank: 10, name: "Tokyo Ghoul",                detail: "Top Netflix anime" },
      { rank: 11, name: "My Hero Academia",           detail: "Top 5 on Crunchyroll" },
      { rank: 12, name: "Jujutsu Kaisen",             detail: "Most-watched on Crunchyroll 2023" },
      { rank: 13, name: "Bleach",                     detail: "Classic Big 3 anime" },
      { rank: 14, name: "Hunter x Hunter",            detail: "Top 10 MAL" },
      { rank: 15, name: "Spy x Family",               detail: "Top streamed 2022–2023" },
      { rank: 16, name: "One Punch Man",              detail: "Viral hit, top Netflix anime" },
      { rank: 17, name: "Neon Genesis Evangelion",    detail: "New global gen via Netflix 2019" },
      { rank: 18, name: "Cowboy Bebop",               detail: "Most accessible for Western fans" },
      { rank: 19, name: "Sailor Moon",                detail: "~100M+ global viewers" },
      { rank: 20, name: "Fairy Tail",                 detail: "Large global fanbase, 328 episodes" },
    ],
  },

  heaviestAnimals: {
    label: "Heaviest Animals (one per species)",
    aliases: {
      "african elephant":       ["elephant", "african bush elephant"],
      "white rhinoceros":       ["rhino", "rhinoceros", "white rhino"],
      "saltwater crocodile":    ["saltwater croc", "croc", "crocodile"],
      "blue whale":             ["blue"],
      "polar bear":             ["polar"],
      "leatherback sea turtle": ["leatherback", "sea turtle"],
      "whale shark":            ["whale shark"],
      "bison":                  ["american bison", "buffalo", "american buffalo"],
      "giant panda":            ["panda"],
      "giant tortoise":         ["tortoise", "galapagos tortoise"],
      "komodo dragon":          ["komodo"],
      "goliath grouper":        ["grouper"],
      "ocean sunfish":          ["sunfish", "mola mola", "mola"],
      "gaur":                   ["indian bison"],
      "southern elephant seal": ["elephant seal"],
      "moose":                  ["elk"],
    },
    items: [
      { rank: 1,  name: "Blue Whale",              detail: "Up to 199,000 kg — heaviest animal" },
      { rank: 2,  name: "Whale Shark",             detail: "Up to 21,500 kg — heaviest fish" },
      { rank: 3,  name: "African Elephant",        detail: "Up to 13,000 kg — heaviest land animal" },
      { rank: 4,  name: "Hippopotamus",            detail: "Up to 4,500 kg" },
      { rank: 5,  name: "Southern Elephant Seal",  detail: "Up to 4,000 kg — heaviest seal" },
      { rank: 6,  name: "White Rhinoceros",        detail: "Up to 3,600 kg" },
      { rank: 7,  name: "Ocean Sunfish",           detail: "Up to 2,300 kg — heaviest bony fish" },
      { rank: 8,  name: "Giraffe",                 detail: "Up to 1,930 kg" },
      { rank: 9,  name: "Gaur",                    detail: "Up to 1,500 kg — heaviest wild cattle" },
      { rank: 10, name: "Bison",                   detail: "Up to 1,270 kg — heaviest in Americas" },
      { rank: 11, name: "Saltwater Crocodile",     detail: "Up to 1,000 kg — heaviest reptile" },
      { rank: 12, name: "Leatherback Sea Turtle",  detail: "Up to 900 kg — heaviest turtle" },
      { rank: 13, name: "Polar Bear",              detail: "Up to 800 kg — heaviest land carnivore" },
      { rank: 14, name: "Moose",                   detail: "Up to 770 kg — heaviest deer" },
      { rank: 15, name: "Giant Tortoise",          detail: "Up to 417 kg — heaviest tortoise" },
      { rank: 16, name: "Goliath Grouper",         detail: "Up to 400 kg — heaviest reef fish" },
      { rank: 17, name: "Gorilla",                 detail: "Up to 270 kg — heaviest primate" },
      { rank: 18, name: "Komodo Dragon",           detail: "Up to 166 kg — heaviest lizard" },
      { rank: 19, name: "Giant Panda",             detail: "Up to 160 kg" },
      { rank: 20, name: "Ostrich",                 detail: "Up to 156 kg — heaviest bird" },
    ],
  },

  mostPopularFruits: {
    label: "Most Popular Fruits Worldwide",
    aliases: {
      "cantaloupe":  ["melon", "rockmelon"],
      "peach":       ["peach nectarine"],
      "lemon":       ["lemon lime", "lime"],
    },
    items: [
      { rank: 1,  name: "Tomato",       detail: "~186M tonnes/year" },
      { rank: 2,  name: "Banana",       detail: "~124M tonnes/year" },
      { rank: 3,  name: "Watermelon",   detail: "~100M tonnes/year" },
      { rank: 4,  name: "Apple",        detail: "~86M tonnes/year" },
      { rank: 5,  name: "Grape",        detail: "~77M tonnes/year" },
      { rank: 6,  name: "Orange",       detail: "~79M tonnes/year" },
      { rank: 7,  name: "Coconut",      detail: "~62M tonnes/year" },
      { rank: 8,  name: "Mango",        detail: "~55M tonnes/year" },
      { rank: 9,  name: "Guava",        detail: "~55M tonnes/year" },
      { rank: 10, name: "Pineapple",    detail: "~28M tonnes/year" },
      { rank: 11, name: "Pear",         detail: "~27M tonnes/year" },
      { rank: 12, name: "Peach",        detail: "~25M tonnes/year" },
      { rank: 13, name: "Cantaloupe",   detail: "~20M tonnes/year" },
      { rank: 14, name: "Lemon",        detail: "~19M tonnes/year" },
      { rank: 15, name: "Mandarin",     detail: "~37M tonnes/year" },
      { rank: 16, name: "Papaya",       detail: "~13M tonnes/year" },
      { rank: 17, name: "Plum",         detail: "~12M tonnes/year" },
      { rank: 18, name: "Avocado",      detail: "~8M tonnes/year" },
      { rank: 19, name: "Strawberry",   detail: "~9M tonnes/year" },
      { rank: 20, name: "Raspberry",    detail: "~0.9M tonnes/year" },
    ],
  },

  countriesMostBeer: {
    label: "Countries Consuming Most Beer",
    aliases: {
      "czech republic": ["czechia", "czech"],
      "united states":  ["us", "usa", "america"],
    },
    items: [
      { rank: 1,  name: "Czech Republic",  detail: "188.6 L per capita/year" },
      { rank: 2,  name: "Austria",         detail: "107.8 L per capita/year" },
      { rank: 3,  name: "Germany",         detail: "99.0 L per capita/year" },
      { rank: 4,  name: "Palau",           detail: "~96 L per capita/year" },
      { rank: 5,  name: "Poland",          detail: "92.0 L per capita/year" },
      { rank: 6,  name: "Ireland",         detail: "91.3 L per capita/year" },
      { rank: 7,  name: "Romania",         detail: "88.7 L per capita/year" },
      { rank: 8,  name: "Lithuania",       detail: "86.2 L per capita/year" },
      { rank: 9,  name: "Spain",           detail: "83.6 L per capita/year" },
      { rank: 10, name: "Belgium",         detail: "82.3 L per capita/year" },
      { rank: 11, name: "Australia",       detail: "78.9 L per capita/year" },
      { rank: 12, name: "Croatia",         detail: "78.5 L per capita/year" },
      { rank: 13, name: "United States",   detail: "75.4 L per capita/year" },
      { rank: 14, name: "Finland",         detail: "74.1 L per capita/year" },
      { rank: 15, name: "Slovakia",        detail: "73.0 L per capita/year" },
      { rank: 16, name: "Denmark",         detail: "72.4 L per capita/year" },
      { rank: 17, name: "Hungary",         detail: "71.8 L per capita/year" },
      { rank: 18, name: "Latvia",          detail: "70.9 L per capita/year" },
      { rank: 19, name: "Netherlands",     detail: "70.1 L per capita/year" },
      { rank: 20, name: "Slovenia",        detail: "69.2 L per capita/year" },
    ],
  },

  mostFIFAWorldCupMatches: {
    label: "Nations with Most FIFA World Cup Wins",
    aliases: {
      "netherlands": ["holland", "dutch"],
      "czechia":     ["czech republic"],
    },
    items: [
      { rank: 1,  name: "Brazil",       detail: "76 wins" },
      { rank: 2,  name: "Germany",      detail: "68 wins" },
      { rank: 3,  name: "Argentina",    detail: "47 wins" },
      { rank: 4,  name: "Italy",        detail: "45 wins" },
      { rank: 5,  name: "France",       detail: "39 wins" },
      { rank: 6,  name: "England",      detail: "32 wins" },
      { rank: 7,  name: "Spain",        detail: "31 wins" },
      { rank: 8,  name: "Netherlands",  detail: "30 wins" },
      { rank: 9,  name: "Uruguay",      detail: "25 wins" },
      { rank: 10, name: "Belgium",      detail: "21 wins" },
      { rank: 11, name: "Russia",       detail: "19 wins (tied w/ Sweden)" },
      { rank: 12, name: "Serbia",       detail: "18 wins" },
      { rank: 13, name: "Mexico",       detail: "17 wins (tied)" },
      { rank: 14, name: "Poland",       detail: "17 wins (tied)" },
      { rank: 15, name: "Portugal",     detail: "17 wins (tied)" },
      { rank: 16, name: "Hungary",      detail: "15 wins" },
      { rank: 17, name: "Switzerland",  detail: "14 wins" },
      { rank: 18, name: "Croatia",      detail: "13 wins" },
      { rank: 19, name: "Austria",      detail: "12 wins (tied w/ Czechia)" },
      { rank: 20, name: "Czechia",      detail: "12 wins (tied w/ Austria)" },
    ],
  },

  highestGrossingSuperheroMovies: {
    label: "Highest-Grossing Superhero Movies",
    aliases: {
      "avengers endgame":           ["endgame"],
      "avengers infinity war":      ["infinity war"],
      "spider-man no way home":     ["no way home", "spiderman no way home"],
      "the avengers":               ["avengers 1", "avengers 2012"],
      "black panther":              ["wakanda"],
      "avengers age of ultron":     ["age of ultron"],
      "black panther wakanda forever": ["wakanda forever"],
      "doctor strange multiverse":  ["doctor strange 2", "multiverse of madness"],
      "thor love and thunder":      ["love and thunder"],
      "captain america civil war":  ["civil war"],
      "aquaman":                    ["aquaman 2018"],
      "joker":                      ["joker 2019"],
      "batman v superman":          ["batman vs superman", "bvs"],
      "suicide squad":              ["suicide squad 2016"],
      "guardians of the galaxy":    ["guardians 1", "gotg"],
      "captain marvel":             ["captain marvel 2019"],
      "thor ragnarok":              ["ragnarok"],
      "wonder woman":               ["wonder woman 2017"],
      "iron man 3":                 ["iron man three"],
      "deadpool and wolverine":     ["deadpool wolverine", "deadpool 3"],
    },
    items: [
      { rank: 1,  name: "Avengers Endgame",              detail: "$2.799B (2019)" },
      { rank: 2,  name: "Avengers Infinity War",         detail: "$2.048B (2018)" },
      { rank: 3,  name: "Spider-Man No Way Home",        detail: "$1.921B (2021)" },
      { rank: 4,  name: "The Avengers",                  detail: "$1.520B (2012)" },
      { rank: 5,  name: "Avengers Age of Ultron",        detail: "$1.405B (2015)" },
      { rank: 6,  name: "Black Panther",                 detail: "$1.349B (2018)" },
      { rank: 7,  name: "Deadpool and Wolverine",        detail: "$1.338B (2024)" },
      { rank: 8,  name: "Iron Man 3",                    detail: "$1.215B (2013)" },
      { rank: 9,  name: "Captain Marvel",                detail: "$1.128B (2019)" },
      { rank: 10, name: "Captain America Civil War",     detail: "$1.153B (2016)" },
      { rank: 11, name: "Aquaman",                       detail: "$1.148B (2018)" },
      { rank: 12, name: "Joker",                         detail: "$1.079B (2019)" },
      { rank: 13, name: "Thor Ragnarok",                 detail: "$854M (2017)" },
      { rank: 14, name: "Black Panther Wakanda Forever", detail: "$859M (2022)" },
      { rank: 15, name: "Batman v Superman",             detail: "$873M (2016)" },
      { rank: 16, name: "Wonder Woman",                  detail: "$822M (2017)" },
      { rank: 17, name: "Doctor Strange Multiverse",     detail: "$955M (2022)" },
      { rank: 18, name: "Guardians of the Galaxy",       detail: "$773M (2014)" },
      { rank: 19, name: "Thor Love and Thunder",         detail: "$761M (2022)" },
      { rank: 20, name: "Suicide Squad",                 detail: "$746M (2016)" },
    ],
  },

  mostPopularVideoGameFranchises: {
    label: "Best-Selling Video Game Franchises",
    aliases: {
      "mario":              ["super mario", "mario bros"],
      "pokemon":            ["pokémon"],
      "call of duty":       ["cod"],
      "grand theft auto":   ["gta"],
      "fifa":               ["ea sports fc", "ea fc"],
      "the sims":           ["sims"],
      "need for speed":     ["nfs"],
      "legend of zelda":    ["zelda"],
      "street fighter":     ["sf"],
      "mortal kombat":      ["mk"],
      "final fantasy":      ["ff"],
      "minecraft":          ["mine craft"],
      "sonic":              ["sonic the hedgehog"],
      "donkey kong":        ["dk"],
      "crash bandicoot":    ["crash"],
    },
    items: [
      { rank: 1,  name: "Mario",              detail: "800M+ copies sold" },
      { rank: 2,  name: "Pokemon",            detail: "480M+ copies sold" },
      { rank: 3,  name: "Call of Duty",       detail: "425M+ copies sold" },
      { rank: 4,  name: "Grand Theft Auto",   detail: "380M+ copies sold" },
      { rank: 5,  name: "FIFA",               detail: "325M+ copies sold" },
      { rank: 6,  name: "Minecraft",          detail: "300M+ copies sold" },
      { rank: 7,  name: "Sonic",              detail: "180M+ copies sold" },
      { rank: 8,  name: "Final Fantasy",      detail: "173M+ copies sold" },
      { rank: 9,  name: "Need for Speed",     detail: "150M+ copies sold" },
      { rank: 10, name: "Legend of Zelda",    detail: "150M+ copies sold" },
      { rank: 11, name: "Assassin's Creed",   detail: "200M+ copies sold" },
      { rank: 12, name: "Resident Evil",      detail: "150M+ copies sold" },
      { rank: 13, name: "The Sims",           detail: "200M+ copies sold" },
      { rank: 14, name: "Halo",               detail: "85M+ copies sold" },
      { rank: 15, name: "Wii Sports",         detail: "83M+ copies sold" },
      { rank: 16, name: "Mortal Kombat",      detail: "73M+ copies sold" },
      { rank: 17, name: "God of War",         detail: "50M+ copies sold" },
      { rank: 18, name: "Crash Bandicoot",    detail: "50M+ copies sold" },
      { rank: 19, name: "Street Fighter",     detail: "49M+ copies sold" },
      { rank: 20, name: "Donkey Kong",        detail: "65M+ copies sold" },
    ],
  },

  mostPopularAnimatedMovies: {
    label: "Highest-Grossing Animated Movies",
    aliases: {
      "frozen":             ["frozen 1"],
      "frozen 2":           ["frozen ii"],
      "the lion king":      ["lion king"],
      "incredibles 2":      ["the incredibles 2"],
      "minions":            ["minions 1"],
      "toy story 4":        ["toy story"],
      "finding dory":       ["finding nemo 2"],
      "zootopia":           ["zootropolis"],
      "super mario bros":   ["mario movie"],
      "despicable me 3":    ["despicable me"],
      "inside out 2":       ["inside out"],
      "secret life of pets":["pets"],
      "kung fu panda 4":    ["kung fu panda"],
    },
    items: [
      { rank: 1,  name: "Inside Out 2",          detail: "$1.698B (2024)" },
      { rank: 2,  name: "Frozen 2",              detail: "$1.453B (2019)" },
      { rank: 3,  name: "Super Mario Bros",      detail: "$1.362B (2023)" },
      { rank: 4,  name: "Frozen",                detail: "$1.290B (2013)" },
      { rank: 5,  name: "Incredibles 2",         detail: "$1.243B (2018)" },
      { rank: 6,  name: "Minions",               detail: "$1.159B (2015)" },
      { rank: 7,  name: "Toy Story 4",           detail: "$1.073B (2019)" },
      { rank: 8,  name: "Despicable Me 3",       detail: "$1.034B (2017)" },
      { rank: 9,  name: "Finding Dory",          detail: "$1.029B (2016)" },
      { rank: 10, name: "Zootopia",              detail: "$1.024B (2016)" },
      { rank: 11, name: "The Lion King",         detail: "$987M (1994)" },
      { rank: 12, name: "Despicable Me 2",       detail: "$970M (2013)" },
      { rank: 13, name: "Moana 2",               detail: "$966M (2024)" },
      { rank: 14, name: "Kung Fu Panda 4",       detail: "$547M (2024)" },
      { rank: 15, name: "Shrek 2",               detail: "$919M (2004)" },
      { rank: 16, name: "Monsters University",   detail: "$743M (2013)" },
      { rank: 17, name: "Coco",                  detail: "$807M (2017)" },
      { rank: 18, name: "Secret Life of Pets",   detail: "$875M (2016)" },
      { rank: 19, name: "Sing",                  detail: "$634M (2016)" },
      { rank: 20, name: "Up",                    detail: "$735M (2009)" },
    ],
  },

  mostFollowedInstagram: {
    label: "Most Followed Accounts on Instagram",
    aliases: {
      "cristiano ronaldo":  ["ronaldo", "cr7"],
      "lionel messi":       ["messi", "leo messi"],
      "selena gomez":       ["selena"],
      "kylie jenner":       ["kylie"],
      "the rock":           ["dwayne johnson", "dwayne the rock johnson"],
      "ariana grande":      ["ariana", "ari"],
      "kim kardashian":     ["kim k", "kardashian"],
      "beyonce":            ["beyoncé"],
      "khloe kardashian":   ["khloe"],
      "kendall jenner":     ["kendall"],
      "taylor swift":       ["swift"],
      "virat kohli":        ["kohli"],
      "neymar":             ["neymar jr"],
      "justin bieber":      ["bieber"],
      "national geographic":["natgeo", "nat geo"],
      "khaby lame":         ["khaby"],
    },
    items: [
      { rank: 1,  name: "Cristiano Ronaldo",   detail: "640M+ followers" },
      { rank: 2,  name: "Lionel Messi",        detail: "510M+ followers" },
      { rank: 3,  name: "Selena Gomez",        detail: "430M+ followers" },
      { rank: 4,  name: "Kylie Jenner",        detail: "400M+ followers" },
      { rank: 5,  name: "The Rock",            detail: "395M+ followers" },
      { rank: 6,  name: "Ariana Grande",       detail: "380M+ followers" },
      { rank: 7,  name: "Kim Kardashian",      detail: "360M+ followers" },
      { rank: 8,  name: "Khloe Kardashian",    detail: "310M+ followers" },
      { rank: 9,  name: "Beyonce",             detail: "320M+ followers" },
      { rank: 10, name: "Khaby Lame",          detail: "315M+ followers" },
      { rank: 11, name: "Kendall Jenner",      detail: "300M+ followers" },
      { rank: 12, name: "Justin Bieber",       detail: "295M+ followers" },
      { rank: 13, name: "National Geographic", detail: "280M+ followers" },
      { rank: 14, name: "Taylor Swift",        detail: "285M+ followers" },
      { rank: 15, name: "Virat Kohli",         detail: "270M+ followers" },
      { rank: 16, name: "Nicki Minaj",         detail: "230M+ followers" },
      { rank: 17, name: "Neymar",              detail: "225M+ followers" },
      { rank: 18, name: "Miley Cyrus",         detail: "210M+ followers" },
      { rank: 19, name: "Cardi B",             detail: "170M+ followers" },
      { rank: 20, name: "LeBron James",        detail: "160M+ followers" },
    ],
  },

  mostWatchedYouTubeChannels: {
    label: "Most Subscribed YouTube Channels",
    aliases: {
      "mrbeast":            ["mr beast", "beast"],
      "t-series":           ["tseries", "t series"],
      "cocomelon":          ["coco melon"],
      "set india":          ["set"],
      "sony sab":           ["sab tv"],
      "like nastya":        ["nastya"],
      "vlad and niki":      ["vlad and nikki"],
      "dude perfect":       ["dude perf"],
      "pewdiepie":          ["pewdie"],
      "kids diana show":    ["diana"],
    },
    items: [
      { rank: 1,  name: "MrBeast",             detail: "380M+ subscribers" },
      { rank: 2,  name: "T-Series",            detail: "275M+ subscribers" },
      { rank: 3,  name: "Cocomelon",           detail: "185M+ subscribers" },
      { rank: 4,  name: "Set India",           detail: "175M+ subscribers" },
      { rank: 5,  name: "Sony SAB",            detail: "165M+ subscribers" },
      { rank: 6,  name: "Kids Diana Show",     detail: "120M+ subscribers" },
      { rank: 7,  name: "Like Nastya",         detail: "120M+ subscribers" },
      { rank: 8,  name: "Vlad and Niki",       detail: "115M+ subscribers" },
      { rank: 9,  name: "YouTube Movies",      detail: "115M+ subscribers" },
      { rank: 10, name: "PewDiePie",           detail: "111M+ subscribers" },
      { rank: 11, name: "Zee Music Company",   detail: "107M+ subscribers" },
      { rank: 12, name: "WWE",                 detail: "100M+ subscribers" },
      { rank: 13, name: "Blackpink",           detail: "95M+ subscribers" },
      { rank: 14, name: "Goldmines",           detail: "88M+ subscribers" },
      { rank: 15, name: "5-Minute Crafts",     detail: "80M+ subscribers" },
      { rank: 16, name: "BTS",                 detail: "77M+ subscribers" },
      { rank: 17, name: "Pinkfong",            detail: "77M+ subscribers" },
      { rank: 18, name: "Justin Bieber",       detail: "73M+ subscribers" },
      { rank: 19, name: "Dude Perfect",        detail: "60M+ subscribers" },
      { rank: 20, name: "Marshmello",          detail: "56M+ subscribers" },
    ],
  },

  mostPopulousCountries: {
    label: "Most Populous Countries",
    aliases: {
      "united states":              ["us", "usa", "america"],
      "democratic republic of congo": ["drc", "congo", "dr congo"],
    },
    items: [
      { rank: 1,  name: "India",               detail: "1.44B people" },
      { rank: 2,  name: "China",               detail: "1.41B people" },
      { rank: 3,  name: "United States",       detail: "340M people" },
      { rank: 4,  name: "Indonesia",           detail: "278M people" },
      { rank: 5,  name: "Pakistan",            detail: "245M people" },
      { rank: 6,  name: "Brazil",              detail: "216M people" },
      { rank: 7,  name: "Nigeria",             detail: "224M people" },
      { rank: 8,  name: "Bangladesh",          detail: "172M people" },
      { rank: 9,  name: "Russia",              detail: "144M people" },
      { rank: 10, name: "Ethiopia",            detail: "128M people" },
      { rank: 11, name: "Mexico",              detail: "130M people" },
      { rank: 12, name: "Japan",               detail: "124M people" },
      { rank: 13, name: "Philippines",         detail: "115M people" },
      { rank: 14, name: "Egypt",               detail: "106M people" },
      { rank: 15, name: "Democratic Republic of Congo", detail: "102M people" },
      { rank: 16, name: "Vietnam",             detail: "98M people" },
      { rank: 17, name: "Iran",                detail: "87M people" },
      { rank: 18, name: "Turkey",              detail: "85M people" },
      { rank: 19, name: "Germany",             detail: "84M people" },
      { rank: 20, name: "Thailand",            detail: "72M people" },
    ],
  },

  mostPopularVegetables: {
    label: "Most Popular Vegetables Worldwide",
    aliases: {
      "sweet potato":       ["yam", "sweet potatoes"],
      "cassava":            ["manioc", "yuca"],
      "eggplant":           ["aubergine", "brinjal"],
      "zucchini":           ["courgette"],
      "bell pepper":        ["capsicum", "pepper"],
      "chili pepper":       ["chilli", "chili", "chilli pepper"],
      "artichoke":          ["globe artichoke"],
    },
    items: [
      { rank: 1,  name: "Potato",         detail: "~376M tonnes/year" },
      { rank: 2,  name: "Cassava",        detail: "~303M tonnes/year" },
      { rank: 3,  name: "Onion",          detail: "~104M tonnes/year" },
      { rank: 4,  name: "Cucumber",       detail: "~93M tonnes/year" },
      { rank: 5,  name: "Sweet Potato",   detail: "~91M tonnes/year" },
      { rank: 6,  name: "Cabbage",        detail: "~71M tonnes/year" },
      { rank: 7,  name: "Eggplant",       detail: "~58M tonnes/year" },
      { rank: 8,  name: "Carrot",         detail: "~44M tonnes/year" },
      { rank: 9,  name: "Chili Pepper",   detail: "~40M tonnes/year" },
      { rank: 10, name: "Bell pepper",    detail: "~37M tonnes/year" },
      { rank: 11, name: "Spinach",        detail: "~31M tonnes/year" },
      { rank: 12, name: "Garlic",         detail: "~31M tonnes/year" },
      { rank: 13, name: "Lettuce",        detail: "~28M tonnes/year" },
      { rank: 14, name: "Pumpkin",        detail: "~27M tonnes/year" },
      { rank: 15, name: "Cauliflower",    detail: "~26M tonnes/year" },
      { rank: 16, name: "Broccoli",       detail: "~25M tonnes/year" },
      { rank: 17, name: "Asparagus",      detail: "~9M tonnes/year" },
      { rank: 18, name: "Celery",         detail: "~8M tonnes/year" },
      { rank: 19, name: "Zucchini",       detail: "~8M tonnes/year" },
      { rank: 20, name: "Artichoke",      detail: "~1.5M tonnes/year" },
    ],
  },

  mostVisitedLandmarks: {
    label: "Most Visited Landmarks in the World",
    aliases: {
      "eiffel tower":       ["tour eiffel", "eiffel"],
      "great wall of china":["great wall", "great wall china"],
      "machu picchu":       ["machu"],
      "colosseum":          ["coliseum", "roman colosseum"],
      "statue of liberty":  ["liberty statue", "lady liberty"],
      "times square":       ["times sq"],
      "notre dame":         ["notre dame cathedral", "notre-dame"],
      "angkor wat":         ["angkor"],
      "sagrada familia":    ["sagrada", "sagrada familia barcelona"],
      "big ben":            ["westminster", "houses of parliament"],
      "burj khalifa":       ["burj", "khalifa"],
      "niagara falls":      ["niagara"],
      "sydney opera house": ["sydney opera", "opera house"],
      "louvre":             ["louvre museum", "musee du louvre"],
    },
    items: [
      { rank: 1,  name: "Times Square",         detail: "~50M visitors/year — New York, USA" },
      { rank: 2,  name: "Niagara Falls",         detail: "~30M visitors/year — USA/Canada" },
      { rank: 3,  name: "Notre Dame",            detail: "~12M visitors/year — Paris, France" },
      { rank: 4,  name: "Sydney Opera House",    detail: "~10.9M visitors/year — Australia" },
      { rank: 5,  name: "Great Wall of China",   detail: "~10M visitors/year — China" },
      { rank: 6,  name: "Louvre",                detail: "~9M visitors/year — Paris, France" },
      { rank: 7,  name: "Colosseum",             detail: "~7.6M visitors/year — Rome, Italy" },
      { rank: 8,  name: "Taj Mahal",             detail: "~7M visitors/year — India" },
      { rank: 9,  name: "Eiffel Tower",          detail: "~7M visitors/year — Paris, France" },
      { rank: 10, name: "Chichen Itza",          detail: "~4M visitors/year — Mexico" },
      { rank: 11, name: "Statue of Liberty",     detail: "~4.5M visitors/year — New York, USA" },
      { rank: 12, name: "Sagrada Familia",       detail: "~4.5M visitors/year — Barcelona, Spain" },
      { rank: 13, name: "Big Ben",               detail: "~3M visitors/year — London, UK" },
      { rank: 14, name: "Acropolis",             detail: "~3M visitors/year — Athens, Greece" },
      { rank: 15, name: "Angkor Wat",            detail: "~2.6M visitors/year — Cambodia" },
      { rank: 16, name: "Burj Khalifa",          detail: "~1.9M visitors/year — Dubai, UAE" },
      { rank: 17, name: "Stonehenge",            detail: "~1.6M visitors/year — UK" },
      { rank: 18, name: "Machu Picchu",          detail: "~1.5M visitors/year — Peru" },
      { rank: 19, name: "Petra",                 detail: "~1M visitors/year — Jordan" },
      { rank: 20, name: "Easter Island",         detail: "~100K visitors/year — Chile" },
    ],
  },

  mostPopularBoyNames: {
    label: "Most Popular Baby Boy Names in Brazil (2025)",
    aliases: {
      "miguel":     [],
      "arthur":     [],
      "heitor":     [],
      "theo":       ["theodore"],
      "davi":       ["david"],
      "gabriel":    ["gabe"],
      "bernardo":   ["berna"],
      "samuel":     ["sam"],
      "noah":       [],
      "pedro":      [],
      "lucas":      ["luke"],
      "matheus":    ["matthew", "mateus"],
      "rafael":     ["rafa"],
      "enzo":       [],
      "nicolas":    ["nicholas", "nicky"],
      "ryan":       [],
      "vitor":      ["victor"],
      "guilherme":  ["william", "gui"],
      "joao":       ["joão", "john"],
      "felipe":     ["philip", "filipe"],
    },
    items: [
      { rank: 1,  name: "Miguel",     detail: "Most popular boy name in Brazil" },
      { rank: 2,  name: "Arthur",     detail: "Top 2 for several years running" },
      { rank: 3,  name: "Heitor",     detail: "Rising fast across Brazil" },
      { rank: 4,  name: "Theo",       detail: "Top 5 in urban centres" },
      { rank: 5,  name: "Davi",       detail: "Biblical name, very popular" },
      { rank: 6,  name: "Gabriel",    detail: "Classic top 10 in Brazil" },
      { rank: 7,  name: "Bernardo",   detail: "Growing popularity nationwide" },
      { rank: 8,  name: "Samuel",     detail: "Consistent top 10 in Brazil" },
      { rank: 9,  name: "Noah",       detail: "International name rising in Brazil" },
      { rank: 10, name: "Pedro",      detail: "Traditional Brazilian favourite" },
      { rank: 11, name: "Lucas",      detail: "Long-time top 10 in Brazil" },
      { rank: 12, name: "Matheus",    detail: "Common across all regions" },
      { rank: 13, name: "Rafael",     detail: "Classic name, consistently popular" },
      { rank: 14, name: "Enzo",       detail: "Italian origin, very popular in Brazil" },
      { rank: 15, name: "Nicolas",    detail: "French/Greek origin, top 20 Brazil" },
      { rank: 16, name: "Ryan",       detail: "English name trending in Brazil" },
      { rank: 17, name: "Vitor",      detail: "Brazilian spelling of Victor" },
      { rank: 18, name: "Guilherme",  detail: "Brazilian form of William" },
      { rank: 19, name: "Joao",       detail: "Traditional classic, all-time top name" },
      { rank: 20, name: "Felipe",     detail: "Portuguese form of Philip" },
    ],
  },

  mostPopularGirlNames: {
    label: "Most Popular Baby Girl Names in Brazil (2025)",
    aliases: {
      "alice":      [],
      "sofia":      ["sophia"],
      "helena":     [],
      "valentina":  ["val"],
      "laura":      [],
      "isabella":   ["bella", "izzy"],
      "manuela":    ["manu"],
      "julia":      ["júlia", "julianna"],
      "maria":      [],
      "ana":        ["anna"],
      "clara":      [],
      "beatriz":    ["bia", "bea"],
      "lorena":     [],
      "luiza":      ["luisa", "louise"],
      "yasmin":     ["jasmine", "yasmine"],
      "giovanna":   ["giovana", "giovana"],
      "mariana":    ["mari"],
      "lara":       [],
      "camila":     ["camilla"],
      "leticia":    ["letícia"],
    },
    items: [
      { rank: 1,  name: "Alice",      detail: "Most popular girl name in Brazil" },
      { rank: 2,  name: "Sofia",      detail: "Top 2 for several years running" },
      { rank: 3,  name: "Helena",     detail: "Classic name, surging in Brazil" },
      { rank: 4,  name: "Valentina",  detail: "Italian origin, very popular in Brazil" },
      { rank: 5,  name: "Laura",      detail: "Timeless favourite across Brazil" },
      { rank: 6,  name: "Isabella",   detail: "Long-time top 10 in Brazil" },
      { rank: 7,  name: "Manuela",    detail: "Top choice in southern Brazil" },
      { rank: 8,  name: "Julia",      detail: "Classic top 10 in Brazil" },
      { rank: 9,  name: "Maria",      detail: "All-time most common name in Brazil" },
      { rank: 10, name: "Ana",        detail: "Traditional classic, widely used" },
      { rank: 11, name: "Clara",      detail: "Rising steadily in popularity" },
      { rank: 12, name: "Beatriz",    detail: "Traditional Brazilian favourite" },
      { rank: 13, name: "Lorena",     detail: "Popular across all regions" },
      { rank: 14, name: "Luiza",      detail: "Brazilian form of Louise" },
      { rank: 15, name: "Yasmin",     detail: "Trending strongly in Brazil" },
      { rank: 16, name: "Giovanna",   detail: "Italian origin, top 20 in Brazil" },
      { rank: 17, name: "Mariana",    detail: "Consistent top 20 for decades" },
      { rank: 18, name: "Lara",       detail: "Short and popular across Brazil" },
      { rank: 19, name: "Camila",     detail: "Popular in Brazil and Latin America" },
      { rank: 20, name: "Leticia",    detail: "Traditional Brazilian name" },
    ],
  },

  mostWatchedSportsWorldwide: {
    label: "Most Watched Sports Worldwide",
    aliases: {
      "football":           ["soccer", "association football"],
      "cricket":            ["test cricket"],
      "field hockey":       ["hockey"],
      "tennis":             ["lawn tennis"],
      "table tennis":       ["ping pong"],
      "basketball":         ["nba"],
      "american football":  ["nfl", "gridiron"],
      "rugby":              ["rugby union", "rugby league"],
      "badminton":          ["badmin"],
      "formula 1":          ["f1", "formula one"],
      "athletics":          ["track and field"],
    },
    items: [
      { rank: 1,  name: "Football",          detail: "3.5B fans worldwide" },
      { rank: 2,  name: "Cricket",           detail: "2.5B fans worldwide" },
      { rank: 3,  name: "Basketball",        detail: "2.2B fans worldwide" },
      { rank: 4,  name: "Field Hockey",      detail: "2.0B fans worldwide" },
      { rank: 5,  name: "Tennis",            detail: "1.0B fans worldwide" },
      { rank: 6,  name: "Volleyball",        detail: "900M fans worldwide" },
      { rank: 7,  name: "Table Tennis",      detail: "850M fans worldwide" },
      { rank: 8,  name: "Baseball",          detail: "500M fans worldwide" },
      { rank: 9,  name: "Rugby",             detail: "475M fans worldwide" },
      { rank: 10, name: "American Football", detail: "400M fans worldwide" },
      { rank: 11, name: "Golf",              detail: "390M fans worldwide" },
      { rank: 12, name: "Swimming",          detail: "385M fans worldwide" },
      { rank: 13, name: "Athletics",         detail: "350M fans worldwide" },
      { rank: 14, name: "Badminton",         detail: "220M fans worldwide" },
      { rank: 15, name: "Boxing",            detail: "200M fans worldwide" },
      { rank: 16, name: "Cycling",           detail: "180M fans worldwide" },
      { rank: 17, name: "Formula 1",         detail: "170M fans worldwide" },
      { rank: 18, name: "Gymnastics",        detail: "130M fans worldwide" },
      { rank: 19, name: "Handball",          detail: "120M fans worldwide" },
      { rank: 20, name: "Ice Hockey",        detail: "110M fans worldwide" },
    ],
  },

};

// triviaData is available as a global variable
