/* Shared word lists — used by Alphabet Grab (alphabet/) and Take a Seat (take-a-seat/).
   Words are space-separated; "_" joins a multi-word item. Level = how common the WORD is (A1 / A2 / B1).
   "prompt" is how Take a Seat asks for a word from the list: "<prompt> starting with <letter>".
   Validate after any edit:  node shared/validate-word-banks.js
   Load with <script src="../shared/word-banks.js"></script>; exposes window.WORD_BANKS. */
(function (root) {
  'use strict';
  var WORD_BANKS = [
    // Words are space-separated; "_" joins a multi-word item. Level = how common the WORD is (A1 / A2 / B1).
    { id: 'animals', prompt: 'An animal', label: 'Animals', icon: '🐾', group: 'Vocabulary',
      A1: 'ant bear bee bird cat chicken cow dog dolphin duck elephant fish fox frog giraffe goat horse lion monkey mouse pig rabbit shark sheep snake spider tiger turtle whale zebra',
      A2: 'bat butterfly camel crab crocodile deer donkey eagle fly goose gorilla hamster hippo insect jellyfish kangaroo kitten koala leopard lizard octopus owl panda parrot penguin polar_bear pony puppy rat snail squirrel swan wolf worm',
      B1: 'beetle bull cheetah chimpanzee dinosaur flamingo gecko hedgehog hyena iguana jaguar llama lobster mosquito moth newt ostrich otter peacock pelican quail raccoon rhino salmon seal sloth tortoise vulture walrus yak' },
    { id: 'food', prompt: 'Something to eat or drink', label: 'Food and Drink', icon: '🍎', group: 'Vocabulary',
      A1: 'apple banana bread butter cake candy carrot cheese chocolate coffee cookie egg fish fruit hamburger ice_cream juice lemon meat milk orange pasta pizza potato rice salad sandwich soup sugar tea tomato water',
      A2: 'avocado bean biscuit burger cereal cherry coconut corn cucumber donut fries garlic grape honey hot_dog jam ketchup kiwi lettuce lime mango melon mushroom noodles nut olive onion pancake peach peanut pear pepper pie pineapple popcorn sausage steak strawberry sweets toast vanilla vegetable waffle watermelon yogurt',
      B1: 'broccoli cabbage cauliflower dumpling eggplant fig lasagna lentils mayonnaise omelet quiche quinoa radish raspberry spinach sushi tuna vinegar zucchini' },
    { id: 'jobs', prompt: 'A job', label: 'Jobs', icon: '👷', group: 'People and Places',
      A1: 'actor artist cook dancer doctor driver farmer nurse pilot police_officer singer teacher waiter',
      A2: 'baker builder chef cleaner dentist designer engineer firefighter guide hairdresser journalist judge lawyer manager mechanic model musician officer painter photographer plumber receptionist reporter sailor scientist secretary shop_assistant soldier tour_guide vet writer',
      B1: 'accountant architect astronaut carpenter cashier editor electrician gardener illustrator interpreter inventor jeweler kindergarten_teacher librarian lifeguard optician pharmacist politician programmer surgeon tailor translator umpire yoga_teacher zookeeper' },
    { id: 'clothes', prompt: 'Something to wear', label: 'Clothes and Accessories', icon: '👕', group: 'Vocabulary',
      A1: 'boots cap coat dress hat jacket jeans pants shirt shoes shorts skirt socks sweater T-shirt trousers',
      A2: 'belt blouse bracelet earrings flip-flops gloves glasses hoodie jumper leggings mask necklace pajamas raincoat ring sandals scarf slippers sneakers suit sunglasses swimsuit tie tracksuit underwear uniform vest watch',
      B1: 'apron bow_tie cardigan collar kimono mittens nightgown overalls overcoat tights yoga_pants' },
    { id: 'house', prompt: 'Something in a house', label: 'Things in a House', icon: '🏠', group: 'Vocabulary',
      A1: 'bath bathroom bed bedroom chair clock computer cup door fridge garden kitchen lamp phone shower sofa stairs table TV window',
      A2: 'alarm_clock armchair blanket bookcase bowl bucket carpet ceiling closet cooker cupboard curtain desk dishwasher drawer elevator fan floor fork freezer garage glass hairdryer hall heater iron kettle key knife ladder light microwave mirror napkin oven pan pillow plant plate radio roof rug shelf sink spoon tap toaster toilet toothbrush towel vase wall wardrobe washing_machine yard',
      B1: 'attic basement chimney cushion doorbell fireplace jar lid mattress quilt radiator socket vacuum_cleaner' },
    { id: 'school', prompt: 'Something at school', label: 'School', icon: '✏️', group: 'Vocabulary',
      A1: 'bag board book chair class classroom computer desk English homework lesson math pen pencil question ruler school student teacher test',
      A2: 'art backpack biology break cafeteria calculator canteen chemistry dictionary eraser exam folder geography glue grade gym history IT lab library lunch map marker music notebook office paper physics playground principal project quiz science scissors sharpener subject textbook timetable uniform vocabulary whiteboard',
      B1: 'assembly certificate diploma essay graduation ink janitor kindergarten locker semester term university yearbook' },
    { id: 'body', prompt: 'A word about the body or health', label: 'Body and Health', icon: '💪', group: 'Vocabulary',
      A1: 'arm back body doctor ear eye face finger foot hair hand head leg mouth nose teeth tooth',
      A2: 'ankle beard blood bone brain cheek chest chin cold cough dentist elbow eyebrow fever flu headache heart hip hospital ill knee lip medicine nail neck nurse pain pill shoulder sick skin stomach temperature thumb toe tongue waist wrist',
      B1: 'allergy bandage eyelash forehead germs gums heel injury jaw kidney liver lung muscle organ palm rash rib skull spine thigh vein virus vitamin' },
    { id: 'sports', prompt: 'A sport or hobby', label: 'Sports and Hobbies', icon: '⚽', group: 'Vocabulary',
      A1: 'baseball basketball cooking cycling dancing drawing football golf hockey music painting reading running singing skating skiing soccer swimming tennis volleyball',
      A2: 'athletics badminton bowling boxing camping chess climbing diving exercise fishing gardening gymnastics hiking horse_riding ice_skating jogging judo karate kite_flying photography rugby sailing skateboarding snowboarding surfing table_tennis video_games walking yoga',
      B1: 'archery fencing juggling kayaking knitting netball origami parkour quilting rowing scuba_diving unicycling windsurfing wrestling zumba' },
    { id: 'transport', prompt: 'A kind of transport', label: 'Transport', icon: '🚌', group: 'People and Places',
      A1: 'bike boat bus car plane ship taxi train',
      A2: 'ambulance bicycle coach cruise_ship delivery_truck electric_car ferry fire_truck garbage_truck helicopter hot-air_balloon jet lorry metro motorbike motorcycle police_car racing_car rocket school_bus scooter skateboard sports_car subway tram truck underground van',
      B1: 'cable_car canoe caravan double-decker glider go-kart hovercraft jeep kayak limousine ocean_liner quad_bike raft sailboat spaceship submarine tractor unicycle wagon yacht zeppelin' },
    { id: 'places', prompt: 'A place in a city', label: 'Places in a City', icon: '🏙️', group: 'People and Places',
      A1: 'airport bank beach cafe cinema hospital hotel house library museum park restaurant school shop station street supermarket zoo',
      A2: 'bakery bookstore bridge bus_station bus_stop castle church department_store factory farm gallery garage gym mall market office parking_lot pharmacy playground police_station pool post_office square stadium temple theater tower university water_park',
      B1: 'aquarium cathedral courthouse embassy fire_station harbor ice_rink jail kiosk mosque newsstand opera_house prison quay skyscraper town_hall youth_club' },
    { id: 'countries', prompt: 'A country', label: 'Countries', icon: '🌍', group: 'People and Places',
      A1: 'Argentina Australia Brazil Canada Chile China England France Germany India Italy Japan Mexico Portugal Russia Spain United_States',
      A2: 'Belgium Bolivia Colombia Cuba Denmark Ecuador Egypt Finland Greece Iceland Indonesia Ireland Jamaica Kenya Morocco Netherlands New_Zealand Nigeria Norway Paraguay Peru Poland Scotland South_Africa South_Korea Sweden Switzerland Thailand Turkey Ukraine United_Kingdom Uruguay Venezuela Vietnam Wales',
      B1: 'Austria Croatia Ethiopia Ghana Honduras Hungary Jordan Kazakhstan Luxembourg Malaysia Nepal Oman Pakistan Qatar Romania Singapore Tanzania Uganda Yemen Zambia Zimbabwe' },
    { id: 'nature', prompt: 'A word about nature or weather', label: 'Nature and Weather', icon: '🌦️', group: 'Vocabulary',
      A1: 'beach cloud flower forest grass ice island lake moon mountain rain river sea sky snow spring star summer sun tree wind winter',
      A2: 'autumn bush cave desert earth field fog hill jungle leaf lightning nest ocean planet rainbow rock sand storm thunder valley volcano waterfall wave weather wood',
      B1: 'avalanche breeze canyon cliff drought earthquake flood glacier hurricane iceberg meadow mist pond quicksand rainforest stream tornado tsunami universe' },
    { id: 'verbs', prompt: 'A verb', label: 'Verbs', icon: '🏃', group: 'Word Types',
      A1: 'ask be buy come cook dance drink drive eat fly get give go have help jump know like listen live look make open play read run see sing sit sleep speak swim take talk walk want watch work write',
      A2: 'answer arrive begin borrow break bring build call carry catch change choose clean climb close count cry cut decide draw dream drop enjoy explain fall feel find finish follow forget grow guess hate hear hide hit hold hope hurry imagine invite join keep kick knock laugh learn leave lend lose love meet miss move need order pay pick plan point pull push put relax remember rent ride ring send shout show shut smile stop study teach tell think throw touch travel try turn understand use visit wait wake wash win wish worry',
      B1: 'admire bake ignore improve nod quit upload vanish volunteer yawn yell zoom' },
    { id: 'adjectives', prompt: 'An adjective', label: 'Adjectives', icon: '🎨', group: 'Word Types',
      A1: 'bad beautiful big black blue cheap cold dark easy expensive fast good green hard hot long new nice old orange red short slow small tall white yellow young',
      A2: 'awful boring bright brilliant clean comfortable dangerous delicious different difficult dirty dry empty famous fantastic fresh full great heavy high huge important interesting large light loud low modern narrow noisy open perfect pretty quick quiet rich round safe sharp soft strange strong sweet tasty terrible thick thin tiny ugly useful warm weak wet wide wonderful wrong',
      B1: 'ancient enormous fragile gigantic icy juicy massive neat ordinary pale rare smooth unusual valuable vast violet visible' },
    { id: 'feelings', prompt: 'A feeling or personality word', label: 'Feelings and Personality', icon: '😊', group: 'Word Types',
      A1: 'happy hungry sad thirsty tired',
      A2: 'afraid angry bored brave calm clever crazy excited friendly funny glad interested kind lazy lonely nervous OK polite proud quiet relaxed rude scared shy sleepy sorry surprised unhappy upset worried',
      B1: 'annoyed ashamed bossy cheerful confident confused curious disappointed embarrassed generous grateful grumpy honest jealous mean moody optimistic outgoing patient pessimistic sensitive stressed vain wise' },
    { id: 'shopping', prompt: 'Something you can buy', label: 'Things You Can Buy', icon: '🛒', group: 'Vocabulary',
      A1: 'apple bag ball bike book bread camera candy car computer cup dress eggs flowers game hat ice_cream jeans juice lamp milk orange_juice pen phone pizza shoes toy TV watch',
      A2: 'battery bracelet charger chocolate dictionary earphones envelope gift guitar hairbrush headphones jacket jewelry keyboard kettle kite laptop magazine map mirror necklace newspaper notebook paint perfume plant poster radio ring scarf shampoo soap stamp sunglasses tablet ticket toothbrush toothpaste umbrella vase video_game wallet yogurt yo-yo',
      B1: 'candle deodorant ink key_ring lipstick mattress nail_polish olive_oil quilt vitamins' },
  ];
  root.WORD_BANKS = WORD_BANKS;
  if (typeof module !== 'undefined' && module.exports) module.exports = WORD_BANKS;
})(typeof window !== 'undefined' ? window : globalThis);
